// Comprehensive Indian Market Products Catalog Data
module.exports = {
  // Electronics: 75 products
  electronics: [
    // Smartphones
    {
      id: 'apple-iphone-15-pro',
      name: 'Apple iPhone 15 Pro (128GB, Natural Titanium)',
      brand: 'Apple',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 129900,
      greenScore: 82.5,
      carbonKg: 66.0,
      convCarbonKg: 85.0,
      waterLiters: 1650,
      lifespan: 5.5,
      subscores: { carbon: 78, mat: 85, dur: 88, rec: 82, pack: 92, rep: 70, cert: 82 },
      materials: [
        { name: '100% Recycled Aluminium Substructure', percentage: 38, isRecycled: true },
        { name: 'Grade 5 Titanium Band', percentage: 22, isRecycled: false },
        { name: '100% Recycled Rare Earth Magnets', percentage: 15, isRecycled: true },
        { name: 'Ceramic Shield Glass', percentage: 25, isRecycled: false }
      ],
      packaging: '100% Fiber-based plastic-free retail box',
      certs: [{ id: 'epeat-gold', name: 'EPEAT Gold', issuer: 'Global Electronics Council', verified: true, desc: 'Eco design standard' }],
      strengths: ['100% recycled cobalt in battery', '100% recycled gold wire in mainboard', 'Eliminated leather accessories'],
      improvements: ['Proprietary component pairing restricts third-party repairs']
    },
    {
      id: 'apple-iphone-14',
      name: 'Apple iPhone 14 (128GB, Midnight)',
      brand: 'Apple',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 58999,
      greenScore: 78.0,
      carbonKg: 61.0,
      convCarbonKg: 82.0,
      waterLiters: 1520,
      lifespan: 5.0,
      subscores: { carbon: 75, mat: 80, dur: 84, rec: 78, pack: 90, rep: 68, cert: 80 },
      materials: [
        { name: 'Recycled Aluminium Frame', percentage: 40, isRecycled: true },
        { name: 'Bio-based plastics & glass', percentage: 35, isRecycled: false },
        { name: 'Recycled Tungsten & Gold', percentage: 10, isRecycled: true },
        { name: 'Display glass', percentage: 15, isRecycled: false }
      ],
      packaging: 'FSC-certified paper packaging',
      certs: [{ id: 'epeat-gold', name: 'EPEAT Gold', issuer: 'GEC', verified: true, desc: 'Electronics sustainability' }],
      strengths: ['Long software support cycle', 'Certified clean electricity suppliers'],
      improvements: ['Display adhesive difficult to service at home']
    },
    {
      id: 'samsung-galaxy-s24-ultra',
      name: 'Samsung Galaxy S24 Ultra 5G (256GB, Titanium Gray)',
      brand: 'Samsung',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 129999,
      greenScore: 81.0,
      carbonKg: 68.0,
      convCarbonKg: 89.0,
      waterLiters: 1720,
      lifespan: 5.5,
      subscores: { carbon: 76, mat: 84, dur: 87, rec: 80, pack: 88, rep: 72, cert: 80 },
      materials: [
        { name: 'Recycled Cobalt Battery & Steel', percentage: 32, isRecycled: true },
        { name: 'Recycled Ocean-Bound Plastics', percentage: 18, isRecycled: true },
        { name: 'Titanium chassis', percentage: 25, isRecycled: false },
        { name: 'Corning Gorilla Armor Glass', percentage: 25, isRecycled: false }
      ],
      packaging: '100% Recycled Paper Packaging Box',
      certs: [{ id: 'ul-ecologo', name: 'UL ECOLOGO Gold', issuer: 'UL Solutions', verified: true, desc: 'Multi-attribute evaluation' }],
      strengths: ['7 generations of OS upgrades', 'Recycled neodymium speaker modules'],
      improvements: ['High embodied energy in Snapdragon processor fabrication']
    },
    {
      id: 'samsung-galaxy-a54-5g',
      name: 'Samsung Galaxy A54 5G (128GB, Awesome Lime)',
      brand: 'Samsung',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 33499,
      greenScore: 76.5,
      carbonKg: 52.0,
      convCarbonKg: 74.0,
      waterLiters: 1380,
      lifespan: 4.5,
      subscores: { carbon: 76, mat: 75, dur: 80, rec: 74, pack: 85, rep: 68, cert: 78 },
      materials: [
        { name: 'Post-consumer recycled plastic buttons', percentage: 22, isRecycled: true },
        { name: 'Recycled glass back panel', percentage: 28, isRecycled: true },
        { name: 'Aluminium and copper traces', percentage: 50, isRecycled: false }
      ],
      packaging: 'Recycled Kraft cardboard box without plastic wrap',
      certs: [{ id: 'ul-ecologo', name: 'UL ECOLOGO', issuer: 'UL', verified: true, desc: 'Eco-certified' }],
      strengths: ['4 years OS + 5 years security patches', 'IP67 dust and water resistance'],
      improvements: ['No wall adapter included, but cable still packaged in PE wrap']
    },
    {
      id: 'samsung-galaxy-m34-5g',
      name: 'Samsung Galaxy M34 5G (128GB, Prism Silver)',
      brand: 'Samsung',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 15999,
      greenScore: 73.0,
      carbonKg: 46.0,
      convCarbonKg: 68.0,
      waterLiters: 1250,
      lifespan: 4.0,
      subscores: { carbon: 74, mat: 70, dur: 76, rec: 72, pack: 80, rep: 68, cert: 72 },
      materials: [
        { name: 'Polycarbonate with 15% PCR content', percentage: 45, isRecycled: true },
        { name: 'Reinforced glass', percentage: 25, isRecycled: false },
        { name: 'Silicon and metals', percentage: 30, isRecycled: false }
      ],
      packaging: 'Compact recycled box',
      certs: [{ id: 'bis-isi', name: 'BIS ISI Certified', issuer: 'Bureau of Indian Standards', verified: true, desc: 'Indian quality certification' }],
      strengths: ['Massive 6000mAh battery extends recharge lifespan', '4 Android version updates'],
      improvements: ['Battery glued with high-adhesion pull tabs']
    },
    {
      id: 'oneplus-12',
      name: 'OnePlus 12 5G (256GB, Silky Black)',
      brand: 'OnePlus',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 64999,
      greenScore: 74.0,
      carbonKg: 58.0,
      convCarbonKg: 78.0,
      waterLiters: 1480,
      lifespan: 4.5,
      subscores: { carbon: 72, mat: 74, dur: 82, rec: 73, pack: 76, rep: 65, cert: 74 },
      materials: [
        { name: 'Aluminium frame with 20% recycled content', percentage: 35, isRecycled: true },
        { name: 'Gorilla Glass Victus 2', percentage: 30, isRecycled: false },
        { name: 'Cobalt & Lithium cells', percentage: 25, isRecycled: false },
        { name: 'Internal alloys', percentage: 10, isRecycled: false }
      ],
      packaging: 'Standard red gift box (soy-based ink)',
      certs: [{ id: 'rohs', name: 'RoHS Compliant', issuer: 'EU RoHS Directive', verified: true, desc: 'Hazardous substance free' }],
      strengths: ['BHE Battery Health Engine preserves battery capacity for 1600 cycles', 'IP65 rating'],
      improvements: ['Proprietary SuperVOOC fast charger increases packaging size']
    },
    {
      id: 'oneplus-nord-ce4',
      name: 'OnePlus Nord CE4 5G (128GB, Celadon Marble)',
      brand: 'OnePlus',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 24999,
      greenScore: 72.5,
      carbonKg: 47.0,
      convCarbonKg: 65.0,
      waterLiters: 1290,
      lifespan: 3.5,
      subscores: { carbon: 73, mat: 71, dur: 76, rec: 70, pack: 75, rep: 66, cert: 70 },
      materials: [
        { name: 'Polycarbonate composite', percentage: 50, isRecycled: false },
        { name: 'Recycled tin in solder', percentage: 12, isRecycled: true },
        { name: 'Glass & Copper', percentage: 38, isRecycled: false }
      ],
      packaging: 'Minimal paperboard box',
      certs: [{ id: 'bis-isi', name: 'BIS Approved', issuer: 'BIS India', verified: true, desc: 'Safety standard' }],
      strengths: ['100W SUPERVOOC charging with 4-year battery lifespan guarantee', 'Clean software'],
      improvements: ['Plastics not yet fully post-consumer recycled']
    },
    {
      id: 'nothing-phone-2a',
      name: 'Nothing Phone (2a) 5G (128GB, Milk White)',
      brand: 'Nothing',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 23999,
      greenScore: 84.0,
      carbonKg: 52.0,
      convCarbonKg: 78.0,
      waterLiters: 1320,
      lifespan: 4.5,
      subscores: { carbon: 82, mat: 86, dur: 83, rec: 84, pack: 92, rep: 75, cert: 82 },
      materials: [
        { name: '100% Recycled Aluminium Midframe', percentage: 32, isRecycled: true },
        { name: '100% Recycled Tin in 6 Circuit Boards', percentage: 18, isRecycled: true },
        { name: '50% Bio-based & PCR Plastic Parts', percentage: 24, isRecycled: true },
        { name: 'Recycled Steel stamping scrap', percentage: 12, isRecycled: true },
        { name: 'Gorilla Glass 5', percentage: 14, isRecycled: false }
      ],
      packaging: 'Zero-plastic biodegradable unbleached pulp box',
      certs: [{ id: 'carbon-trust', name: 'Carbon Trust Audited', issuer: 'Carbon Trust UK', verified: true, desc: 'Audited carbon footprint of 52kg' }],
      strengths: ['Lowest carbon footprint in its class (52 kg CO₂e)', 'Made with 100% renewable electricity at final assembly', 'Plastic-free packaging'],
      improvements: ['Rear transparent adhesive makes camera module repair trickier']
    },
    {
      id: 'nothing-phone-2',
      name: 'Nothing Phone (2) Flagship 5G (256GB, Dark Grey)',
      brand: 'Nothing',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 36999,
      greenScore: 83.5,
      carbonKg: 53.4,
      convCarbonKg: 79.0,
      waterLiters: 1360,
      lifespan: 4.5,
      subscores: { carbon: 81, mat: 85, dur: 84, rec: 82, pack: 92, rep: 74, cert: 82 },
      materials: [
        { name: '100% Recycled Aluminium Frame', percentage: 35, isRecycled: true },
        { name: '100% Recycled Tin & Copper foil', percentage: 16, isRecycled: true },
        { name: 'PCR plastics in 9 internal components', percentage: 22, isRecycled: true },
        { name: 'Curved Gorilla Glass', percentage: 27, isRecycled: false }
      ],
      packaging: 'FSC-mix plastic-free tear-strip packaging',
      certs: [{ id: 'carbon-trust', name: 'Carbon Trust Certified', issuer: 'Carbon Trust', verified: true, desc: 'Certified cradle-to-grave footprint' }],
      strengths: ['SGS verified environmental profile', '3 major OS updates and 4 years bi-monthly security patches'],
      improvements: ['Glyph LED lighting adds minor component complexity']
    },
    {
      id: 'xiaomi-14',
      name: 'Xiaomi 14 5G Leica Flagship (512GB, Jade Green)',
      brand: 'Xiaomi',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 69999,
      greenScore: 73.5,
      carbonKg: 62.0,
      convCarbonKg: 82.0,
      waterLiters: 1540,
      lifespan: 4.5,
      subscores: { carbon: 72, mat: 74, dur: 80, rec: 73, pack: 75, rep: 66, cert: 72 },
      materials: [
        { name: 'CNC Carved Aluminium with 15% recycled alloy', percentage: 34, isRecycled: true },
        { name: 'Bio-ceramic leather or glass', percentage: 26, isRecycled: false },
        { name: 'Silicon-carbon battery cells', percentage: 24, isRecycled: false },
        { name: 'Optics and copper', percentage: 16, isRecycled: false }
      ],
      packaging: 'Standard white rigid board',
      certs: [{ id: 'rohs', name: 'RoHS Compliant', issuer: 'SGS', verified: true, desc: 'Lead and cadmium free' }],
      strengths: ['High energy density battery reduces physical raw mass', 'IP68 water sealing'],
      improvements: ['High transport carbon from international shipping']
    },
    {
      id: 'redmi-note-13-pro-plus',
      name: 'Redmi Note 13 Pro+ 5G (256GB, Fusion Purple)',
      brand: 'Redmi',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 31999,
      greenScore: 71.0,
      carbonKg: 54.0,
      convCarbonKg: 72.0,
      waterLiters: 1390,
      lifespan: 3.5,
      subscores: { carbon: 70, mat: 71, dur: 77, rec: 71, pack: 74, rep: 64, cert: 68 },
      materials: [
        { name: 'Vegan bio-leather back or glass', percentage: 30, isRecycled: false },
        { name: 'Polycarbonate inner chassis', percentage: 40, isRecycled: false },
        { name: 'Circuit boards and batteries', percentage: 30, isRecycled: false }
      ],
      packaging: 'Cardboard box with soy ink',
      certs: [{ id: 'bis-isi', name: 'BIS Registered', issuer: 'BIS India', verified: true, desc: 'National standard' }],
      strengths: ['IP68 certification increases resistance to liquid damage', 'Local Indian assembly in Noida'],
      improvements: ['Fast-charging brick generates extra electronic scrap over time']
    },
    {
      id: 'motorola-edge-50-pro',
      name: 'Motorola Edge 50 Pro 5G (256GB, Moonlight Pearl)',
      brand: 'Motorola',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 31999,
      greenScore: 81.0,
      carbonKg: 49.0,
      convCarbonKg: 75.0,
      waterLiters: 1280,
      lifespan: 4.0,
      subscores: { carbon: 80, mat: 82, dur: 83, rec: 81, pack: 94, rep: 70, cert: 78 },
      materials: [
        { name: 'Handmade Italian Acetate or Vegan Leather', percentage: 32, isRecycled: false },
        { name: '100% Recycled Aluminium Frame', percentage: 30, isRecycled: true },
        { name: 'Recycled solder tin', percentage: 12, isRecycled: true },
        { name: 'Glass & Electronics', percentage: 26, isRecycled: false }
      ],
      packaging: '100% Plastic-free eco box printed with soy ink & fragranced with bio-scent',
      certs: [{ id: 'fsc', name: 'FSC Certified Packaging', issuer: 'Forest Stewardship Council', verified: true, desc: 'Sustainably sourced forestry' }],
      strengths: ['100% plastic-free packaging box with natural soy ink', 'Pantone verified display color accuracy with lower blue emission'],
      improvements: ['Curved OLED edge glass more vulnerable to accidental drops']
    },
    {
      id: 'google-pixel-8a',
      name: 'Google Pixel 8a 5G (128GB, Bay Blue)',
      brand: 'Google',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 49999,
      greenScore: 86.0,
      carbonKg: 47.0,
      convCarbonKg: 76.0,
      waterLiters: 1210,
      lifespan: 7.0,
      subscores: { carbon: 84, mat: 88, dur: 86, rec: 85, pack: 95, rep: 78, cert: 88 },
      materials: [
        { name: '100% Recycled Aluminium in Enclosure', percentage: 40, isRecycled: true },
        { name: '76% Recycled Plastic in Back Cover', percentage: 24, isRecycled: true },
        { name: '100% Recycled Tin in Solder', percentage: 10, isRecycled: true },
        { name: 'Corning Gorilla Glass 3', percentage: 26, isRecycled: false }
      ],
      packaging: '100% Plastic-free unbleached paperboard box',
      certs: [
        { id: 'ul-ecologo', name: 'UL ECOLOGO Gold', issuer: 'UL', verified: true, desc: 'Top tier circular electronic design' },
        { id: 'energy-star', name: 'ENERGY STAR', issuer: 'EPA', verified: true, desc: 'Power efficiency' }
      ],
      strengths: ['Industry-leading 7 years of full Android OS and security upgrades', 'Back cover made with 76% recycled plastic', 'Plastic-free compact retail packaging'],
      improvements: ['Tensor G3 chip thermal dissipation can run warm during gaming']
    },
    {
      id: 'google-pixel-8-pro',
      name: 'Google Pixel 8 Pro (128GB, Obsidian)',
      brand: 'Google',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 93999,
      greenScore: 85.0,
      carbonKg: 61.0,
      convCarbonKg: 88.0,
      waterLiters: 1510,
      lifespan: 7.0,
      subscores: { carbon: 83, mat: 87, dur: 86, rec: 84, pack: 95, rep: 76, cert: 88 },
      materials: [
        { name: '100% Recycled Aluminium Frame', percentage: 42, isRecycled: true },
        { name: 'Recycled Tin & Magnet components', percentage: 16, isRecycled: true },
        { name: 'Gorilla Glass Victus 2', percentage: 42, isRecycled: false }
      ],
      packaging: '100% Plastic-free certified packaging box',
      certs: [{ id: 'ul-ecologo', name: 'UL ECOLOGO Gold', issuer: 'UL', verified: true, desc: 'Highest environmental rating' }],
      strengths: ['7-year OS maintenance lifespan eliminates early replacement', 'Official iFixit spare parts availability'],
      improvements: ['Camera visor glass complex to separate in recycling stream']
    },
    {
      id: 'realme-12-pro-plus',
      name: 'Realme 12 Pro+ 5G (256GB, Submarine Blue)',
      brand: 'Realme',
      category: 'Electronics',
      subcategory: 'Smartphones',
      price: 29999,
      greenScore: 71.5,
      carbonKg: 52.0,
      convCarbonKg: 73.0,
      waterLiters: 1360,
      lifespan: 3.5,
      subscores: { carbon: 71, mat: 72, dur: 78, rec: 70, pack: 74, rep: 63, cert: 69 },
      materials: [
        { name: 'Bio-inspired vegan leather', percentage: 28, isRecycled: false },
        { name: 'Plastic & alloy frame', percentage: 42, isRecycled: false },
        { name: 'Display & circuits', percentage: 30, isRecycled: false }
      ],
      packaging: 'Yellow cardboard box',
      certs: [{ id: 'bis-isi', name: 'BIS ISI Certified', issuer: 'BIS India', verified: true, desc: 'Consumer safety' }],
      strengths: ['Periscope telephoto zoom in sub-30k segment', 'Long 5000mAh battery life'],
      improvements: ['Shorter software upgrade roadmap (2 OS upgrades)']
    }
  ]
};
