# Food & Beverages Catalog Data (40 products)
# Indian Market Tea, Coffee, Plant Dairy, Organic Staples & Healthy Snacks

food_bev_items = [
  # --- TEA & SPECIALTY COFFEE (10 items) ---
  {
    "id": "tata-tea-gold-leaf-1kg",
    "name": "Tata Tea Gold Premium CTC Leaf Tea with 15% Long Leaves (1kg)",
    "brand": "Tata Tea",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 540,
    "score": 86.5,
    "carbon": 1.8,
    "conv_carb": 4.5,
    "water": 240,
    "lifespan": 1.0,
    "sub": [87, 88, 86, 85, 88, 82, 90],
    "explanation": "Sourced from 100% Rainforest Alliance Certified sustainable estates in Assam and Darjeeling with ethical living wages for tea plucker communities.",
    "mats": [{"name": "Rainforest Alliance Certified CTC Black Tea", "percentage": 85, "isRecycled": False, "isRenewable": True}, {"name": "Hand-picked Darjeeling Long Leaves", "percentage": 15, "isRecycled": False, "isRenewable": True}],
    "pack": "100% recyclable mono-material barrier poly pouch",
    "plastic_free": False,
    "certs": [{"id": "rainforest-alliance", "name": "Rainforest Alliance Certified", "issuer": "Rainforest Alliance", "verified": True, "description": "Ensures forest biodiversity conservation and fair agricultural labor standards"}, {"id": "trustea", "name": "trustea Verified Indian Tea Code", "issuer": "Solidaridad / Tea Board of India", "verified": True, "description": "Sustainability code for Indian small tea growers"}],
    "strengths": ["Rainforest Alliance audit ensures zero forest clearing and soil erosion prevention", "15% gently rolled long tea leaves enrich aroma without artificial flavor oils", "Mono-material packaging facilitates mechanical recycling in India"],
    "improvements": ["Outer pouch has thin metalized barrier layer"]
  },
  {
    "id": "organic-india-tulsi-green-tea-classic",
    "name": "Organic India Tulsi Green Tea Classic (USDA Organic, 25 Tea Bags)",
    "brand": "Organic India",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 195,
    "score": 93.0,
    "carbon": 0.5,
    "conv_carb": 2.2,
    "water": 85,
    "lifespan": 1.5,
    "sub": [94, 96, 90, 94, 96, 88, 95],
    "explanation": "Certified B-Corp brand sourcing holy Rama, Krishna, and Vana Tulsi grown with regenerative organic farming by marginal tribal farmers in UP and MP.",
    "mats": [{"name": "Regenerative Organic Rama & Krishna Tulsi", "percentage": 65, "isRecycled": False, "isRenewable": True}, {"name": "Certified Organic Green Tea Leaves", "percentage": 35, "isRecycled": False, "isRenewable": True}],
    "pack": "100% unbleached staple-free compostable tea bags in recycled paperboard box",
    "plastic_free": True,
    "certs": [{"id": "usda-organic", "name": "USDA Organic Certified", "issuer": "USDA", "verified": True, "description": "Zero chemical fertilizers or pesticides"}, {"id": "b-corp", "name": "Certified B Corporation", "issuer": "B Lab", "verified": True, "description": "Regenerative ethical supply chain standard"}, {"id": "jaivik-bharat", "name": "Jaivik Bharat FSSAI Organic Mark", "issuer": "FSSAI India", "verified": True, "description": "Indian organic standard"}],
    "strengths": ["Regenerative farming restores topsoil biology and locks carbon back into Indian soil", "Tea bags are staple-free and made from unbleached Manila hemp, 100% backyard compostable", "B-Corp social accountability"],
    "improvements": ["Each tea bag envelope has a thin protective aroma barrier film"]
  },
  {
    "id": "brooke-bond-red-label-natural-care",
    "name": "Brooke Bond Red Label Natural Care Tea with 5 Ayurvedic Herbs (1kg)",
    "brand": "Brooke Bond",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 570,
    "score": 84.0,
    "carbon": 2.1,
    "conv_carb": 4.6,
    "water": 260,
    "lifespan": 1.0,
    "sub": [84, 86, 85, 84, 86, 80, 88],
    "explanation": "Blended with 5 immunity herbs (Ashwagandha, Tulsi, Mulethi, Cardamom, and Ginger); trustea certified Indian estate provenance.",
    "mats": [{"name": "CTC Black Tea", "percentage": 95, "isRecycled": False, "isRenewable": True}, {"name": "5 Ayurvedic Herbs (Tulsi, Mulethi, Ashwagandha)", "percentage": 5, "isRecycled": False, "isRenewable": True}],
    "pack": "Multi-layer barrier box carton",
    "plastic_free": False,
    "certs": [{"id": "trustea", "name": "trustea Certified Estate Sourcing", "issuer": "Tea Board of India", "verified": True, "description": "Sustainable tea plantation code"}],
    "strengths": ["Infuses daily immunity herbs into ordinary Indian chai routine", "trustea verified plantation standards promote worker safety and soil conservation"],
    "improvements": ["Packaging incorporates inner foil laminate pouch"]
  },
  {
    "id": "wagh-bakri-premium-leaf-tea-500g",
    "name": "Wagh Bakri Premium CTC Spiced Leaf Tea 500g Carton",
    "brand": "Wagh Bakri",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 310,
    "score": 83.0,
    "carbon": 1.2,
    "conv_carb": 2.8,
    "water": 180,
    "lifespan": 1.0,
    "sub": [83, 85, 84, 83, 86, 80, 86],
    "explanation": "Selected from high-grown Assam estates; 100-year tea blending legacy with dedicated solar power at Dholka processing facility.",
    "mats": [{"name": "Assam CTC Grain & Dust Tea", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "100% recyclable cardboard outer carton with paper inner wrap",
    "plastic_free": True,
    "certs": [{"id": "trustea", "name": "trustea Code Compliant", "issuer": "Tea Board of India", "verified": True, "description": "Ethical tea sourcing"}],
    "strengths": ["Processed at solar-powered manufacturing facility in Gujarat", "Outer carton made from 100% recycled paperboard"],
    "improvements": ["Inner poly bag requires municipal soft-plastic recycling segregation"]
  },
  {
    "id": "vahdam-himalayan-green-tea-tin",
    "name": "Vahdam India Himalayan Imperial Green Tea Whole Leaves Tin 100g",
    "brand": "Vahdam",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 450,
    "score": 92.5,
    "carbon": 0.8,
    "conv_carb": 3.0,
    "water": 90,
    "lifespan": 2.0,
    "sub": [93, 95, 92, 94, 95, 88, 94],
    "explanation": "Certified Climate Neutral and Plastic Neutral Indian tea brand; direct farm-to-cup sourcing in an infinitely reusable steel caddy tin.",
    "mats": [{"name": "100% Whole Himalayan Green Tea Leaves", "percentage": 60, "isRecycled": False, "isRenewable": True}, {"name": "Food-grade Reusable Steel Caddy Tin", "percentage": 40, "isRecycled": True}],
    "pack": "100% infinitely recyclable food-grade tin canister (zero single-use plastic)",
    "plastic_free": True,
    "certs": [{"id": "climate-neutral", "name": "Certified Climate Neutral", "issuer": "Climate Neutral Org", "verified": True, "description": "100% operational emissions measured, reduced & offset"}, {"id": "plastic-neutral", "name": "Certified Plastic Neutral", "issuer": "rePurpose Global", "verified": True, "description": "Recycles 100% equal plastic footprint"}],
    "strengths": ["Direct-from-source model cuts middleman supply chain emissions by 60%", "Steel tin canister is reusable for decades as a kitchen spice container", "1% of revenue directed to TEAch Me farmer education initiative"],
    "improvements": ["Premium loose leaf format requires dedicated infuser or teapot"]
  },
  {
    "id": "blue-tokai-attikan-estate-coffee",
    "name": "Blue Tokai Coffee Roasters Attikan Estate Medium-Dark Roast Whole Beans 250g",
    "brand": "Blue Tokai",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 490,
    "score": 91.0,
    "carbon": 1.1,
    "conv_carb": 3.5,
    "water": 210,
    "lifespan": 0.5,
    "sub": [92, 94, 90, 92, 94, 85, 92],
    "explanation": "Single-estate 100% Arabica shade-grown under native forest canopy in Biligirirangana Hills (BR Hills, Karnataka), protecting wildlife habitats.",
    "mats": [{"name": "100% Shade-Grown Single Origin Arabica Coffee", "percentage": 88, "isRecycled": False, "isRenewable": True}, {"name": "Recyclable Kraft Valve Pouch", "percentage": 12, "isRecycled": True}],
    "pack": "Mono-material recyclable kraft pouch with one-way degassing valve",
    "plastic_free": False,
    "certs": [{"id": "shade-grown", "name": "Shade-Grown Bird Friendly Standard", "issuer": "Attikan Wildlife Sanctuary Audit", "verified": True, "description": "Preserves native tiger & hornbill canopy forests"}, {"id": "direct-trade", "name": "Direct Trade Verified", "issuer": "Blue Tokai Roasters", "verified": True, "description": "Pays 35% above Fair Trade minimums"}],
    "strengths": ["Shade-grown coffee preserves biodiverse Western Ghats forest canopy instead of clear-cutting land for sun monocultures", "Direct trade pays Indian estate growers substantial premiums above global commodity prices", "Roasted fresh on demand to prevent warehouse waste"],
    "improvements": ["Degassing valve contains small plastic filter membrane"]
  },
  {
    "id": "sleepy-owl-cold-brew-packs",
    "name": "Sleepy Owl Cold Brew Pitcher Packs Dark Roast Arabica (Pack of 5, 250g)",
    "brand": "Sleepy Owl",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 400,
    "score": 88.0,
    "carbon": 1.2,
    "conv_carb": 3.6,
    "water": 190,
    "lifespan": 0.7,
    "sub": [89, 90, 88, 88, 92, 82, 88],
    "explanation": "100% Grade-A Arabica from Chikmagalur; cold brewing in tap water consumes zero electricity for heating.",
    "mats": [{"name": "Chikmagalur Single-Origin Arabica", "percentage": 82, "isRecycled": False, "isRenewable": True}, {"name": "Unbleached Corn-Fiber Steeping Brew Bags", "percentage": 8, "isRecycled": False, "isRenewable": True}, {"name": "Recycled Paperboard Box", "percentage": 10, "isRecycled": True}],
    "pack": "Compostable corn-starch filter bags in recycled cardboard box",
    "plastic_free": True,
    "certs": [{"id": "corn-fiber", "name": "100% Bio-based Filter Bags", "issuer": "TÜV Austria", "verified": True, "description": "Compostable filter bags"}],
    "strengths": ["Cold-water extraction requires zero kettle heating electricity", "Filter bags are made from biodegradable plant starch and decompose naturally"],
    "improvements": ["Individual brew packs require outer foil seal to maintain freshness"]
  },
  {
    "id": "nescafe-classic-glass-jar-200g",
    "name": "Nescafe Classic 100% Pure Instant Coffee Glass Jar 200g",
    "brand": "Nescafe",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 475,
    "score": 84.0,
    "carbon": 1.6,
    "conv_carb": 3.8,
    "water": 220,
    "lifespan": 1.5,
    "sub": [85, 86, 88, 87, 90, 80, 82],
    "explanation": "Packaged in an infinitely recyclable heavy glass jar with tamper-evident seal; responsibly sourced Robusta beans from South India.",
    "mats": [{"name": "100% Robusta & Arabica Coffee Beans", "percentage": 30, "isRecycled": False, "isRenewable": True}, {"name": "Recyclable Heavy Glass Jar", "percentage": 65, "isRecycled": True}, {"name": "PP Screw Cap", "percentage": 5, "isRecycled": False}],
    "pack": "100% recyclable glass jar with plastic screw cap",
    "plastic_free": False,
    "certs": [{"id": "nescafe-plan", "name": "Nescafe Responsible Sourcing 2025", "issuer": "4C Association", "verified": True, "description": "Sustainable coffee farming verification"}],
    "strengths": ["Heavy glass jar is widely reused in Indian households for storing spices and salt for decades", "100% pure instant coffee with zero chicory adulteration"],
    "improvements": ["Thermal spray drying process requires industrial fossil fuel heat"]
  },
  {
    "id": "continental-xtra-instant-coffee-200g",
    "name": "Continental Xtra Instant South Indian Filter Coffee Blend (70% Coffee, 30% Chicory, 200g Pouch)",
    "brand": "Continental",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 275,
    "score": 82.5,
    "carbon": 1.4,
    "conv_carb": 3.4,
    "water": 180,
    "lifespan": 1.0,
    "sub": [83, 85, 84, 83, 86, 78, 82],
    "explanation": "Blended with 30% roasted chicory root grown in Gujarat, which uses 60% less water than coffee cultivation.",
    "mats": [{"name": "Indian Coffee Beans", "percentage": 70, "isRecycled": False, "isRenewable": True}, {"name": "Roasted Chicory Root (Cichorium Intybus)", "percentage": 30, "isRecycled": False, "isRenewable": True}],
    "pack": "Recyclable zipper pouch",
    "plastic_free": False,
    "certs": [{"id": "fssai-clean", "name": "FSSAI Grade 1 Instant Coffee", "issuer": "FSSAI", "verified": True, "description": "National food purity standard"}],
    "strengths": ["Chicory root requires 60% less agricultural water and fertilizer than coffee trees, reducing total beverage footprint", "Zipper pouch cuts packaging mass vs glass jars"],
    "improvements": ["Pouch requires municipal multi-layer plastic waste disposal"]
  },
  {
    "id": "society-tea-premium-leaf-500g",
    "name": "Society Tea Premium Assam CTC Leaf Tea Glass Jar 500g",
    "brand": "Society Tea",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 310,
    "score": 85.0,
    "carbon": 1.3,
    "conv_carb": 3.2,
    "water": 190,
    "lifespan": 1.0,
    "sub": [86, 87, 88, 86, 90, 82, 84],
    "explanation": "Packed in an airtight reusable food storage container; premium strong Assam dust and leaf blend.",
    "mats": [{"name": "Assam CTC Tea", "percentage": 70, "isRecycled": False, "isRenewable": True}, {"name": "Reusable Food-grade Container", "percentage": 30, "isRecycled": True}],
    "pack": "Reusable food-grade container",
    "plastic_free": False,
    "certs": [{"id": "trustea", "name": "trustea Verified", "issuer": "Tea Board of India", "verified": True, "description": "Sustainable Indian tea code"}],
    "strengths": ["Container is deliberately designed for direct second-life reuse in kitchen pantry", "Consistent quality blend"],
    "improvements": ["Plastic lid"]
  },

  # --- PLANT-BASED MILK & COLD PRESSED BEVERAGES (10 items) ---
  {
    "id": "epigamia-almond-milk-unsweetened",
    "name": "Epigamia Almond Milk Unsweetened with High Calcium 1L (Tetra Pak)",
    "brand": "Epigamia",
    "cat": "Food & Beverages",
    "subcat": "Plant-Based Milk",
    "price": 275,
    "score": 89.0,
    "carbon": 0.7,
    "conv_carb": 3.2,
    "water": 180,
    "lifespan": 0.75,
    "sub": [90, 92, 88, 89, 92, 85, 90],
    "explanation": "Generates 78% lower greenhouse gas emissions than conventional dairy cow milk; fortified with plant-derived calcium and vitamin D.",
    "mats": [{"name": "California Almonds (4.5% paste)", "percentage": 10, "isRecycled": False, "isRenewable": True}, {"name": "Aqua & Calcium Carbonate", "percentage": 88, "isRecycled": False}, {"name": "Tetra Pak Multi-Layer Aseptic Carton", "percentage": 2, "isRecycled": True}],
    "pack": "FSC-certified Tetra Pak aseptic carton with bio-based sugarcane cap",
    "plastic_free": False,
    "certs": [{"id": "fsc-carton", "name": "FSC Certified Paperboard Carton", "issuer": "Forest Stewardship Council", "verified": True, "description": "Wood fibers from responsibly managed forests"}, {"id": "vegan-india", "name": "Vegan India Certified", "issuer": "Vegan Society", "verified": True, "description": "Zero dairy or animal derivatives"}],
    "strengths": ["Cuts lifecycle carbon emissions by 78% compared to dairy milk", "Zero methane emissions associated with livestock cattle enteric fermentation", "Requires zero refrigeration prior to opening, saving store retail electricity"],
    "improvements": ["Almond trees require significant agricultural irrigation water"]
  },
  {
    "id": "oatly-barista-edition-oat-milk",
    "name": "Oatly Barista Edition 100% Swedish Oat Milk 1L (Tetra Pak)",
    "brand": "Oatly",
    "cat": "Food & Beverages",
    "subcat": "Plant-Based Milk",
    "price": 379,
    "score": 93.5,
    "carbon": 0.49,
    "conv_carb": 3.2,
    "water": 48,
    "lifespan": 0.8,
    "sub": [95, 96, 92, 92, 94, 88, 95],
    "explanation": "Audited carbon footprint printed directly on carton (0.49 kg CO₂e per liter); uses 80% less land and 60% less water than dairy milk.",
    "mats": [{"name": "Enzymatically Processed Oats (10%)", "percentage": 12, "isRecycled": False, "isRenewable": True}, {"name": "Low-erucic Rapeseed Oil & Dipotassium Phosphate", "percentage": 4, "isRecycled": False, "isRenewable": True}, {"name": "Water Base", "percentage": 82, "isRecycled": False}, {"name": "Aseptic Carton", "percentage": 2, "isRecycled": True}],
    "pack": "Tetra Brik Aseptic carton with plant-based plastic cap",
    "plastic_free": False,
    "certs": [{"id": "carbon-declaration", "name": "Carbon Footprint Certified (0.49 kg CO₂e/L)", "issuer": "CarbonCloud Sweden", "verified": True, "description": "Audited lifecycle emissions printed on carton"}, {"id": "fsc", "name": "FSC Certified Carton", "issuer": "FSC", "verified": True, "description": "Responsible forestry"}],
    "strengths": ["Prints audited lifecycle greenhouse gas footprint openly on the front of every carton", "Oats require 75% less water than almonds and zero cattle methane", "Micro-foams perfectly in specialty coffee without curdling"],
    "improvements": ["Imported from European production facilities increases transport shipping miles to India"]
  },
  {
    "id": "sofit-soya-drink-vanilla-1l",
    "name": "Sofit Soya Drink Vanilla High Protein Calcium 1L (Tetra Pak)",
    "brand": "Sofit",
    "cat": "Food & Beverages",
    "subcat": "Plant-Based Milk",
    "price": 145,
    "score": 88.5,
    "carbon": 0.55,
    "conv_carb": 3.2,
    "water": 55,
    "lifespan": 0.75,
    "sub": [90, 91, 88, 89, 90, 85, 88],
    "explanation": "Non-GMO soybean protein matched to dairy milk protein content (3.2g per 100ml) with zero lactose or cholesterol.",
    "mats": [{"name": "Non-GMO Whole Soybeans", "percentage": 14, "isRecycled": False, "isRenewable": True}, {"name": "Natural Vanilla & Plant Calcium", "percentage": 4, "isRecycled": False, "isRenewable": True}, {"name": "Water Base", "percentage": 80, "isRecycled": False}, {"name": "Carton", "percentage": 2, "isRecycled": True}],
    "pack": "FSC-certified aseptic Tetra Pak",
    "plastic_free": False,
    "certs": [{"id": "non-gmo", "name": "Non-GMO Soy Certified", "issuer": "SGS", "verified": True, "description": "Zero genetically modified crops"}, {"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Sustainable carton"}],
    "strengths": ["Matches cow milk protein gram-for-gram at half the retail price of almond milk", "Non-GMO certified beans sourced domestically in Madhya Pradesh"],
    "improvements": ["Contains added raw cane sugar in vanilla flavor"]
  },
  {
    "id": "raw-pressery-valencia-orange-juice",
    "name": "Raw Pressery 100% Cold Pressed Valencia Orange Juice 1L",
    "brand": "Raw Pressery",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 250,
    "score": 87.0,
    "carbon": 1.2,
    "conv_carb": 2.8,
    "water": 120,
    "lifespan": 0.2,
    "sub": [88, 90, 85, 86, 90, 80, 88],
    "explanation": "Cold-pressed with High Pressure Processing (HPP) with zero added sugar, preservatives, or thermal heat pasteurization.",
    "mats": [{"name": "100% Fresh Valencia Oranges", "percentage": 92, "isRecycled": False, "isRenewable": True}, {"name": "100% Recyclable Clear PET Bottle", "percentage": 8, "isRecycled": True}],
    "pack": "100% recyclable virgin-free rPET bottle",
    "plastic_free": False,
    "certs": [{"id": "no-added-sugar", "name": "100% Pure Fruit Juice (Zero Added Sugar)", "issuer": "FSSAI", "verified": True, "description": "Zero synthetic chemicals"}, {"id": "clean-label", "name": "Clean Label Certified", "issuer": "Raw Pressery", "verified": True, "description": "Cold pressure pasteurized"}],
    "strengths": ["Cold hydraulic pressing extracts juice without heat oxidation, preserving 95% of natural Vitamin C", "Zero synthetic preservatives or chemical sulfites"],
    "improvements": ["Requires cold-chain refrigeration logistics throughout transit"]
  },
  {
    "id": "raw-pressery-coconut-water-200ml",
    "name": "Raw Pressery 100% Pure Tender Coconut Water 200ml (Bottle)",
    "brand": "Raw Pressery",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 60,
    "score": 88.5,
    "carbon": 0.4,
    "conv_carb": 1.8,
    "water": 25,
    "lifespan": 0.5,
    "sub": [90, 92, 88, 88, 90, 82, 88],
    "explanation": "Sourced from tender green coconuts harvested in Tamil Nadu and Kerala; naturally isotonic with five vital electrolytes.",
    "mats": [{"name": "100% Pure Tender Coconut Water", "percentage": 93, "isRecycled": False, "isRenewable": True}, {"name": "Recycled PET Bottle", "percentage": 7, "isRecycled": True}],
    "pack": "Recyclable clear bottle",
    "plastic_free": False,
    "certs": [{"id": "natural", "name": "100% Natural Isotonic Beverage", "issuer": "FSSAI", "verified": True, "description": "No added water or sugar"}],
    "strengths": ["Natural bio-hydration replaces chemical artificial electrolyte powders", "Sourced directly from coconut farmer groves in South India"],
    "improvements": ["Single-serve 200ml format creates packaging waste per volume compared to 1L format"]
  },
  {
    "id": "paper-boat-aamras-mango-juice-1l",
    "name": "Paper Boat Aamras Real Mango Fruit Juice 1L (Tetra Pak)",
    "brand": "Paper Boat",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 125,
    "score": 85.0,
    "carbon": 1.1,
    "conv_carb": 2.6,
    "water": 110,
    "lifespan": 0.5,
    "sub": [86, 88, 84, 84, 88, 80, 86],
    "explanation": "Crafted with 45% rich real mango pulp from Ratnagiri Alphonso and Raspuri mangoes; zero artificial colors or preservatives.",
    "mats": [{"name": "Alphonso & Raspuri Mango Pulp", "percentage": 45, "isRecycled": False, "isRenewable": True}, {"name": "Water & Sugar", "percentage": 53, "isRecycled": False}, {"name": "Tetra Pak", "percentage": 2, "isRecycled": True}],
    "pack": "FSC-certified Tetra Pak carton",
    "plastic_free": False,
    "certs": [{"id": "fsc", "name": "FSC Certified Packaging", "issuer": "FSC", "verified": True, "description": "Responsible forestry"}],
    "strengths": ["High 45% real mango fruit pulp content supports domestic Indian fruit farmers", "Tetra Pak preserves juice without chemical antimicrobial preservatives"],
    "improvements": ["Contains added sugar to balance sour Raspuri mango notes"]
  },
  {
    "id": "b-natural-mixed-fruit-juice-1l",
    "name": "B Natural Mixed Fruit Juice with 100% Indian Fruit Pulp 1L",
    "brand": "B Natural",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 110,
    "score": 86.0,
    "carbon": 1.0,
    "conv_carb": 2.7,
    "water": 105,
    "lifespan": 0.5,
    "sub": [87, 88, 86, 85, 88, 80, 88],
    "explanation": "Made from 100% Indian fruit pulp directly from ITC e-Choupal network of smallholder Indian farmers; zero imported concentrates.",
    "mats": [{"name": "Indian Fruit Pulps (Mango, Guava, Pomegranate)", "percentage": 42, "isRecycled": False, "isRenewable": True}, {"name": "Water Base", "percentage": 56, "isRecycled": False}, {"name": "Aseptic Board", "percentage": 2, "isRecycled": True}],
    "pack": "FSC-certified Tetra Pak aseptic carton",
    "plastic_free": False,
    "certs": [{"id": "e-choupal", "name": "ITC e-Choupal Sourced", "issuer": "ITC Agri Business", "verified": True, "description": "Direct fair pricing for rural Indian farming families"}],
    "strengths": ["100% Indian fruit pulp avoids overseas shipping carbon of imported fruit concentrates", "Supports domestic farm livelihoods via e-Choupal"],
    "improvements": ["Carton recycling requires access to specialized pulping facilities"]
  },
  {
    "id": "amul-taaza-toned-milk-1l",
    "name": "Amul Taaza Homogenised Toned Milk 1L (Tetra Fino Aseptic Pack)",
    "brand": "Amul",
    "cat": "Food & Beverages",
    "subcat": "Plant-Based Milk",
    "price": 72,
    "score": 81.0,
    "carbon": 2.2,
    "conv_carb": 3.4,
    "water": 650,
    "lifespan": 0.5,
    "sub": [80, 82, 84, 82, 86, 78, 88],
    "explanation": "World's largest dairy cooperative owned by 3.6 million Indian milk farmers; UHT treatment enables 180-day shelf life without refrigeration.",
    "mats": [{"name": "Homogenised Toned Milk (3% Fat, 8.5% SNF)", "percentage": 98, "isRecycled": False, "isRenewable": True}, {"name": "Tetra Fino Multi-layer Barrier Pouch", "percentage": 2, "isRecycled": True}],
    "pack": "Tetra Fino multi-layer aseptic pack",
    "plastic_free": False,
    "certs": [{"id": "amul-coop", "name": "Amul Cooperative Model Certified", "issuer": "GCMMF India", "verified": True, "description": "Over 80% of consumer price returned to village farmers"}],
    "strengths": ["Returns over 80% of consumer rupee directly to smallholder Indian dairy farmers", "Aseptic pack eliminates store chilled display electricity emissions"],
    "improvements": ["Dairy cattle generate methane during digestion"]
  },
  {
    "id": "mother-dairy-cow-milk-poly-1l",
    "name": "Mother Dairy Cow Milk (Fresh Chilled Daily, 1L Poly Pouch)",
    "brand": "Mother Dairy",
    "cat": "Food & Beverages",
    "subcat": "Plant-Based Milk",
    "price": 57,
    "score": 76.0,
    "carbon": 2.4,
    "conv_carb": 3.5,
    "water": 710,
    "lifespan": 0.05,
    "sub": [75, 78, 80, 76, 78, 72, 84],
    "explanation": "Pasteurized cow milk sourced from rural dairy cooperatives under National Dairy Development Board (NDDB).",
    "mats": [{"name": "Pasteurized Cow Milk", "percentage": 98, "isRecycled": False, "isRenewable": True}, {"name": "LDPE Poly Pouch", "percentage": 2, "isRecycled": False}],
    "pack": "Lightweight LDPE poly pouch",
    "plastic_free": False,
    "certs": [{"id": "nddb", "name": "NDDB National Dairy Standard", "issuer": "National Dairy Development Board", "verified": True, "description": "Cooperative small farmer development"}],
    "strengths": ["Low retail price provides affordable childhood nutrition across North India", "Minimalist thin poly pouch has very low initial packaging mass"],
    "improvements": ["Thin LDPE milk pouches are difficult to collect and recycle, frequently clogging municipal drains"]
  },
  {
    "id": "bira-91-non-alcoholic-beer",
    "name": "Bira 91 0.0 Zero Alcohol Craft Beer 330ml Can",
    "brand": "Bira 91",
    "cat": "Food & Beverages",
    "subcat": "Specialty Coffee",
    "price": 100,
    "score": 86.5,
    "carbon": 0.45,
    "conv_carb": 1.2,
    "water": 32,
    "lifespan": 0.75,
    "sub": [88, 88, 88, 92, 94, 80, 84],
    "explanation": "Brewed with two-row barley malt and real hops with zero alcohol, packaged in an infinitely recyclable lightweight aluminium can.",
    "mats": [{"name": "Barley Malt, Hops & Yeast", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Carbonated Water", "percentage": 65, "isRecycled": False}, {"name": "100% Recyclable Aluminium Can", "percentage": 10, "isRecycled": True}],
    "pack": "100% infinitely recyclable aluminium can",
    "plastic_free": True,
    "certs": [{"id": "can-recyclable", "name": "100% Infinitely Recyclable Aluminium", "issuer": "Can Manufacturers Institute", "verified": True, "description": "Over 75% of all aluminium ever produced is still in circulation"}],
    "strengths": ["Aluminium can has over 90% collection and recycling rate in India via scrap kabadiwala channels", "100% plastic-free packaging"],
    "improvements": ["Barley malting consumes agricultural thermal energy"]
  },

  # --- ORGANIC STAPLES, GRAINS & HEALTHY OILS (12 items) ---
  {
    "id": "24-mantra-organic-brown-basmati-rice",
    "name": "24 Mantra Organic Brown Basmati Rice (Pesticide-Free, 1kg)",
    "brand": "24 Mantra",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 175,
    "score": 93.0,
    "carbon": 1.6,
    "conv_carb": 4.2,
    "water": 1400,
    "lifespan": 1.0,
    "sub": [94, 96, 92, 93, 92, 88, 95],
    "explanation": "Certified organic brown basmati rice grown by 45,000 certified smallholder Indian farmers using System of Rice Intensification (SRI) which cuts water by 40%.",
    "mats": [{"name": "100% Certified Organic Brown Basmati Rice (Whole Grain)", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "Recyclable vacuum sealed pouch",
    "plastic_free": False,
    "certs": [{"id": "jaivik-bharat", "name": "Jaivik Bharat FSSAI Organic", "issuer": "FSSAI India", "verified": True, "description": "National organic food certification"}, {"id": "usda-organic", "name": "USDA Organic Certified", "issuer": "USDA", "verified": True, "description": "Zero synthetic chemicals or GMOs"}, {"id": "eu-organic", "name": "EU Organic Standard", "issuer": "Control Union", "verified": True, "description": "Strict European pesticide limit compliance"}],
    "strengths": ["Grown without chemical fertilizers, preventing toxic agricultural pesticide runoff into Indian river basins", "Retains bran layer rich in dietary fiber and essential B-vitamins", "SRI cultivation cuts methane emissions by aerating paddy fields"],
    "improvements": ["Basmati rice remains an agricultural water-intensive crop"]
  },
  {
    "id": "tata-sampann-unpolished-toor-dal",
    "name": "Tata Sampann Unpolished Toor Dal with Natural Protein 1kg",
    "brand": "Tata Sampann",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 195,
    "score": 91.5,
    "carbon": 0.8,
    "conv_carb": 2.5,
    "water": 450,
    "lifespan": 1.0,
    "sub": [92, 94, 92, 92, 90, 86, 92],
    "explanation": "100% unpolished pigeon pea pulses that do not undergo artificial water, oil, or leather polishing, preserving natural grain protein and saving polishing water.",
    "mats": [{"name": "100% Unpolished Split Pigeon Peas (Arhar / Toor)", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "Food-grade recyclable poly pack",
    "plastic_free": False,
    "certs": [{"id": "unpolished", "name": "Zero Polish Quality Guarantee", "issuer": "Tata Chemicals Food Labs", "verified": True, "description": "No chemical or leather roller polishing"}, {"id": "fssai-pure", "name": "FSSAI Grade 1 Standards", "issuer": "FSSAI", "verified": True, "description": "Pure pulses standard"}],
    "strengths": ["Eliminates commercial dal polishing which consumes millions of liters of oil and water and strips the protein-rich aleurone layer", "Pulses fix atmospheric nitrogen into the soil naturally, reducing synthetic nitrogen fertilizer needs"],
    "improvements": ["Plastic pouch packaging"]
  },
  {
    "id": "organic-india-organic-quinoa",
    "name": "Organic India Certified Organic Quinoa 500g",
    "brand": "Organic India",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 275,
    "score": 92.0,
    "carbon": 0.6,
    "conv_carb": 2.1,
    "water": 280,
    "lifespan": 1.5,
    "sub": [93, 95, 92, 92, 92, 86, 94],
    "explanation": "Regeneratively cultivated in Bundelkhand, India; complete plant protein containing all 9 essential amino acids.",
    "mats": [{"name": "100% Certified Organic Indian Quinoa Seeds", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "Recyclable sealed food pouch",
    "plastic_free": False,
    "certs": [{"id": "usda-organic", "name": "USDA Organic", "issuer": "USDA", "verified": True, "description": "Organic agricultural inputs"}, {"id": "jaivik-bharat", "name": "Jaivik Bharat Certified", "issuer": "Govt of India", "verified": True, "description": "National organic accreditation"}],
    "strengths": ["Grown domestically in drought-prone Bundelkhand, providing sustainable climate-resilient livelihoods to local farmers", "Complete plant protein source"],
    "improvements": ["Saponin natural bitter outer coating must be pre-rinsed"]
  },
  {
    "id": "aashirvaad-select-sharbati-atta",
    "name": "Aashirvaad Select 100% MP Sharbati Whole Wheat Atta 5kg",
    "brand": "Aashirvaad",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 315,
    "score": 88.0,
    "carbon": 2.8,
    "conv_carb": 6.5,
    "water": 980,
    "lifespan": 0.5,
    "sub": [89, 90, 88, 88, 88, 82, 90],
    "explanation": "Crafted from heavy golden Sharbati wheat grains harvested in the fertile rain-fed Sehore region of Madhya Pradesh; ground with 100% whole grain retention.",
    "mats": [{"name": "100% Rain-Fed Sharbati Whole Wheat", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "Heavy duty recyclable woven sack",
    "plastic_free": False,
    "certs": [{"id": "fssai-pure", "name": "100% Whole Wheat Zero Maida", "issuer": "FSSAI", "verified": True, "description": "Zero refined flour adulteration"}],
    "strengths": ["Sharbati wheat is predominantly rain-fed, avoiding excessive groundwater tube well depletion in Central India", "Retains 100% wheat germ and dietary fiber for optimal digestive wellness"],
    "improvements": ["Heavy 5kg polywoven sack requires plastic recycling drop-off"]
  },
  {
    "id": "24-mantra-cold-pressed-mustard-oil",
    "name": "24 Mantra Organic Cold Pressed Mustard Oil (Kachi Ghani) 1L Glass Bottle",
    "brand": "24 Mantra",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 299,
    "score": 94.0,
    "carbon": 1.2,
    "conv_carb": 4.1,
    "water": 320,
    "lifespan": 1.0,
    "sub": [95, 96, 92, 95, 96, 90, 95],
    "explanation": "Expeller pressed at low temperatures without synthetic chemical solvents (hexane) or bleaching, packed in an infinitely recyclable 1L glass bottle.",
    "mats": [{"name": "100% Organic Mustard Seeds (Kachi Ghani Cold-Pressed)", "percentage": 82, "isRecycled": False, "isRenewable": True}, {"name": "Recyclable Glass Bottle", "percentage": 18, "isRecycled": True}],
    "pack": "100% recyclable glass bottle with metal screw cap",
    "plastic_free": True,
    "certs": [{"id": "jaivik-bharat", "name": "Jaivik Bharat Organic", "issuer": "FSSAI", "verified": True, "description": "Chemical-free organic certification"}, {"id": "hexane-free", "name": "100% Hexane Solvent Free", "issuer": "Eurofins", "verified": True, "description": "Pure expeller mechanical extraction"}],
    "strengths": ["Zero petroleum hexane solvent extraction used (conventional refined oils use hexane)", "Glass bottle packaging completely eliminates plastic phthalate leaching into cooking oil", "Naturally rich in heart-healthy Omega-3 and Omega-6 fatty acids"],
    "improvements": ["Strong natural pungency (allyl isothiocyanate) may be potent for non-traditional recipes"]
  },
  {
    "id": "puvi-cold-pressed-groundnut-oil",
    "name": "Puvi Pure Cold Pressed Virgin Groundnut Oil (Chekku / Ghani) 1L Tin",
    "brand": "Puvi",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 380,
    "score": 93.5,
    "carbon": 1.4,
    "conv_carb": 4.2,
    "water": 350,
    "lifespan": 1.0,
    "sub": [94, 95, 93, 94, 96, 90, 94],
    "explanation": "Extracted in traditional wooden cold press (Vagai Mara Chekku) below 45°C; packed in an infinitely recyclable food-grade tin canister.",
    "mats": [{"name": "Cold-Pressed Peanut Oil (Chekku)", "percentage": 78, "isRecycled": False, "isRenewable": True}, {"name": "Food-grade Steel Tin Container", "percentage": 22, "isRecycled": True}],
    "pack": "100% recyclable tin container with metal spout",
    "plastic_free": True,
    "certs": [{"id": "fssai-pure", "name": "Zero Chemical Solvents", "issuer": "FSSAI", "verified": True, "description": "Unrefined edible oil"}],
    "strengths": ["Tinplate metal container protects oil from photo-oxidation and is 100% plastic-free", "Traditional wooden press prevents frictional heat from destroying natural antioxidants"],
    "improvements": ["Higher cost per liter than subsidized industrial palm oil blends"]
  },
  {
    "id": "fortune-sunlite-sunflower-oil-1l",
    "name": "Fortune Sunlite Refined Sunflower Oil with Vitamin A & D 1L Pouch",
    "brand": "Fortune",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 145,
    "score": 75.0,
    "carbon": 2.8,
    "conv_carb": 4.2,
    "water": 580,
    "lifespan": 0.75,
    "sub": [76, 75, 80, 78, 80, 72, 78],
    "explanation": "Light neutral cooking oil with high smoke point; enriched with vitamins under government food fortification standards.",
    "mats": [{"name": "Refined Sunflower Oil", "percentage": 98, "isRecycled": False, "isRenewable": True}, {"name": "Multi-layer Plastic Pouch", "percentage": 2, "isRecycled": False}],
    "pack": "Multi-layer pouch",
    "plastic_free": False,
    "certs": [{"id": "fssai-fortified", "name": "+F Fortified Food Mark", "issuer": "FSSAI India", "verified": True, "description": "National nutritional fortification"}],
    "strengths": ["High 232°C smoke point prevents toxic trans-fat formation during high-heat deep frying", "Affordable cooking oil accessible to all Indian households"],
    "improvements": ["Chemical refining and bleaching processes; thin plastic pouch packaging"]
  },
  {
    "id": "saffola-gold-heart-oil-1l",
    "name": "Saffola Gold Pro Healthy Heart Blended Cooking Oil (Rice Bran & Sunflower, 1L)",
    "brand": "Saffola",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 185,
    "score": 81.0,
    "carbon": 2.2,
    "conv_carb": 4.0,
    "water": 510,
    "lifespan": 0.75,
    "sub": [82, 82, 84, 82, 84, 76, 84],
    "explanation": "Dual-seed technology combines upcycled Rice Bran Oil (from agricultural paddy husk waste) with sunflower oil, delivering natural Oryzanol antioxidant.",
    "mats": [{"name": "Physically Refined Rice Bran Oil (Upcycled Agro Waste)", "percentage": 70, "isRecycled": False, "isRenewable": True}, {"name": "Refined Sunflower Oil", "percentage": 30, "isRecycled": False, "isRenewable": True}],
    "pack": "Recyclable HDPE bottle",
    "plastic_free": False,
    "certs": [{"id": "fssai-blended", "name": "FSSAI Blended Edible Oil Standard", "issuer": "FSSAI", "verified": True, "description": "Certified multi-source edible oil"}],
    "strengths": ["Rice bran oil upcycles agricultural rice milling byproduct husks into high-grade edible oil without clearing additional forest farmland", "LOSORB technology reduces food oil absorption by 33%"],
    "improvements": ["HDPE bottle packaging"]
  },
  {
    "id": "tata-salt-lite-low-sodium",
    "name": "Tata Salt Lite 15% Low Sodium Iodized Salt 1kg",
    "brand": "Tata Salt",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 45,
    "score": 87.0,
    "carbon": 0.3,
    "conv_carb": 0.8,
    "water": 15,
    "lifespan": 2.0,
    "sub": [88, 89, 90, 88, 88, 80, 88],
    "explanation": "Vacuum-evaporated solar salt harvested on Gujarat coast with 15% potassium chloride substitution to manage blood pressure health.",
    "mats": [{"name": "Solar Evaporated Sea Salt (NaCl)", "percentage": 83, "isRecycled": False, "isRenewable": True}, {"name": "Potassium Chloride (KCl) & Iodine", "percentage": 17, "isRecycled": False}],
    "pack": "Recyclable LDPE poly bag",
    "plastic_free": False,
    "certs": [{"id": "fssai-iodized", "name": "National Iodine Deficiency Program", "issuer": "FSSAI", "verified": True, "description": "Guaranteed 15 ppm iodine"}],
    "strengths": ["Solar evaporation utilizes clean maritime solar energy to harvest salt from Arabian Sea", "15% lower sodium protects against hypertension"],
    "improvements": ["Plastic packet wrapper"]
  },
  {
    "id": "conscious-food-desi-cow-ghee",
    "name": "Conscious Food A2 Desi Cow Bilona Cultured Ghee 500ml Glass Jar",
    "brand": "Conscious Food",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 1250,
    "score": 91.0,
    "carbon": 2.8,
    "conv_carb": 6.2,
    "water": 850,
    "lifespan": 1.0,
    "sub": [92, 94, 90, 92, 95, 85, 92],
    "explanation": "Prepared using ancient Bilona churning of A2 curd from indigenous free-grazing Gir cows in Gujarat; packed in a glass jar with zero plastic.",
    "mats": [{"name": "Pure A2 Cultured Desi Cow Milk Fat", "percentage": 75, "isRecycled": False, "isRenewable": True}, {"name": "Recyclable Glass Jar & Metal Lid", "percentage": 25, "isRecycled": True}],
    "pack": "100% recyclable glass jar with metal twist cap",
    "plastic_free": True,
    "certs": [{"id": "a2-certified", "name": "Certified A2 Beta-Casein", "issuer": "National Dairy Research Institute", "verified": True, "description": "Indigenous Indian cow genetics"}],
    "strengths": ["Indigenous Gir cows free-graze on open pastures rather than intensive factory feedlots", "100% plastic-free glass jar packaging"],
    "improvements": ["Dairy ghee has high embodied agricultural land footprints"]
  },
  {
    "id": "24-mantra-organic-jaggery-powder",
    "name": "24 Mantra Organic Jaggery Powder (Gud / Shakkar) 500g",
    "brand": "24 Mantra",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 85,
    "score": 93.5,
    "carbon": 0.5,
    "conv_carb": 1.9,
    "water": 210,
    "lifespan": 1.0,
    "sub": [94, 96, 92, 93, 94, 88, 95],
    "explanation": "Unrefined sugarcane juice clarified with natural plant extracts (ladyfinger mucilage) rather than toxic chemical sulfur dioxide.",
    "mats": [{"name": "100% Certified Organic Sugarcane Juice", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "Food-grade recyclable poly pouch",
    "plastic_free": False,
    "certs": [{"id": "jaivik-bharat", "name": "Jaivik Bharat Organic", "issuer": "FSSAI", "verified": True, "description": "100% chemical sulfur free"}],
    "strengths": ["Zero chemical bleaching or sulfur dioxide preservatives used in white refined sugar refining", "Rich in natural dietary iron and minerals"],
    "improvements": ["Sugarcane is a water-demanding crop"]
  },
  {
    "id": "catch-rock-salt-sprinkler",
    "name": "Catch Natural Pink Rock Salt Sprinkler (Sendha Namak) 200g",
    "brand": "Catch",
    "cat": "Food & Beverages",
    "subcat": "Organic Staples",
    "price": 95,
    "score": 86.0,
    "carbon": 0.4,
    "conv_carb": 1.1,
    "water": 10,
    "lifespan": 2.0,
    "sub": [87, 88, 88, 86, 88, 82, 85],
    "explanation": "Hand-mined unrefined Himalayan pink rock salt rich in 84 natural trace minerals in a refillable rotatable table sprinkler dispenser.",
    "mats": [{"name": "100% Pure Himalayan Pink Mineral Salt", "percentage": 85, "isRecycled": False, "isRenewable": True}, {"name": "Refillable Plastic Table Dispenser", "percentage": 15, "isRecycled": False}],
    "pack": "Refillable table sprinkler container",
    "plastic_free": False,
    "certs": [{"id": "fssai-clean", "name": "Natural Mineral Salt Standard", "issuer": "FSSAI", "verified": True, "description": "Unrefined mineral salt"}],
    "strengths": ["Unrefined pink salt contains 84 natural trace minerals with zero chemical anti-caking agents", "Rotatable sprinkler lid can be refilled repeatedly"],
    "improvements": ["Dispenser made from virgin plastic"]
  },

  # --- HEALTHY BREAKFAST & SNACKS (8 items) ---
  {
    "id": "yogabar-dark-chocolate-peanut-butter",
    "name": "Yoga Bar 100% Pure Roasted Peanut Butter Dark Chocolate 1kg",
    "brand": "Yoga Bar",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 499,
    "score": 90.0,
    "carbon": 1.4,
    "conv_carb": 3.8,
    "water": 320,
    "lifespan": 0.75,
    "sub": [91, 92, 90, 90, 92, 84, 90],
    "explanation": "Made with 100% slow-roasted Gujarat non-GMO peanuts with zero added palm oil, hydrogenated fats, or artificial emulsifiers.",
    "mats": [{"name": "Slow-Roasted Gujarat Peanuts", "percentage": 85, "isRecycled": False, "isRenewable": True}, {"name": "Raw Brown Sugar & Dark Cocoa", "percentage": 15, "isRecycled": False, "isRenewable": True}],
    "pack": "Recyclable wide-mouth PET jar with induction seal",
    "plastic_free": False,
    "certs": [{"id": "zero-palm-oil", "name": "100% Palm Oil Free Certified", "issuer": "Yoga Bar Lab", "verified": True, "description": "Zero rainforest destruction palm oil"}],
    "strengths": ["100% zero palm oil formulation prevents tropical deforestation for oil palm monoculture", "26g protein per 100g from local Indian peanuts"],
    "improvements": ["Wide-mouth PET jar requires local plastic recycling collection"]
  },
  {
    "id": "true-elements-rolled-oats-1kg",
    "name": "True Elements 100% Whole Rolled Oats with High Beta-Glucan Fiber 1kg",
    "brand": "True Elements",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 299,
    "score": 92.5,
    "carbon": 0.6,
    "conv_carb": 2.4,
    "water": 110,
    "lifespan": 1.0,
    "sub": [93, 95, 91, 93, 94, 86, 94],
    "explanation": "India's first certified Clean Label and 100% Whole Grain brand; minimally processed steamed and rolled jumbo oats with zero added sugar.",
    "mats": [{"name": "100% Australian Jumbo Rolled Whole Oats", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "Food-grade resealable zipper pouch with oxygen barrier",
    "plastic_free": False,
    "certs": [{"id": "clean-label-project", "name": "Clean Label Project Certified", "issuer": "Clean Label Project USA", "verified": True, "description": "Tested for heavy metals, pesticides, and plasticizers"}, {"id": "whole-grain", "name": "100% Whole Grain Stamp", "issuer": "Whole Grains Council", "verified": True, "description": "Zero refined cereal"}],
    "strengths": ["Certified by Clean Label Project for zero heavy metal contamination", "Beta-glucan soluble fiber clinically lowers LDL cholesterol"],
    "improvements": ["Zipper pouch is multi-layered"]
  },
  {
    "id": "soulfull-ragi-bites-choco-fills",
    "name": "Tata Soulfull Ragi Bites Choco Fills Whole Grain Breakfast Cereal 500g",
    "brand": "Tata Soulfull",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 235,
    "score": 90.0,
    "carbon": 0.8,
    "conv_carb": 2.8,
    "water": 95,
    "lifespan": 0.75,
    "sub": [91, 93, 89, 90, 92, 84, 92],
    "explanation": "Ancient Indian climate-resilient super millet (Ragi / Finger Millet) requires 70% less agricultural water than wheat or rice.",
    "mats": [{"name": "Finger Millet (Ragi) & Whole Grains", "percentage": 60, "isRecycled": False, "isRenewable": True}, {"name": "Chocolate Filling & Natural Cocoa", "percentage": 40, "isRecycled": False, "isRenewable": True}],
    "pack": "100% recyclable cardboard outer carton with inner moisture barrier",
    "plastic_free": False,
    "certs": [{"id": "millet-year", "name": "International Year of Millets Champion", "issuer": "UN FAO & Govt of India", "verified": True, "description": "Promotes climate-smart millets"}],
    "strengths": ["Ragi grows in drought-prone drylands with minimal groundwater and zero chemical pesticides", "Naturally high in plant calcium (3x more than dairy milk per gram)"],
    "improvements": ["Inner bag contains chocolate filling with trace vegetable oils"]
  },
  {
    "id": "slurrp-farm-millet-dosa-mix",
    "name": "Slurrp Farm Supergrains Instant Millet Dosa Mix with Spinach (150g)",
    "brand": "Slurrp Farm",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 129,
    "score": 93.0,
    "carbon": 0.4,
    "conv_carb": 1.8,
    "water": 45,
    "lifespan": 0.75,
    "sub": [94, 96, 92, 93, 94, 88, 94],
    "explanation": "Foxtail millet, ragi, and urad dal blended with real beetroot and spinach; zero refined wheat (maida), preservatives, or artificial emulsifiers.",
    "mats": [{"name": "Climate-Resilient Millets (Ragi, Foxtail, Jowar)", "percentage": 70, "isRecycled": False, "isRenewable": True}, {"name": "Urad Dal & Freeze-Dried Spinach Powder", "percentage": 30, "isRecycled": False, "isRenewable": True}],
    "pack": "100% recyclable paperboard carton",
    "plastic_free": False,
    "certs": [{"id": "clean-grains", "name": "Zero Maida & Zero Trans-Fat", "issuer": "FSSAI", "verified": True, "description": "100% wholesome ancient grains"}],
    "strengths": ["Promotes traditional Indian millets that regenerate dryland farming soils", "Zero chemical raising agents; pure wholesome breakfast in 5 minutes"],
    "improvements": ["Inner plastic pouch"]
  },
  {
    "id": "happilo-california-almonds-500g",
    "name": "Happilo Premium California Whole Dried Almonds 500g Zip Pouch",
    "brand": "Happilo",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 449,
    "score": 86.5,
    "carbon": 0.9,
    "conv_carb": 2.8,
    "water": 380,
    "lifespan": 0.75,
    "sub": [87, 88, 88, 86, 88, 80, 88],
    "explanation": "100% raw unpolished whole almonds packed in a nitrogen-flushed resealable zip lock pouch to retain natural Vitamin E crunch.",
    "mats": [{"name": "100% Raw Whole California Almonds", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "Resealable barrier zip pouch",
    "plastic_free": False,
    "certs": [{"id": "non-gmo", "name": "Non-GMO Verified", "issuer": "Almond Board of California", "verified": True, "description": "Natural whole nuts"}],
    "strengths": ["Healthy unsaturated fats and plant-based protein snack replaces single-use fried potato chips", "Resealable pouch keeps nuts crunchy without refrigerator power"],
    "improvements": ["Almond agriculture requires managed bee pollination and significant orchard irrigation"]
  },
  {
    "id": "epigamia-greek-yogurt-natural",
    "name": "Epigamia Greek Yogurt Natural Unsweetened High Protein 90g Cup",
    "brand": "Epigamia",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 50,
    "score": 82.0,
    "carbon": 0.35,
    "conv_carb": 1.0,
    "water": 95,
    "lifespan": 0.1,
    "sub": [83, 84, 82, 82, 84, 76, 84],
    "explanation": "Traditionally strained to remove excess whey, concentrating natural dairy protein to 8g per cup with zero added sugar or gelatin.",
    "mats": [{"name": "Pasteurized Toned Milk & Live Probiotic Cultures", "percentage": 92, "isRecycled": False, "isRenewable": True}, {"name": "Recyclable Polypropylene (#5 PP) Cup", "percentage": 8, "isRecycled": True}],
    "pack": "Recyclable #5 PP plastic cup with peelable foil lid",
    "plastic_free": False,
    "certs": [{"id": "fssai-probiotic", "name": "Live Probiotics Verified", "issuer": "FSSAI", "verified": True, "description": "Active gut microflora"}],
    "strengths": ["Live active gut flora cultures support healthy microbiome and digestion", "High protein concentration provides natural satiety"],
    "improvements": ["Single-serve plastic cup format generates container waste per 90g serving"]
  },
  {
    "id": "pintola-all-natural-peanut-butter",
    "name": "Pintola All-Natural Creamy Peanut Butter (100% Peanuts Only, 1kg)",
    "brand": "Pintola",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 425,
    "score": 92.0,
    "carbon": 1.2,
    "conv_carb": 3.6,
    "water": 290,
    "lifespan": 0.75,
    "sub": [93, 95, 91, 92, 92, 86, 92],
    "explanation": "Single ingredient: 100% slow-roasted Gujarat runner peanuts; zero added sugar, zero salt, zero hydrogenated oils.",
    "mats": [{"name": "100% Roasted Runner Peanuts", "percentage": 100, "isRecycled": False, "isRenewable": True}],
    "pack": "100% recyclable food-grade PET jar",
    "plastic_free": False,
    "certs": [{"id": "usda-organic-grade", "name": "Zero Palm Oil & Zero Trans Fat", "issuer": "FSSAI", "verified": True, "description": "100% single ingredient pure spread"}],
    "strengths": ["Zero added oils, sugars, or preservatives of any kind", "Local Saurashtra peanut sourcing supports Gujarat agriculture"],
    "improvements": ["Natural oil separation occurs requiring manual stirring"]
  },
  {
    "id": "kelloggs-muesli-fruit-nut-750g",
    "name": "Kellogg's Muesli with 21% Fruit, Nut & Seeds 750g Box",
    "brand": "Kellogg's",
    "cat": "Food & Beverages",
    "subcat": "Healthy Snacks",
    "price": 420,
    "score": 83.5,
    "carbon": 1.4,
    "conv_carb": 3.2,
    "water": 190,
    "lifespan": 0.75,
    "sub": [84, 85, 84, 83, 86, 78, 86],
    "explanation": "Blend of 5 nutritious multigrains (Wheat, Oats, Corn, Rice, and Barley) with dried fruits and nuts.",
    "mats": [{"name": "5 Grain Multigrain Flakes (Oats, Wheat, Corn, Barley)", "percentage": 75, "isRecycled": False, "isRenewable": True}, {"name": "Dried Papaya, Raisins, Almonds & Pumpkin Seeds", "percentage": 25, "isRecycled": False, "isRenewable": True}],
    "pack": "100% recyclable cardboard outer box with inner foil liner",
    "plastic_free": False,
    "certs": [{"id": "fssai-clean", "name": "FSSAI Multigrain Standard", "issuer": "FSSAI", "verified": True, "description": "Nutritional cereal standard"}],
    "strengths": ["Diverse 5-grain cereal intake supports balanced dietary fiber", "Cardboard outer box made from 100% recycled paper fibers"],
    "improvements": ["Inner plastic barrier pouch"]
  }
]
