# Home & Kitchen Catalog Data (55+ products)
# Indian Market Appliances, Cookware, Drinkware & Storage

home_kitchen_items = [
  # --- LARGE APPLIANCES & REFRIGERATORS (10 items) ---
  {
    "id": "lg-242l-3star-smart-inverter-fridge",
    "name": "LG 242L 3-Star Smart Inverter Frost Free Double Door Refrigerator (Shiny Steel)",
    "brand": "LG",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 25990,
    "score": 83.5,
    "carbon": 340.0,
    "conv_carb": 580.0,
    "water": 4200,
    "lifespan": 12.0,
    "sub": [82, 85, 94, 84, 88, 86, 88],
    "explanation": "Smart Inverter Compressor saves 36% electrical power with eco-friendly R600a zero-ODP natural refrigerant.",
    "mats": [{"name": "Galvanized Steel Sheet", "percentage": 55, "isRecycled": True}, {"name": "Cyclopentane High-density Insulation", "percentage": 25, "isRecycled": False}, {"name": "Copper & Aluminium Heat Exchangers", "percentage": 15, "isRecycled": True}, {"name": "Tempered Glass Shelves", "percentage": 5, "isRecycled": False}],
    "pack": "Heavy-duty corrugated paper carton with minimal EPS corner protectors",
    "plastic_free": False,
    "certs": [{"id": "bee-3star", "name": "BEE 3-Star Energy Rating", "issuer": "Bureau of Energy Efficiency India", "verified": True, "description": "National energy conservation efficiency rating"}, {"id": "iso-14001", "name": "ISO 14001 Environmental Standard", "issuer": "TÜV Rheinland", "verified": True, "description": "Eco manufacturing process"}],
    "strengths": ["R600a hydrocarbon refrigerant has zero Ozone Depletion Potential", "10-year compressor warranty ensures extended operational life", "Auto Smart Connect runs smoothly on home solar/inverter systems"],
    "improvements": ["Crisper drawer uses non-recycled polystyrene polymer"]
  },
  {
    "id": "samsung-253l-3star-curd-maestro-fridge",
    "name": "Samsung 253L 3-Star Inverter Double Door Fridge with Curd Maestro (Refined Inox)",
    "brand": "Samsung",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 27990,
    "score": 83.0,
    "carbon": 350.0,
    "conv_carb": 590.0,
    "water": 4350,
    "lifespan": 12.0,
    "sub": [81, 84, 93, 83, 88, 84, 88],
    "explanation": "Digital Inverter Technology adjusts 7 compressor speeds automatically; built-in fermentation curd maker eliminates single-use plastic dahi tubs.",
    "mats": [{"name": "High-tensile Coated Steel", "percentage": 54, "isRecycled": True}, {"name": "Eco Thermal Insulation Foam", "percentage": 26, "isRecycled": False}, {"name": "Toughened Glass Shelves", "percentage": 10, "isRecycled": False}, {"name": "Copper Tubing", "percentage": 10, "isRecycled": True}],
    "pack": "Recyclable cardboard carton",
    "plastic_free": False,
    "certs": [{"id": "bee-3star", "name": "BEE 3-Star Certified", "issuer": "BEE India", "verified": True, "description": "Energy rating"}],
    "strengths": ["Curd Maestro function eliminates hundreds of plastic retail curd containers annually", "Solar panel compatible operation"],
    "improvements": ["Door gasket magnetic seal requires maintenance every 5 years"]
  },
  {
    "id": "whirlpool-265l-intellifresh-fridge",
    "name": "Whirlpool 265L 3-Star IntelliFresh Inverter Double Door Refrigerator (German Steel)",
    "brand": "Whirlpool",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 28490,
    "score": 82.0,
    "carbon": 365.0,
    "conv_carb": 600.0,
    "water": 4500,
    "lifespan": 11.5,
    "sub": [80, 83, 92, 82, 86, 82, 86],
    "explanation": "Microprocessor-guided adaptive intelligence sensors adapt cooling based on internal load and door usage.",
    "mats": [{"name": "Steel Outer Body", "percentage": 56, "isRecycled": True}, {"name": "Thermal Polyurethane Insulation", "percentage": 24, "isRecycled": False}, {"name": "Copper & Brass", "percentage": 12, "isRecycled": True}, {"name": "Glass", "percentage": 8, "isRecycled": False}],
    "pack": "Heavy corrugated box",
    "plastic_free": False,
    "certs": [{"id": "bee-3star", "name": "BEE 3-Star", "issuer": "BEE", "verified": True, "description": "Energy efficiency"}],
    "strengths": ["Zeolite technology in vegetable crisper absorbs ethylene gas, extending produce shelf life by up to 15 days to reduce domestic food waste", "R600a eco gas"],
    "improvements": ["Ice twister assembly uses brittle ABS plastic"]
  },
  {
    "id": "godrej-eon-244l-inverter-fridge",
    "name": "Godrej Eon 244L 3-Star Nano Shield Inverter Frost Free Fridge (Fossil Steel)",
    "brand": "Godrej",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 24490,
    "score": 86.0,
    "carbon": 310.0,
    "conv_carb": 570.0,
    "water": 3950,
    "lifespan": 13.0,
    "sub": [86, 88, 94, 86, 90, 88, 92],
    "explanation": "First Indian brand with 100% Green Inverter Technology and zero CFC/HCFC/HFC emissions since 2001.",
    "mats": [{"name": "Recycled Indian Steel", "percentage": 58, "isRecycled": True}, {"name": "Green Polyurethane Foam", "percentage": 22, "isRecycled": False}, {"name": "Copper Coils", "percentage": 14, "isRecycled": True}, {"name": "Glass Trays", "percentage": 6, "isRecycled": False}],
    "pack": "Recycled cardboard container",
    "plastic_free": False,
    "certs": [{"id": "cii-greenpro", "name": "CII GreenPro Certified Ecolabel", "issuer": "Confederation of Indian Industry", "verified": True, "description": "Highest holistic Indian environmental product rating"}, {"id": "bee-3star", "name": "BEE 3-Star", "issuer": "BEE", "verified": True, "description": "Standard energy efficiency"}],
    "strengths": ["GreenPro certified ecolabel for sustainable Indian manufacturing", "Nano Shield disinfection technology kills 95% of food surface microbes without chemical treatments", "Thickest PUF insulation in category"],
    "improvements": ["Handle design is integrated rather than modularly replaceable"]
  },
  {
    "id": "haier-325l-bottom-mount-fridge",
    "name": "Haier 325L 3-Star Bottom Mounted Triple Inverter Refrigerator (Dazzle Steel)",
    "brand": "Haier",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 34990,
    "score": 84.0,
    "carbon": 380.0,
    "conv_carb": 620.0,
    "water": 4600,
    "lifespan": 12.5,
    "sub": [83, 85, 93, 84, 88, 85, 88],
    "explanation": "Bottom-mounted freezer cuts bending by 90% and reduces cold air loss by placing frequently accessed fresh compartment on top.",
    "mats": [{"name": "Powder-coated Steel", "percentage": 56, "isRecycled": True}, {"name": "Eco PUF Insulation", "percentage": 24, "isRecycled": False}, {"name": "Copper Cooling", "percentage": 12, "isRecycled": True}, {"name": "Glass", "percentage": 8, "isRecycled": False}],
    "pack": "Cardboard carton",
    "plastic_free": False,
    "certs": [{"id": "bee-3star", "name": "BEE 3-Star", "issuer": "BEE", "verified": True, "description": "Energy rating"}],
    "strengths": ["Triple Inverter fan and compressor synchronizes RPM to thermal load", "1 Hour Icing Technology uses quick cooling bursts efficiently"],
    "improvements": ["Larger overall volume requires wider kitchen clearance"]
  },
  {
    "id": "ifb-senator-smart-8kg-front-load",
    "name": "IFB Senator Smart Touch 8kg 5-Star Front Load Washing Machine (Silver)",
    "brand": "IFB",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 39990,
    "score": 88.5,
    "carbon": 290.0,
    "conv_carb": 560.0,
    "water": 2900,
    "lifespan": 14.0,
    "sub": [88, 89, 96, 88, 90, 92, 92],
    "explanation": "EcoInverter motor with Aqua Energie filter dissolves detergent efficiently, cutting water use to 42 liters per load.",
    "mats": [{"name": "Stainless Steel Crescent Drum", "percentage": 42, "isRecycled": True}, {"name": "Cast Iron Counterweight", "percentage": 28, "isRecycled": True}, {"name": "Recycled Polymer Outer Tub", "percentage": 18, "isRecycled": True}, {"name": "Copper Inverter Motor", "percentage": 12, "isRecycled": True}],
    "pack": "Heavy corrugated recyclable box",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star Highest Rating", "issuer": "BEE India", "verified": True, "description": "Maximum water and electricity conservation tier"}, {"id": "iso-14001", "name": "ISO 14001 Certified Factory", "issuer": "TÜV", "verified": True, "description": "Zero industrial effluent discharge"}],
    "strengths": ["Aqua Energie softens hard ground water commonly found in Indian cities", "Crescent Moon drum pattern reduces garment fiber shredding and microplastic release", "10-year motor warranty with 10-year genuine spare parts commitment"],
    "improvements": ["High machine weight of 75kg requires two technicians for home moving"]
  },
  {
    "id": "bosch-7kg-5star-front-load-waj2416sin",
    "name": "Bosch 7kg 5-Star Inverter Touch Front Load Washing Machine (Silver)",
    "brand": "Bosch",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 31990,
    "score": 88.0,
    "carbon": 285.0,
    "conv_carb": 550.0,
    "water": 2850,
    "lifespan": 13.5,
    "sub": [87, 88, 96, 88, 90, 91, 92],
    "explanation": "EcoSilence Drive brushless motor with ActiveWater Plus pressure sensors measures exact fabric weight to dispense minimal water.",
    "mats": [{"name": "VarioDrum Stainless Steel", "percentage": 40, "isRecycled": True}, {"name": "Cast Counterweight", "percentage": 30, "isRecycled": True}, {"name": "Recycled Tub Polymer", "percentage": 18, "isRecycled": True}, {"name": "Brushless Motor & Copper", "percentage": 12, "isRecycled": True}],
    "pack": "Cardboard carton with recyclable pallet base",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star", "issuer": "BEE", "verified": True, "description": "Highest efficiency"}, {"id": "ecoperfect", "name": "Bosch EcoPerfect Standard", "issuer": "Bosch Home", "verified": True, "description": "Reduces electricity consumption by 50%"}],
    "strengths": ["ActiveWater Plus precisely calculates water down to 256 load increments", "AntiVibration side walls stabilize spin vibrations", "10-year motor warranty"],
    "improvements": ["Heater cycle consumes significant energy if 60°C wash is selected frequently"]
  },
  {
    "id": "lg-7kg-5star-inverter-front-load",
    "name": "LG 7kg 5-Star AI Direct Drive Front Load Washer with Steam (Middle Black)",
    "brand": "LG",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 34990,
    "score": 87.5,
    "carbon": 295.0,
    "conv_carb": 555.0,
    "water": 2950,
    "lifespan": 13.0,
    "sub": [87, 87, 95, 87, 90, 90, 92],
    "explanation": "AI Direct Drive motor connects directly to drum with zero belt or pulley wear, analyzing fabric softness to tailor motions.",
    "mats": [{"name": "Stainless Steel Drum & Lifters", "percentage": 42, "isRecycled": True}, {"name": "Direct Drive Motor", "percentage": 18, "isRecycled": True}, {"name": "Cast Counterweights", "percentage": 25, "isRecycled": True}, {"name": "Housing & Electronics", "percentage": 15, "isRecycled": False}],
    "pack": "Heavy corrugated carton",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star", "issuer": "BEE", "verified": True, "description": "Efficiency rating"}],
    "strengths": ["Zero belt drive reduces friction wear failures", "Steam wash eliminates 99.9% of dust mite allergens without chemical additives"],
    "improvements": ["Control touch panel requires genuine replacement module if cracked"]
  },
  {
    "id": "samsung-7kg-5star-ecobubble-washer",
    "name": "Samsung 7kg 5-Star EcoBubble Front Load Washer with AI Control (Inox Grey)",
    "brand": "Samsung",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 32990,
    "score": 87.0,
    "carbon": 300.0,
    "conv_carb": 560.0,
    "water": 3050,
    "lifespan": 13.0,
    "sub": [86, 87, 95, 86, 90, 89, 92],
    "explanation": "EcoBubble generates foam bubbles that penetrate fabric 40x faster in cold water, saving up to 70% water heater energy.",
    "mats": [{"name": "Stainless Steel Diamond Drum", "percentage": 40, "isRecycled": True}, {"name": "Digital Inverter Motor", "percentage": 16, "isRecycled": True}, {"name": "Counterweights", "percentage": 28, "isRecycled": True}, {"name": "Plastic Fascia", "percentage": 16, "isRecycled": False}],
    "pack": "Recyclable carton",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star", "issuer": "BEE", "verified": True, "description": "Top energy tier"}],
    "strengths": ["Cold water EcoBubble wash avoids 70% heating electricity", "20-year digital inverter warranty"],
    "improvements": ["Requires stable water inlet pressure above 50 kPa"]
  },
  {
    "id": "whirlpool-7-5kg-bloomwash-pro",
    "name": "Whirlpool 7.5kg 5-Star BloomWash Pro Top Load Washing Machine (Graphite)",
    "brand": "Whirlpool",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 23490,
    "score": 81.5,
    "carbon": 260.0,
    "conv_carb": 440.0,
    "water": 4100,
    "lifespan": 10.5,
    "sub": [80, 82, 89, 81, 85, 84, 88],
    "explanation": "Built-in heater with Hexa Bloom Impeller creates 360-degree bloom wash motion; 5-star energy rating.",
    "mats": [{"name": "Stainless Steel Tub", "percentage": 35, "isRecycled": True}, {"name": "Galvanized Steel Cabinet", "percentage": 40, "isRecycled": True}, {"name": "Polypropylene Impeller", "percentage": 15, "isRecycled": False}, {"name": "Motor & PCB", "percentage": 10, "isRecycled": False}],
    "pack": "Cardboard box",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star", "issuer": "BEE", "verified": True, "description": "Top efficiency tier"}],
    "strengths": ["BEE 5-Star certified electricity efficiency in top load class", "Soft close hydraulic glass lid prevents impact cracks"],
    "improvements": ["Top load format naturally uses more water per cycle than front load designs"]
  },

  # --- AIR CONDITIONERS & BLDC SMART FANS (9 items) ---
  {
    "id": "voltas-1-5ton-5star-inverter-split-ac",
    "name": "Voltas 1.5 Ton 5-Star Inverter Split AC (185V Vectra Elegant, 100% Copper)",
    "brand": "Voltas",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 38490,
    "score": 85.0,
    "carbon": 420.0,
    "conv_carb": 740.0,
    "water": 4800,
    "lifespan": 10.0,
    "sub": [84, 85, 93, 85, 88, 86, 90],
    "explanation": "High ISEER 5.0 rating with 100% copper condenser tubes and eco-friendly R32 refrigerant with low GWP of 675.",
    "mats": [{"name": "100% Copper Heat Exchangers & Tubes", "percentage": 42, "isRecycled": True}, {"name": "Galvanized Outdoor Sheet Metal", "percentage": 35, "isRecycled": True}, {"name": "Inverter Rotary Compressor", "percentage": 15, "isRecycled": True}, {"name": "Indoor ABS Casing", "percentage": 8, "isRecycled": False}],
    "pack": "Corrugated cardboard cartons for indoor and outdoor units",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star Energy Label", "issuer": "BEE India", "verified": True, "description": "Highest annual energy saving tier (ISEER 5.0)"}, {"id": "rohs", "name": "RoHS Compliant", "issuer": "TATA Sons Quality", "verified": True, "description": "Heavy metals free"}],
    "strengths": ["100% copper coils extend thermal efficiency and withstand coastal saline corrosion", "R32 refrigerant has 68% lower Global Warming Potential than older R410A", "Operates even at 52°C extreme ambient heat"],
    "improvements": ["Air filters require bi-weekly manual cleaning to maintain optimal COP efficiency"]
  },
  {
    "id": "daikin-1-5ton-5star-inverter-ac-ftkm50u",
    "name": "Daikin 1.5 Ton 5-Star Inverter Split AC with PM2.5 Filter (FTKM50U)",
    "brand": "Daikin",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 45490,
    "score": 87.5,
    "carbon": 390.0,
    "conv_carb": 730.0,
    "water": 4600,
    "lifespan": 12.0,
    "sub": [87, 88, 95, 87, 90, 89, 92],
    "explanation": "Industry-leading ISEER 5.2 rating with Daikin patented Neo Swing Inverter compressor that eliminates refrigerant gas leakage friction.",
    "mats": [{"name": "100% Grooved Copper Tubes", "percentage": 44, "isRecycled": True}, {"name": "Anti-Corrosion Outdoor Casing", "percentage": 34, "isRecycled": True}, {"name": "Swing Inverter Compressor", "percentage": 14, "isRecycled": True}, {"name": "Indoor High-grade Casing", "percentage": 8, "isRecycled": False}],
    "pack": "Recyclable industrial carton packaging",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star ISEER 5.2", "issuer": "BEE India", "verified": True, "description": "Exceptional efficiency"}, {"id": "green-ac", "name": "Zero ODP R32 Pioneer", "issuer": "Daikin Global", "verified": True, "description": "Original developer of R32"}],
    "strengths": ["Highest energy efficiency ISEER 5.2 in 1.5-ton segment saves hundreds of units of grid coal power", "Neo Swing compressor eliminates internal friction wear", "Self-clean dew clean technology"],
    "improvements": ["Higher initial purchase price compared to domestic entry models"]
  },
  {
    "id": "panasonic-1-5ton-5star-wifi-inverter-ac",
    "name": "Panasonic 1.5 Ton 5-Star Wi-Fi Inverter AC with nanoe-X (CS/CU-NU18YKY5W)",
    "brand": "Panasonic",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 44990,
    "score": 86.5,
    "carbon": 405.0,
    "conv_carb": 735.0,
    "water": 4700,
    "lifespan": 11.0,
    "sub": [86, 86, 94, 86, 89, 88, 92],
    "explanation": "nanoe-X hydroxyl radicals inhibit 99.9% of indoor air pollutants and bacteria, functioning as an integrated standalone air purifier.",
    "mats": [{"name": "Copper Condenser & Evaporator", "percentage": 43, "isRecycled": True}, {"name": "Eco-Tough Outdoor Casing", "percentage": 35, "isRecycled": True}, {"name": "Compressor & PCB", "percentage": 14, "isRecycled": True}, {"name": "Indoor Unit", "percentage": 8, "isRecycled": False}],
    "pack": "Cardboard packaging",
    "plastic_free": False,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star", "issuer": "BEE", "verified": True, "description": "Energy standard"}, {"id": "nanoe-x", "name": "Texcell Air Purification Verified", "issuer": "Texcell France", "verified": True, "description": "Inactivates 99.9% pollutants"}],
    "strengths": ["nanoe-X technology neutralizes airborne mold and viruses without disposable filter waste", "AI MirAI app monitors daily electricity consumption trends in rupees"],
    "improvements": ["Requires active Wi-Fi connection for intelligent scheduling automation"]
  },
  {
    "id": "atomberg-renesa-1200mm-bldc-fan",
    "name": "Atomberg Renesa 1200mm BLDC Smart Motor Ceiling Fan with Remote (Midnight Black)",
    "brand": "Atomberg",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 3699,
    "score": 93.0,
    "carbon": 34.0,
    "conv_carb": 125.0,
    "water": 480,
    "lifespan": 12.0,
    "sub": [94, 92, 96, 90, 92, 92, 94],
    "explanation": "Consumes only 28 Watts at top speed (compared to 75 Watts for induction fans), saving up to ₹1,500 every single year per fan.",
    "mats": [{"name": "100% Aluminium Blades", "percentage": 45, "isRecycled": True}, {"name": "BLDC Permanent Magnet Motor (Copper & Neodymium)", "percentage": 35, "isRecycled": True}, {"name": "Smart Inverter Driver PCB", "percentage": 12, "isRecycled": False}, {"name": "Aluminium Canopy & Downrod", "percentage": 8, "isRecycled": True}],
    "pack": "Compact 100% recyclable cardboard box with cardboard inserts (zero Styrofoam)",
    "plastic_free": True,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star Energy Certified (28W)", "issuer": "BEE India", "verified": True, "description": "Exceeds highest ceiling fan standard"}, {"id": "bis-isi", "name": "BIS IS 374 ISI Certified", "issuer": "Bureau of Indian Standards", "verified": True, "description": "Electric ceiling fan standard"}],
    "strengths": ["Consumes only 28W at speed 5 compared to standard 75-80W fans, cutting electricity consumption by 65%", "Runs 3 times longer on home inverter battery during power cuts", "Zero motor humming noise and negligible heat dissipation"],
    "improvements": ["Remote control requires 2x AAA batteries (rechargeable recommended)"]
  },
  {
    "id": "havells-stealth-air-1200mm-bldc-fan",
    "name": "Havells Stealth Air 1200mm BLDC Motor Smart Ceiling Fan (Pearl White)",
    "brand": "Havells",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 5499,
    "score": 91.5,
    "carbon": 38.0,
    "conv_carb": 128.0,
    "water": 510,
    "lifespan": 11.5,
    "sub": [92, 91, 95, 89, 90, 90, 94],
    "explanation": "Aerodynamic composite blades with BLDC motor consumes 32W with ultra-silent 240 m³/min air delivery.",
    "mats": [{"name": "Engineered Composite Blades", "percentage": 42, "isRecycled": False}, {"name": "BLDC Motor & Copper Coils", "percentage": 38, "isRecycled": True}, {"name": "Aluminium Housing & Steel Downrod", "percentage": 20, "isRecycled": True}],
    "pack": "Recyclable cardboard box",
    "plastic_free": True,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star BLDC", "issuer": "BEE", "verified": True, "description": "Top efficiency tier"}, {"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS", "verified": True, "description": "Safety standard"}],
    "strengths": ["Whisper-quiet aerodynamic blade profile minimizes turbulent air drag", "Saves over ₹1,300 on electricity bills annually"],
    "improvements": ["Composite blades cannot be bent back into shape if mishandled"]
  },
  {
    "id": "crompton-energion-hyperjet-bldc-fan",
    "name": "Crompton Energion Hyperjet 1200mm BLDC Motor Ceiling Fan (BEE 5-Star, Brown)",
    "brand": "Crompton",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 3199,
    "score": 92.5,
    "carbon": 35.0,
    "conv_carb": 125.0,
    "water": 490,
    "lifespan": 11.0,
    "sub": [93, 91, 95, 90, 91, 91, 94],
    "explanation": "ActivBLDC technology uses 35W with wide operating voltage from 90V to 300V, engineered for erratic Indian grid voltages.",
    "mats": [{"name": "Aluminium Blades", "percentage": 44, "isRecycled": True}, {"name": "ActivBLDC Motor", "percentage": 36, "isRecycled": True}, {"name": "Steel Hardware", "percentage": 20, "isRecycled": True}],
    "pack": "Cardboard box packaging",
    "plastic_free": True,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star Rating", "issuer": "BEE", "verified": True, "description": "Maximum energy efficiency"}, {"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "National approval"}],
    "strengths": ["ActivBLDC motor handles Indian voltage fluctuations down to 90V smoothly", "RF remote controls fan from any room angle"],
    "improvements": ["Canopy plastic shroud is thin"]
  },
  {
    "id": "orient-electric-i-float-bldc-fan",
    "name": "Orient Electric I-Float 1200mm IoT Smart BLDC Fan with Inverter Motor (White)",
    "brand": "Orient Electric",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 4999,
    "score": 91.0,
    "carbon": 36.0,
    "conv_carb": 126.0,
    "water": 500,
    "lifespan": 11.0,
    "sub": [92, 90, 94, 89, 90, 90, 94],
    "explanation": "Smart IoT BLDC ceiling fan consumes 32W with voice control integration (Alexa / Google Assistant).",
    "mats": [{"name": "Aluminium Alloy Blades", "percentage": 46, "isRecycled": True}, {"name": "Inverter BLDC Motor", "percentage": 34, "isRecycled": True}, {"name": "Wi-Fi Module & Hardware", "percentage": 20, "isRecycled": False}],
    "pack": "Recyclable cardboard box",
    "plastic_free": True,
    "certs": [{"id": "bee-5star", "name": "BEE 5-Star", "issuer": "BEE", "verified": True, "description": "Highest rating"}],
    "strengths": ["Automated timer schedules fan shutdown during night hours to prevent wasted power", "5-year warranty on motor"],
    "improvements": ["Requires smartphone setup for Wi-Fi features"]
  },
  {
    "id": "philips-ac1215-air-purifier",
    "name": "Philips AC1215/20 Air Purifier with NanoProtect True HEPA (Series 1000, White)",
    "brand": "Philips",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 9999,
    "score": 84.0,
    "carbon": 42.0,
    "conv_carb": 78.0,
    "water": 680,
    "lifespan": 8.0,
    "sub": [83, 84, 91, 84, 88, 86, 88],
    "explanation": "NanoProtect HEPA captures 99.97% of PM2.5 particulates down to 0.003 microns, operating on just 50W max draw.",
    "mats": [{"name": "Post-Consumer ABS Plastic Casing", "percentage": 50, "isRecycled": True}, {"name": "NanoProtect HEPA Fiber Media", "percentage": 20, "isRecycled": False}, {"name": "Activated Carbon Pellets", "percentage": 15, "isRecycled": False, "isRenewable": True}, {"name": "Electric Motor & Fan", "percentage": 15, "isRecycled": True}],
    "pack": "100% recyclable cardboard box with paper pulp molded buffers",
    "plastic_free": True,
    "certs": [{"id": "ecarf", "name": "ECARF Allergy-Friendly Certified", "issuer": "European Centre for Allergy Research", "verified": True, "description": "Clinically tested for allergy relief"}, {"id": "energy-star", "name": "ENERGY STAR Certified", "issuer": "EPA", "verified": True, "description": "Energy efficiency"}],
    "strengths": ["Removes toxic smog and winter PM2.5 in Indian cities cleanly with zero ozone emissions", "Silent sleep mode uses only 11W of electricity"],
    "improvements": ["Replacement HEPA filter cartridges are non-washable and require yearly disposal"]
  },
  {
    "id": "mi-smart-air-purifier-4",
    "name": "Mi Smart Air Purifier 4 with True HEPA and Negative Air Ionization (White)",
    "brand": "Xiaomi",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 14999,
    "score": 83.5,
    "carbon": 48.0,
    "conv_carb": 82.0,
    "water": 740,
    "lifespan": 7.5,
    "sub": [82, 83, 90, 83, 88, 85, 88],
    "explanation": "High-efficiency 3-in-1 cylindrical filter with 400 m³/h CADR and OLED touch screen real-time AQI monitor.",
    "mats": [{"name": "ABS Body Shell", "percentage": 52, "isRecycled": False}, {"name": "High-density Filter Cartridge", "percentage": 25, "isRecycled": False}, {"name": "Centrifugal Fan Motor", "percentage": 23, "isRecycled": True}],
    "pack": "Recyclable cardboard box",
    "plastic_free": False,
    "certs": [{"id": "tuv-rheinland", "name": "TÜV Rheinland Allergy Care", "issuer": "TÜV", "verified": True, "description": "Allergen reduction certified"}],
    "strengths": ["Automated laser particle sensor ramps up speed only when pollution spikes, saving 40% electricity", "OLED display"],
    "improvements": ["Filter barrel contains RFID chip which prevents third-party refill use"]
  },

  # --- COOKWARE & STAINLESS STEEL PRESSURE COOKERS (18 items) ---
  {
    "id": "prestige-deluxe-alpha-svachh-3l",
    "name": "Prestige Deluxe Alpha Svachh 3L Stainless Steel Pressure Cooker",
    "brand": "Prestige",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 2850,
    "score": 93.5,
    "carbon": 14.5,
    "conv_carb": 42.0,
    "water": 380,
    "lifespan": 25.0,
    "sub": [94, 94, 98, 95, 92, 96, 92],
    "explanation": "Food-grade AISI 304 stainless steel with unique Alpha induction bottom; designed to last over 25 years with modular replaceable gaskets and safety valves.",
    "mats": [{"name": "Food Grade AISI 304 Stainless Steel", "percentage": 78, "isRecycled": True}, {"name": "Aluminium Core Thermal Base (Impact Bonded)", "percentage": 14, "isRecycled": True}, {"name": "Phenolic Bakelite Handle", "percentage": 6, "isRecycled": False}, {"name": "Food-grade Silicone Gasket", "percentage": 2, "isRecycled": False}],
    "pack": "100% recyclable cardboard box with printed kraft inserts",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified (IS 2347)", "issuer": "Bureau of Indian Standards", "verified": True, "description": "Rigorous pressure vessel safety standard"}, {"id": "food-grade", "name": "AISI 304 Food Contact Safe", "issuer": "NABL Accredited Lab", "verified": True, "description": "Heavy metal and nickel leaching safe"}],
    "strengths": ["Spillage control Svachh lid prevents starchy liquid boil-over, keeping cooktop clean", "Multi-decade lifespan reduces single-use cookware turnover", "All components (valves, gaskets, handles) available as cheap spare parts"],
    "improvements": ["Heavier than thin anodised aluminium alternatives"]
  },
  {
    "id": "hawkins-contura-hard-anodised-3l",
    "name": "Hawkins Contura Hard Anodised Pressure Cooker 3L (Black)",
    "brand": "Hawkins",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 2175,
    "score": 90.0,
    "carbon": 16.0,
    "conv_carb": 45.0,
    "water": 420,
    "lifespan": 20.0,
    "sub": [90, 89, 96, 91, 90, 95, 92],
    "explanation": "Hard anodised 60-micron surface is non-reactive with acidic foods and will not pit or tarnish over decades of Indian cooking.",
    "mats": [{"name": "Virgin Virgin Hard Anodised Aluminium", "percentage": 85, "isRecycled": False}, {"name": "Stainless Steel Inner Lid", "percentage": 8, "isRecycled": True}, {"name": "Stay-cool Bakelite Handles", "percentage": 5, "isRecycled": False}, {"name": "Rubber Gasket", "percentage": 2, "isRecycled": False}],
    "pack": "Corrugated carton box with paper wrap",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified (IS 2347)", "issuer": "BIS India", "verified": True, "description": "Safety compliance"}, {"id": "ul", "name": "UL Listed", "issuer": "Underwriters Laboratories", "verified": True, "description": "International safety approval"}],
    "strengths": ["Inside-fitting safety lid cannot be forced open while pressure exists inside", "Curved rounded body facilitates easy stirring of dal and curries", "Spare parts sold across every local Indian market"],
    "improvements": ["Hard anodised base is not compatible with induction cooktops"]
  },
  {
    "id": "stahl-artisan-triply-kadai-24cm",
    "name": "Stahl Artisan Triply Stainless Steel Kadai with Lid 24cm (2.5L)",
    "brand": "Stahl",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 3195,
    "score": 94.0,
    "carbon": 12.0,
    "conv_carb": 38.0,
    "water": 320,
    "lifespan": 30.0,
    "sub": [95, 95, 99, 96, 92, 98, 92],
    "explanation": "Triply construction (SS304 interior + aluminium thermal core + magnetic SS430 exterior) distributes heat evenly, eliminating toxic PTFE/PFOA non-stick coatings forever.",
    "mats": [{"name": "AISI 304 Food Grade Stainless Steel Inner", "percentage": 50, "isRecycled": True}, {"name": "Thermal Aluminium Core", "percentage": 25, "isRecycled": True}, {"name": "Magnetic Stainless Steel Outer", "percentage": 25, "isRecycled": True}],
    "pack": "100% plastic-free recycled paper gift box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS", "verified": True, "description": "National cookware standard"}, {"id": "ptfe-free", "name": "100% PTFE & PFOA Free", "issuer": "Eurofins", "verified": True, "description": "Zero chemical coating release"}],
    "strengths": ["Eliminates peeling chemical non-stick pans that get thrown away every 2 years", "Lifetime warranty against manufacturing defects", "Compatible with gas, induction, halogen, and oven"],
    "improvements": ["Requires proper pre-heating (Leidenfrost water droplet test) to achieve natural non-stick characteristics"]
  },
  {
    "id": "vinod-platinum-triply-saucepan-16cm",
    "name": "Vinod Platinum Triply Stainless Steel Saucepan with Glass Lid 1.5L",
    "brand": "Vinod",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 1750,
    "score": 92.0,
    "carbon": 9.5,
    "conv_carb": 28.0,
    "water": 260,
    "lifespan": 25.0,
    "sub": [93, 93, 98, 94, 90, 96, 90],
    "explanation": "Even 3-ply heat spread prevents milk and tea from burning at the bottom, cutting scrubbing detergent and water usage.",
    "mats": [{"name": "Triply Stainless Steel Layer", "percentage": 85, "isRecycled": True}, {"name": "Cast Stainless Steel Handle", "percentage": 10, "isRecycled": True}, {"name": "Tempered Glass Lid", "percentage": 5, "isRecycled": False}],
    "pack": "Cardboard carton",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "National standard"}],
    "strengths": ["Cast stainless steel handle riveted permanently with zero plastic components", "Induction and gas compatible"],
    "improvements": ["Metal handle can become warm during extended simmering"]
  },
  {
    "id": "meyer-preseasoned-cast-iron-skillet-26cm",
    "name": "Meyer Pre-Seasoned Cast Iron 26cm Skillet Frying Pan",
    "brand": "Meyer",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 2490,
    "score": 96.0,
    "carbon": 11.0,
    "conv_carb": 42.0,
    "water": 190,
    "lifespan": 50.0,
    "sub": [97, 98, 100, 98, 94, 100, 92],
    "explanation": "Heirloom cookware that lasts for generations; seasoned exclusively with 100% natural vegetable oil with zero synthetic chemical resins.",
    "mats": [{"name": "100% Molten Iron Ore & Recycled Pig Iron", "percentage": 98, "isRecycled": True}, {"name": "Baked Vegetable Oil Seasoning", "percentage": 2, "isRecycled": False, "isRenewable": True}],
    "pack": "Plastic-free unbleached kraft box with natural jute cord",
    "plastic_free": True,
    "certs": [{"id": "fda-food", "name": "US FDA Food Contact Safe", "issuer": "FDA", "verified": True, "description": "Heavy metals and lead free"}, {"id": "zero-chemical", "name": "Zero PTFE / PFOA / PFAS", "issuer": "SGS", "verified": True, "description": "Certified chemical free"}],
    "strengths": ["Infuses natural dietary iron into cooking, combating nutritional anemia", "Virtually indestructible lifespan lasting 50 to 100+ years", "100% recyclable metal at eventual end of life"],
    "improvements": ["Heavy 2.4kg mass requires two hands to lift"]
  },
  {
    "id": "indus-valley-cast-iron-tawa-28cm",
    "name": "The Indus Valley Super Smooth Cast Iron Dosa Tawa 28cm",
    "brand": "The Indus Valley",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 1499,
    "score": 95.5,
    "carbon": 9.8,
    "conv_carb": 39.0,
    "water": 180,
    "lifespan": 40.0,
    "sub": [96, 97, 100, 97, 94, 100, 92],
    "explanation": "CNC machine-smoothed cast iron tawa pre-seasoned with gingelly sesame oil; replaces toxic Teflon dosa pans.",
    "mats": [{"name": "Cast Iron", "percentage": 98, "isRecycled": True}, {"name": "Pure Sesame Seed Oil", "percentage": 2, "isRecycled": False, "isRenewable": True}],
    "pack": "100% plastic-free recycled paper packaging",
    "plastic_free": True,
    "certs": [{"id": "toxin-free", "name": "Toxin-Free Food Grade", "issuer": "NABL Lab India", "verified": True, "description": "Zero chemical leaching"}],
    "strengths": ["Smooth machine-finished surface creates non-stick crispy dosas naturally", "Zero synthetic plastic chemical coatings"],
    "improvements": ["Must be dried promptly after washing to prevent natural surface oxidation"]
  },
  {
    "id": "wonderchef-granite-dosa-tawa-28cm",
    "name": "Wonderchef Granite Non-Stick Dosa Tawa 28cm (PFOA Free, Virgin Aluminium)",
    "brand": "Wonderchef",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 1299,
    "score": 73.0,
    "carbon": 18.0,
    "conv_carb": 26.0,
    "water": 390,
    "lifespan": 3.0,
    "sub": [72, 70, 76, 74, 82, 68, 76],
    "explanation": "Forged virgin aluminium with mineral-reinforced 5-layer granite stone coating; PFOA free.",
    "mats": [{"name": "Virgin Aluminium", "percentage": 80, "isRecycled": False}, {"name": "Water-based Fluoropolymer Granite Coating", "percentage": 10, "isRecycled": False}, {"name": "Soft-touch Bakelite Handle", "percentage": 10, "isRecycled": False}],
    "pack": "Printed carton with shrink film",
    "plastic_free": False,
    "certs": [{"id": "pfoa-free", "name": "100% PFOA Free Certified", "issuer": "TÜV Rheinland", "verified": True, "description": "No toxic surfactants"}],
    "strengths": ["Lightweight and easy for daily fast morning breakfast preparation", "PFOA free"],
    "improvements": ["Fluoropolymer coating wears off in 2-3 years, forcing full pan replacement"]
  },
  {
    "id": "pigeon-cruise-induction-cooktop",
    "name": "Pigeon by Stovekraft Cruise 1800W Induction Cooktop with LED Display (Black)",
    "brand": "Pigeon",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 1799,
    "score": 85.0,
    "carbon": 22.0,
    "conv_carb": 65.0,
    "water": 360,
    "lifespan": 8.0,
    "sub": [86, 84, 88, 85, 88, 80, 88],
    "explanation": "93% thermal energy efficiency directly heats magnetic cookware, eliminating fossil LPG cylinder combustion in the kitchen.",
    "mats": [{"name": "Microcrystalline Ceramic Glass Plate", "percentage": 35, "isRecycled": False}, {"name": "High-purity Copper Induction Coil", "percentage": 30, "isRecycled": True}, {"name": "Fire-retardant ABS Body", "percentage": 25, "isRecycled": False}, {"name": "Control Electronics", "percentage": 10, "isRecycled": False}],
    "pack": "Cardboard box with paper padding",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified (IS 302)", "issuer": "BIS India", "verified": True, "description": "Electric kitchen appliance safety"}],
    "strengths": ["93% energy efficiency compared to 40% efficiency of domestic gas burners", "Eliminates indoor kitchen fossil fuel gas exhaust fumes and nitrogen dioxide"],
    "improvements": ["Only functions with ferromagnetic cookware (cast iron, stainless steel)"]
  },
  {
    "id": "prestige-pic-20-induction-cooktop",
    "name": "Prestige PIC 20 1600W Induction Cooktop with Indian Menu Presets",
    "brand": "Prestige",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 2495,
    "score": 86.0,
    "carbon": 24.0,
    "conv_carb": 68.0,
    "water": 380,
    "lifespan": 8.5,
    "sub": [87, 85, 89, 86, 89, 82, 88],
    "explanation": "Custom Indian cooking menu presets (Dosa, Chapati, Idli, Curry) regulate precise wattages to prevent wasted electrical draw.",
    "mats": [{"name": "Ceramic Vitro-Crystal Plate", "percentage": 36, "isRecycled": False}, {"name": "Copper Induction Coils", "percentage": 32, "isRecycled": True}, {"name": "Engineered Polymer Frame", "percentage": 22, "isRecycled": False}, {"name": "PCB", "percentage": 10, "isRecycled": False}],
    "pack": "Cardboard carton",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Quality standard"}],
    "strengths": ["Automatic voltage regulator handles Indian grid spikes", "Child lock safety cutoff prevents accidental activation"],
    "improvements": ["Cooling fan creates slight audible airflow sound during operation"]
  },
  {
    "id": "philips-daily-air-fryer-hd9218",
    "name": "Philips Daily Collection Air Fryer with Rapid Air Technology (HD9218/50, Black)",
    "brand": "Philips",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 6999,
    "score": 84.5,
    "carbon": 38.0,
    "conv_carb": 85.0,
    "water": 590,
    "lifespan": 8.0,
    "sub": [84, 83, 90, 84, 88, 82, 88],
    "explanation": "Rapid Air circular convection fries with up to 90% less oil, drastically cutting consumption of edible cooking oils and domestic disposal fat.",
    "mats": [{"name": "Food-grade Stainless Steel Basket & Element", "percentage": 40, "isRecycled": True}, {"name": "Heat-resistant Polypropylene Shell", "percentage": 42, "isRecycled": False}, {"name": "Convection Motor & Electronics", "percentage": 18, "isRecycled": True}],
    "pack": "Recyclable cardboard carton",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "Safety standard"}, {"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Chemical compliance"}],
    "strengths": ["Cuts household cooking oil consumption by up to 90%, reducing palm oil deforestation demand", "Automatic shut-off timer prevents food burning"],
    "improvements": ["Basket non-stick coating requires gentle sponge washing to prevent scratches"]
  },
  {
    "id": "bajaj-platini-stand-mixer-1000w",
    "name": "Bajaj Platini Stand Mixer 1000W with 5.2L Stainless Steel Bowl (Black)",
    "brand": "Bajaj",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 8999,
    "score": 83.0,
    "carbon": 46.0,
    "conv_carb": 88.0,
    "water": 640,
    "lifespan": 10.0,
    "sub": [82, 83, 92, 83, 86, 84, 86],
    "explanation": "Full metal gear system and 5.2L stainless steel bowl engineered for heavy dough kneading without motor burnout.",
    "mats": [{"name": "AISI 304 Stainless Steel Mixing Bowl", "percentage": 35, "isRecycled": True}, {"name": "Cast Die-Cast Aluminium Attachments", "percentage": 25, "isRecycled": True}, {"name": "Heavy-duty Copper Motor", "percentage": 25, "isRecycled": True}, {"name": "ABS Outer Shell", "percentage": 15, "isRecycled": False}],
    "pack": "Corrugated box with cardboard inserts",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS", "verified": True, "description": "Consumer safety"}],
    "strengths": ["Full metal planetary gear transmission prevents plastic gear stripping", "Eliminates bakery plastic bread packaging via home whole-grain baking"],
    "improvements": ["Heavy 7kg footprint occupies dedicated kitchen counter space"]
  },
  {
    "id": "sujata-powermatic-plus-juicer-mixer",
    "name": "Sujata Powermatic Plus 900W Juicer Mixer Grinder with Honeycomb Mesh (White)",
    "brand": "Sujata",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 5799,
    "score": 89.0,
    "carbon": 36.0,
    "conv_carb": 82.0,
    "water": 520,
    "lifespan": 15.0,
    "sub": [88, 88, 98, 88, 88, 95, 88],
    "explanation": "Legendary commercial-grade 900W pure copper motor with 22,000 RPM double ball bearings runs continuously for 90 minutes; built to last 15+ years in Indian kitchens.",
    "mats": [{"name": "Heavy Gauge Stainless Steel Jars", "percentage": 42, "isRecycled": True}, {"name": "Pure Copper Wound Motor & Steel Ball Bearings", "percentage": 38, "isRecycled": True}, {"name": "Shockproof High-grade Polymer Body", "percentage": 20, "isRecycled": False}],
    "pack": "Heavy cardboard carton",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified (IS 4250)", "issuer": "BIS India", "verified": True, "description": "Safety standard for domestic food mixers"}],
    "strengths": ["Extreme 15+ year operational lifespan makes it an Indian kitchen icon", "All carbon brushes, drive couplers, and jar gaskets readily available at every local repair shop", "Honeycomb micro-mesh extracts maximum juice without pulp waste"],
    "improvements": ["High sound output (approx. 80dB) during heavy dry masala grinding"]
  },
  {
    "id": "borosil-glass-mixing-bowl-set",
    "name": "Borosil Glass Mixing Bowl Set with Plastic Lids (Set of 3: 500ml, 900ml, 1.3L)",
    "brand": "Borosil",
    "cat": "Home & Kitchen",
    "subcat": "Food Storage",
    "price": 1099,
    "score": 93.0,
    "carbon": 8.2,
    "conv_carb": 28.0,
    "water": 190,
    "lifespan": 20.0,
    "sub": [94, 95, 96, 95, 90, 94, 90],
    "explanation": "100% borosilicate glass with zero chemical leaching; withstands temperatures up to 350°C and safe for oven, microwave, freezer, and dishwasher.",
    "mats": [{"name": "100% Pure Borosilicate Glass", "percentage": 88, "isRecycled": False, "isRenewable": True}, {"name": "BPA-Free Polypropylene Lids", "percentage": 12, "isRecycled": False}],
    "pack": "Plastic-free corrugated cardboard presentation box",
    "plastic_free": True,
    "certs": [{"id": "food-grade", "name": "100% Food Grade Borosilicate", "issuer": "Borosil Labs", "verified": True, "description": "Guaranteed zero leaching"}, {"id": "lead-cadmium-free", "name": "Lead & Cadmium Free Certified", "issuer": "SGS", "verified": True, "description": "Pure non-toxic glass"}],
    "strengths": ["Does not absorb turmeric stains, food odors, or tomato acid etchings like plastic containers", "Zero microplastic migration when reheating hot Indian food", "Safe from freezer to microwave"],
    "improvements": ["Glass can chip if dropped onto granite countertops"]
  },
  {
    "id": "borosil-klip-n-store-glass-containers",
    "name": "Borosil Klip N Store 3-Piece Rectangular Glass Storage Container Set (320ml, 520ml, 800ml)",
    "brand": "Borosil",
    "cat": "Home & Kitchen",
    "subcat": "Food Storage",
    "price": 1295,
    "score": 92.5,
    "carbon": 8.8,
    "conv_carb": 29.0,
    "water": 210,
    "lifespan": 18.0,
    "sub": [93, 94, 95, 94, 90, 92, 90],
    "explanation": "Airtight silicone gasket with 4-way lock clips keeps food fresh without plasticizer chemical migration.",
    "mats": [{"name": "Borosilicate Glass Base", "percentage": 82, "isRecycled": False}, {"name": "BPA-Free PP Lid with Silicone Ring", "percentage": 18, "isRecycled": False}],
    "pack": "Recyclable cardboard box",
    "plastic_free": True,
    "certs": [{"id": "bpa-free", "name": "100% BPA Free", "issuer": "SGS", "verified": True, "description": "Chemical safety"}],
    "strengths": ["Completely leak-proof airtight seal eliminates single-use cling film wrap", "Microwave safe without lid"],
    "improvements": ["Silicone sealing ring must be removed periodically for thorough cleaning"]
  },
  {
    "id": "borosil-vision-classic-tumblers-6pack",
    "name": "Borosil Vision Classic Glass Tumblers 295ml (Pack of 6, Borosilicate)",
    "brand": "Borosil",
    "cat": "Home & Kitchen",
    "subcat": "Drinkware",
    "price": 540,
    "score": 94.0,
    "carbon": 6.5,
    "conv_carb": 24.0,
    "water": 160,
    "lifespan": 20.0,
    "sub": [95, 96, 96, 96, 94, 95, 90],
    "explanation": "Iconic Indian minimalist design crafted from 100% borosilicate glass that will not turn cloudy or scratch after thousands of dishwasher washes.",
    "mats": [{"name": "100% Borosilicate Glass", "percentage": 100, "isRecycled": False}],
    "pack": "100% recyclable cardboard box with paper dividers",
    "plastic_free": True,
    "certs": [{"id": "lead-free", "name": "Lead and Cadmium Free", "issuer": "SGS", "verified": True, "description": "Zero heavy metal release"}],
    "strengths": ["100% plastic-free glass drinking solution", "Can pour boiling hot tea or icy cold water directly without thermal shock cracking", "Zero plastic packaging"],
    "improvements": ["Lightweight glass walls feel delicate to heavy-handed users"]
  },
  {
    "id": "milton-thermosteel-flip-lid-1000ml",
    "name": "Milton Thermosteel Flip Lid Insulated Stainless Steel Flask 1000ml (Silver)",
    "brand": "Milton",
    "cat": "Home & Kitchen",
    "subcat": "Drinkware",
    "price": 1099,
    "score": 93.0,
    "carbon": 8.5,
    "conv_carb": 32.0,
    "water": 210,
    "lifespan": 15.0,
    "sub": [94, 93, 98, 94, 90, 94, 90],
    "explanation": "Double-walled vacuum insulation with copper coating keeps beverages hot or cold for 24 hours, replacing hundreds of single-use PET plastic bottles.",
    "mats": [{"name": "Food Grade 304 Stainless Steel Inner & Outer", "percentage": 88, "isRecycled": True}, {"name": "Copper Inner Coating", "percentage": 4, "isRecycled": True}, {"name": "BPA-Free Polypropylene Lid & Cup", "percentage": 6, "isRecycled": False}, {"name": "Food-grade Silicone Seal Ring", "percentage": 2, "isRecycled": False}],
    "pack": "Cardboard gift box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified (IS 17526)", "issuer": "BIS India", "verified": True, "description": "National stainless steel vacuum flask standard"}, {"id": "bpa-free", "name": "BPA Free Tested", "issuer": "Intertek", "verified": True, "description": "Toxic plastic chemical free"}],
    "strengths": ["Copper-plated vacuum core maintains 24-hour thermal performance", "Durable stainless steel jacket survives drops without vacuum failure", "Replaces thousands of single-use mineral water plastic bottles over its lifespan"],
    "improvements": ["Outer fabric thermal pouch contains non-recyclable synthetic foam"]
  },
  {
    "id": "cello-infuser-steel-water-bottle-800ml",
    "name": "Cello Infuser Stainless Steel Water Bottle with Fruit Strainer 800ml",
    "brand": "Cello",
    "cat": "Home & Kitchen",
    "subcat": "Drinkware",
    "price": 799,
    "score": 91.5,
    "carbon": 7.8,
    "conv_carb": 28.0,
    "water": 190,
    "lifespan": 12.0,
    "sub": [93, 92, 96, 93, 90, 92, 88],
    "explanation": "Single-wall lightweight stainless steel bottle with integrated removable stainless infuser strainer for detox fruit and herb infusions.",
    "mats": [{"name": "18/8 Food Grade Stainless Steel", "percentage": 92, "isRecycled": True}, {"name": "Silicone O-Ring", "percentage": 3, "isRecycled": False}, {"name": "BPA-Free Cap", "percentage": 5, "isRecycled": False}],
    "pack": "100% recyclable paper box",
    "plastic_free": True,
    "certs": [{"id": "bpa-free", "name": "BPA Free Certified", "issuer": "TÜV", "verified": True, "description": "Chemical safety"}],
    "strengths": ["Built-in stainless steel infuser basket encourages drinking tap water infused with lemon/mint rather than bottled sugary drinks", "Rust-proof 18/8 steel"],
    "improvements": ["Single-wall construction causes exterior condensation with ice water"]
  },
  {
    "id": "tupperware-aquasafe-fliptop-1l-set",
    "name": "Tupperware Aquasafe Fliptop Water Bottles 1L (Set of 4, Vibrant Colors)",
    "brand": "Tupperware",
    "cat": "Home & Kitchen",
    "subcat": "Drinkware",
    "price": 1280,
    "score": 82.0,
    "carbon": 9.2,
    "conv_carb": 26.0,
    "water": 240,
    "lifespan": 10.0,
    "sub": [83, 81, 92, 84, 82, 85, 84],
    "explanation": "100% virgin food-grade polypropylene certified BPA-free with tight flip-top seal, engineered for over a decade of daily refrigerator use.",
    "mats": [{"name": "100% Virgin Food-Grade Polypropylene (#5 PP)", "percentage": 98, "isRecycled": False}, {"name": "Silicone Tab", "percentage": 2, "isRecycled": False}],
    "pack": "Cardboard carton",
    "plastic_free": False,
    "certs": [{"id": "bpa-free", "name": "100% BPA Free", "issuer": "Tupperware Quality", "verified": True, "description": "Zero estrogenic activity chemicals"}, {"id": "fda-safe", "name": "US FDA Compliant", "issuer": "FDA", "verified": True, "description": "Safe for repeat food contact"}],
    "strengths": ["Durable heavy-gauge polypropylene does not degrade or leach microplastics in refrigerator temperatures", "Flip-top spout allows easy one-handed drinking"],
    "improvements": ["Manufactured from virgin petroleum-based polymers rather than recycled resins"]
  },
  {
    "id": "tupperware-modular-mates-oval-set",
    "name": "Tupperware Modular Mates Oval Kitchen Storage Container Set (Set of 4)",
    "brand": "Tupperware",
    "cat": "Home & Kitchen",
    "subcat": "Food Storage",
    "price": 2490,
    "score": 83.5,
    "carbon": 11.5,
    "conv_carb": 31.0,
    "water": 290,
    "lifespan": 15.0,
    "sub": [84, 82, 95, 85, 84, 88, 86],
    "explanation": "Modular stackable pantry storage with airtight seals keeps pulses, rice, and spices free from moisture and weevils for months.",
    "mats": [{"name": "High-clarity Polypropylene Body", "percentage": 75, "isRecycled": False}, {"name": "Low-density Polyethylene Airtight Seal Lid", "percentage": 25, "isRecycled": False}],
    "pack": "Recyclable cardboard box",
    "plastic_free": False,
    "certs": [{"id": "bpa-free", "name": "BPA Free", "issuer": "Tupperware", "verified": True, "description": "Safe plastic"}, {"id": "airtight", "name": "Airtight Seal Certified", "issuer": "NABL Lab", "verified": True, "description": "Moisture barrier"}],
    "strengths": ["Airtight moisture barrier prevents weevil and fungal infestation in stored grains, preventing bulk food waste", "Stackable modular form factor maximizes pantry cabinet vertical volume"],
    "improvements": ["Lids require hand washing in warm water to avoid warping"]
  },
  {
    "id": "vaya-tyffyn-1000ml-insulated-lunchbox",
    "name": "Vaya Tyffyn 1000ml Polished Insulated Stainless Steel Lunch Box (Graphite)",
    "brand": "Vaya",
    "cat": "Home & Kitchen",
    "subcat": "Food Storage",
    "price": 2990,
    "score": 91.0,
    "carbon": 13.0,
    "conv_carb": 38.0,
    "water": 310,
    "lifespan": 15.0,
    "sub": [92, 92, 96, 92, 90, 92, 88],
    "explanation": "VacuTherm technology keeps home-cooked meals warm for up to 6 hours; stainless steel containers with leak-resistant silicone lids eliminate disposable foil wraps.",
    "mats": [{"name": "AISI 304 Stainless Steel Containers & Shell", "percentage": 82, "isRecycled": True}, {"name": "Food-grade Silicone Lids & Partitions", "percentage": 14, "isRecycled": False}, {"name": "Copper Coating & Latches", "percentage": 4, "isRecycled": True}],
    "pack": "100% plastic-free recycled paperboard box with magnetic closure",
    "plastic_free": True,
    "certs": [{"id": "bpa-free", "name": "BPA Free", "issuer": "Intertek", "verified": True, "description": "Non-toxic food contact safe"}, {"id": "fda-safe", "name": "FDA Approved Materials", "issuer": "FDA", "verified": True, "description": "Food safe"}],
    "strengths": ["Eliminates daily plastic bags, aluminum foil wraps, and disposable takeout containers", "Keeps meals warm without needing office microwave reheating power", "Dishwasher safe containers"],
    "improvements": ["Total packed lunch weight of 1.1kg is heavier than plastic lunchboxes"]
  },
  {
    "id": "vaya-drynk-600ml-tumbler",
    "name": "Vaya Drynk 600ml Insulated Tumbler with Magnetic Cap (Ombre Black)",
    "brand": "Vaya",
    "cat": "Home & Kitchen",
    "subcat": "Drinkware",
    "price": 1790,
    "score": 92.0,
    "carbon": 8.0,
    "conv_carb": 28.0,
    "water": 200,
    "lifespan": 15.0,
    "sub": [93, 93, 97, 93, 92, 93, 88],
    "explanation": "Vacuum insulated tumbler keeps cold drinks chilled for 18 hours and hot tea warm for 12 hours with magnetic latch cap that stays open while sipping.",
    "mats": [{"name": "304 Stainless Steel Body", "percentage": 84, "isRecycled": True}, {"name": "Magnetic Flip Cap Assembly", "percentage": 12, "isRecycled": False}, {"name": "Silicone Bottom Base & Seals", "percentage": 4, "isRecycled": False}],
    "pack": "Plastic-free presentation box",
    "plastic_free": True,
    "certs": [{"id": "bpa-free", "name": "BPA Free", "issuer": "Intertek", "verified": True, "description": "Chemical safety"}],
    "strengths": ["Magnetic cap locks back into place so it never hits the nose while drinking", "Anti-slip silicone coaster base prevents desk clanking noise and surface scratches"],
    "improvements": ["Sippy lid requires occasional disassembly for deep cleaning"]
  },
  {
    "id": "signoraware-besto-lunchbox",
    "name": "Signoraware Besto Insulated Stainless Steel Lunch Box (4 Containers + Bag)",
    "brand": "Signoraware",
    "cat": "Home & Kitchen",
    "subcat": "Food Storage",
    "price": 1150,
    "score": 87.0,
    "carbon": 10.5,
    "conv_carb": 30.0,
    "water": 260,
    "lifespan": 10.0,
    "sub": [88, 88, 93, 88, 86, 88, 86],
    "explanation": "Food-grade stainless steel bowls with virgin polypropylene airtight lids, manufactured in Kala Amb, Himachal Pradesh.",
    "mats": [{"name": "Stainless Steel Inner Bowls", "percentage": 68, "isRecycled": True}, {"name": "BPA-Free Plastic Lids", "percentage": 20, "isRecycled": False}, {"name": "Washable Fabric Tote Bag", "percentage": 12, "isRecycled": False}],
    "pack": "Cardboard carton",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "National quality standard"}, {"id": "bpa-free", "name": "BPA Free", "issuer": "Signoraware", "verified": True, "description": "Non-toxic certified"}],
    "strengths": ["Domestic manufacturing in Himachal Pradesh", "Leak-resistant lids with air release vent button for hot curries"],
    "improvements": ["Thermal bag uses synthetic polyester fabric"]
  },
  {
    "id": "prestige-iris-750w-mixer-grinder",
    "name": "Prestige Iris 750W Mixer Grinder with 4 Stainless Steel Jars (White/Blue)",
    "brand": "Prestige",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 3199,
    "score": 84.0,
    "carbon": 32.0,
    "conv_carb": 68.0,
    "water": 460,
    "lifespan": 10.0,
    "sub": [83, 84, 91, 84, 86, 88, 88],
    "explanation": "750-watt heavy duty motor with overload protector switch and 4 heavy gauge stainless steel jars.",
    "mats": [{"name": "AISI 304 Stainless Steel Jars", "percentage": 45, "isRecycled": True}, {"name": "Copper Motor Windings", "percentage": 30, "isRecycled": True}, {"name": "Shockproof ABS Body", "percentage": 25, "isRecycled": False}],
    "pack": "Cardboard carton with paper buffers",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS India", "verified": True, "description": "National safety compliance"}],
    "strengths": ["Overload thermal cut-off switch protects motor from burning out during heavy grinding", "Widely available replacement couplers and blades across India"],
    "improvements": ["Plastic jar dome lids can cloud over time if washed with harsh abrasives"]
  },
  {
    "id": "borosil-electric-kettle-1-5l",
    "name": "Borosil Stainless Steel Electric Kettle 1.5L (Rio, 1500W)",
    "brand": "Borosil",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 1499,
    "score": 87.0,
    "carbon": 14.0,
    "conv_carb": 34.0,
    "water": 260,
    "lifespan": 8.0,
    "sub": [86, 88, 92, 87, 88, 86, 88],
    "explanation": "Boils 1.5 liters of water in under 4 minutes with automatic dry-boil cutoff, far more energy efficient than open gas stove boiling.",
    "mats": [{"name": "Food Grade 304 Stainless Steel Body", "percentage": 65, "isRecycled": True}, {"name": "Concealed Heating Element & Copper Wire", "percentage": 20, "isRecycled": True}, {"name": "Cool-Touch Polypropylene Handle & Base", "percentage": 15, "isRecycled": False}],
    "pack": "Recyclable cardboard box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS", "verified": True, "description": "Safety compliance"}, {"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Chemical compliance"}],
    "strengths": ["Concealed heating plate resists scale buildup and facilitates effortless descaling with simple vinegar", "Auto shut-off prevents electrical waste"],
    "improvements": ["Outer metal single-wall body becomes hot during boiling"]
  },
  {
    "id": "kent-grand-plus-ro-water-purifier",
    "name": "Kent Grand Plus RO+UV+UF+TDS Water Purifier with Zero Water Wastage (9L)",
    "brand": "Kent",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 16999,
    "score": 86.5,
    "carbon": 48.0,
    "conv_carb": 95.0,
    "water": 1200,
    "lifespan": 10.0,
    "sub": [85, 87, 92, 86, 88, 88, 90],
    "explanation": "Zero Water Wastage technology pumps rejected RO water back into overhead tank, saving up to 20,000 liters of potable water per household per year.",
    "mats": [{"name": "Food Grade ABS Storage Tank", "percentage": 48, "isRecycled": False}, {"name": "RO Membrane & Carbon Filter Blocks", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Booster Pump & UV Chamber", "percentage": 27, "isRecycled": True}],
    "pack": "Heavy corrugated box",
    "plastic_free": False,
    "certs": [{"id": "wqa-gold", "name": "WQA Gold Seal Certified", "issuer": "Water Quality Association USA", "verified": True, "description": "Global drinking water standard (NSF/ANSI 58)"}, {"id": "isi", "name": "BIS ISI Certified", "issuer": "BIS India", "verified": True, "description": "National drinking water standard"}],
    "strengths": ["Zero Water Wastage recirculation system completely solves the massive water wastage problem of conventional RO purifiers", "Eliminates need for 20-liter plastic packaged water bubbles"],
    "improvements": ["Membranes must be replaced annually creating non-biodegradable filter cartridge waste"]
  },
  {
    "id": "eureka-forbes-aquaguard-aura-ro",
    "name": "Eureka Forbes Aquaguard Aura RO+UV+Active Copper Water Purifier (7L, Black)",
    "brand": "Eureka Forbes",
    "cat": "Home & Kitchen",
    "subcat": "Home Appliances",
    "price": 15499,
    "score": 85.5,
    "carbon": 46.0,
    "conv_carb": 92.0,
    "water": 1300,
    "lifespan": 10.0,
    "sub": [84, 86, 91, 85, 88, 87, 90],
    "explanation": "Active Copper Zinc Booster infuses natural copper ions according to Indian traditional Ayurveda; mineral guard technology retains essential calcium and magnesium.",
    "mats": [{"name": "Food-grade Polymer Body", "percentage": 50, "isRecycled": False}, {"name": "Active Copper & Zinc Cartridge", "percentage": 15, "isRecycled": False}, {"name": "Pump & Electronics", "percentage": 35, "isRecycled": True}],
    "pack": "Cardboard packaging",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS IS 10500 Certified", "issuer": "BIS", "verified": True, "description": "Potable drinking water compliance"}],
    "strengths": ["Copper-infused hydration improves natural immune wellness", "Long-lasting UV e-boiling chamber"],
    "improvements": ["Reject water tube must be routed manually to garden or cleaning bucket"]
  },
  {
    "id": "milton-pro-stainless-steel-bottle-750ml",
    "name": "Milton Pro Stainless Steel Water Bottle 750ml (Single Wall, Matte Silver)",
    "brand": "Milton",
    "cat": "Home & Kitchen",
    "subcat": "Drinkware",
    "price": 425,
    "score": 93.0,
    "carbon": 5.8,
    "conv_carb": 22.0,
    "water": 140,
    "lifespan": 15.0,
    "sub": [94, 94, 98, 95, 92, 95, 90],
    "explanation": "Ultra-lightweight 100% food-grade stainless steel bottle designed to fit standard bicycle cages and backpack bottle pockets.",
    "mats": [{"name": "Grade 304 Food Grade Stainless Steel", "percentage": 94, "isRecycled": True}, {"name": "Silicone Seal Ring", "percentage": 2, "isRecycled": False}, {"name": "Stainless Steel Cap Liner", "percentage": 4, "isRecycled": True}],
    "pack": "100% recyclable paper box",
    "plastic_free": True,
    "certs": [{"id": "food-grade", "name": "Food Grade Stainless Steel", "issuer": "Milton Quality", "verified": True, "description": "Toxin and heavy metal free"}],
    "strengths": ["Single-wall design is extremely lightweight for hiking and daily school/office carry", "100% recyclable metal body", "Plastic-free cap design"],
    "improvements": ["Does not retain beverage hot/cold temperatures like double-wall flasks"]
  },
  {
    "id": "cello-maxima-glass-storage-jars-6pack",
    "name": "Cello Maxima Airtight Modular Kitchen Glass Storage Jars 1000ml (Set of 6)",
    "brand": "Cello",
    "cat": "Home & Kitchen",
    "subcat": "Food Storage",
    "price": 1199,
    "score": 93.5,
    "carbon": 9.5,
    "conv_carb": 30.0,
    "water": 220,
    "lifespan": 25.0,
    "sub": [95, 96, 96, 95, 92, 94, 90],
    "explanation": "Pure soda-lime lead-free glass jars with airtight steel-finish lids for storing dal, spices, and snacks without plastic chemical leaching.",
    "mats": [{"name": "Lead-Free Pure Glass", "percentage": 85, "isRecycled": True}, {"name": "Stainless Steel Clad PP Lids", "percentage": 12, "isRecycled": True}, {"name": "Silicone Airtight Gasket", "percentage": 3, "isRecycled": False}],
    "pack": "100% recyclable cardboard box with protective partitions",
    "plastic_free": True,
    "certs": [{"id": "lead-cadmium-free", "name": "Lead & Cadmium Free Certified", "issuer": "SGS", "verified": True, "description": "Zero toxic metals"}, {"id": "fda-safe", "name": "FDA Food Contact Safe", "issuer": "FDA", "verified": True, "description": "Food safety standard"}],
    "strengths": ["Completely non-porous glass prevents oil absorption and spice odor retention", "Airtight seal keeps humidity out during heavy Indian monsoon seasons"],
    "improvements": ["Glass jars are breakable if dropped on ceramic tiles"]
  },
  {
    "id": "hawkins-hevibase-induction-cooker-3l",
    "name": "Hawkins Hevibase Induction Compatible Pressure Cooker 3L",
    "brand": "Hawkins",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 2425,
    "score": 91.0,
    "carbon": 15.0,
    "conv_carb": 44.0,
    "water": 410,
    "lifespan": 20.0,
    "sub": [91, 90, 97, 92, 91, 95, 92],
    "explanation": "Double thick 6.35mm heavy magnetic stainless steel base attached to virgin aluminium body distributes heat evenly and works on gas and induction.",
    "mats": [{"name": "Heavy Gauge Virgin Aluminium Body", "percentage": 70, "isRecycled": False}, {"name": "AISI 430 Magnetic Stainless Steel Base", "percentage": 20, "isRecycled": True}, {"name": "Bakelite Stay-Cool Handles", "percentage": 8, "isRecycled": False}, {"name": "Gasket & Valve", "percentage": 2, "isRecycled": False}],
    "pack": "Cardboard carton box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified (IS 2347)", "issuer": "BIS India", "verified": True, "description": "Safety standard"}],
    "strengths": ["Heavy 6.35mm base eliminates hot spots that burn rice or dal", "Inside-fitting lid provides foolproof pressure containment safety"],
    "improvements": ["Aluminium inner surface can discolor slightly with alkaline tap water"]
  },
  {
    "id": "pigeon-induction-aluminium-cooker-5l",
    "name": "Pigeon by Stovekraft Special Induction Base Aluminium Cooker 5L",
    "brand": "Pigeon",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 1499,
    "score": 87.0,
    "carbon": 17.5,
    "conv_carb": 40.0,
    "water": 430,
    "lifespan": 15.0,
    "sub": [88, 86, 92, 88, 86, 92, 88],
    "explanation": "Budget-friendly family-sized pressure cooker with induction bottom, manufactured in Bengaluru under Indian quality standards.",
    "mats": [{"name": "Virgin Aluminium Alloy", "percentage": 78, "isRecycled": False}, {"name": "Stainless Steel Induction Plate", "percentage": 14, "isRecycled": True}, {"name": "Bakelite Handles", "percentage": 6, "isRecycled": False}, {"name": "Nitrile Gasket", "percentage": 2, "isRecycled": False}],
    "pack": "Cardboard carton",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS", "verified": True, "description": "Indian standard"}],
    "strengths": ["Large 5L volume accommodates bulk family meal prep efficiently in a single cooking cycle", "Affordable pricing"],
    "improvements": ["Aluminium body reacts with tamarind or acidic tomato sauces if stored overnight"]
  },
  {
    "id": "wonderchef-nutri-blend-compact-blender",
    "name": "Wonderchef Nutri-Blend 400W Mixer Grinder & Blender with 2 Unbreakable Jars (Black)",
    "brand": "Wonderchef",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 2799,
    "score": 81.0,
    "carbon": 22.0,
    "conv_carb": 45.0,
    "water": 380,
    "lifespan": 6.5,
    "sub": [81, 80, 86, 82, 85, 80, 84],
    "explanation": "Compact 400W high-speed motor extracts maximum nutrients from fruits and vegetables in 30 seconds.",
    "mats": [{"name": "Transparent Polycarbonate Jars", "percentage": 35, "isRecycled": False}, {"name": "Copper Windings & Motor", "percentage": 35, "isRecycled": True}, {"name": "Stainless Steel Surgical Blades", "percentage": 15, "isRecycled": True}, {"name": "ABS Base Casing", "percentage": 15, "isRecycled": False}],
    "pack": "Cardboard gift box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Certified", "issuer": "BIS India", "verified": True, "description": "National approval"}],
    "strengths": ["Compact countertop footprint encourages daily healthy green smoothie preparation", "Extracts micro-nutrients by pulverizing seeds and skins"],
    "improvements": ["Polycarbonate jars can develop fine cloudy lines after grinding hard turmeric roots"]
  },
  {
    "id": "milton-spotzero-microfiber-spin-mop",
    "name": "Milton Spotzero Classic Microfiber Spin Mop with Plastic Bucket & Steel Rod",
    "brand": "Milton",
    "cat": "Home & Kitchen",
    "subcat": "Cleaning Tools",
    "price": 1299,
    "score": 88.0,
    "carbon": 14.0,
    "conv_carb": 32.0,
    "water": 280,
    "lifespan": 8.0,
    "sub": [89, 87, 92, 88, 88, 92, 86],
    "explanation": "High-absorption microfiber mop head cleans floors using 50% less chemical floor cleaners and water, with easily replaceable refill heads.",
    "mats": [{"name": "Heavy Duty Polypropylene Bucket", "percentage": 55, "isRecycled": True}, {"name": "Stainless Steel Telescopic Handle", "percentage": 25, "isRecycled": True}, {"name": "Ultra-Fine Microfiber Strands", "percentage": 15, "isRecycled": True}, {"name": "Wringer Mechanism", "percentage": 5, "isRecycled": False}],
    "pack": "Corrugated cardboard box",
    "plastic_free": True,
    "certs": [{"id": "isi", "name": "Milton Spotzero Quality Certified", "issuer": "Spotzero Lab", "verified": True, "description": "Wear-tested gear mechanism"}],
    "strengths": ["Microfiber strands trap dust and hair electrostatically using plain warm water without requiring harsh synthetic floor chemicals", "Modular refill heads sold cheaply across India to avoid bucket replacement"],
    "improvements": ["Microfibers shed tiny synthetic particles during hot wash cycles"]
  },
  {
    "id": "borosil-prime-grill-sandwich-maker",
    "name": "Borosil Prime Grill Sandwich Maker 700W (Black)",
    "brand": "Borosil",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 1790,
    "score": 81.5,
    "carbon": 18.0,
    "conv_carb": 36.0,
    "water": 310,
    "lifespan": 6.0,
    "sub": [82, 80, 87, 82, 86, 78, 84],
    "explanation": "Heats sandwiches in 3 minutes with automatic thermostat control to prevent energy waste.",
    "mats": [{"name": "Die-Cast Aluminium Grill Plates", "percentage": 45, "isRecycled": True}, {"name": "Bakelite Cool-Touch Casing", "percentage": 35, "isRecycled": False}, {"name": "Electric Heating Coil & Wiring", "percentage": 20, "isRecycled": False}],
    "pack": "Cardboard box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "Safety standard"}],
    "strengths": ["Thermal cutout prevents overheating and wasted standby draw", "Compact vertical upright storage saves kitchen cabinet space"],
    "improvements": ["Grill plates are fixed and cannot be removed for dishwasher immersion"]
  },
  {
    "id": "milton-microowow-microwave-tiffin",
    "name": "Milton Microowow Stainless Steel Microwave Safe Tiffin Set (3 Containers)",
    "brand": "Milton",
    "cat": "Home & Kitchen",
    "subcat": "Food Storage",
    "price": 1050,
    "score": 88.5,
    "carbon": 10.0,
    "conv_carb": 28.0,
    "water": 240,
    "lifespan": 12.0,
    "sub": [89, 89, 94, 90, 88, 90, 86],
    "explanation": "Special microwave-safe stainless steel containers eliminate heating food in plastic containers at the office.",
    "mats": [{"name": "Microwave-Safe Stainless Steel Inner", "percentage": 70, "isRecycled": True}, {"name": "BPA-Free Outer Insulation Layer", "percentage": 20, "isRecycled": False}, {"name": "Silicone Airtight Lids", "percentage": 10, "isRecycled": False}],
    "pack": "Cardboard box",
    "plastic_free": True,
    "certs": [{"id": "microwave-safe", "name": "Microwave Safe Steel Certified", "issuer": "TÜV", "verified": True, "description": "Safe for electromagnetic heating"}, {"id": "bpa-free", "name": "BPA Free", "issuer": "Intertek", "verified": True, "description": "Zero phthalates"}],
    "strengths": ["Enables heating office lunch in stainless steel rather than toxic plastic containers", "Completely leak-proof silicone seal lids"],
    "improvements": ["Must be microwaved without the metal rimmed outer lid"]
  },
  {
    "id": "prestige-clean-home-spray-mop",
    "name": "Prestige Clean Home PSB 10 Magic Spray Mop with Microfiber Pad",
    "brand": "Prestige",
    "cat": "Home & Kitchen",
    "subcat": "Cleaning Tools",
    "price": 1495,
    "score": 87.5,
    "carbon": 11.5,
    "conv_carb": 26.0,
    "water": 210,
    "lifespan": 7.0,
    "sub": [88, 86, 91, 88, 87, 90, 86],
    "explanation": "Integrated refillable spray bottle sprays fine mist, using only 200ml of water to mop an entire 1000 sq ft apartment.",
    "mats": [{"name": "Aluminium Handle Pole", "percentage": 50, "isRecycled": True}, {"name": "Refillable Water Bottle & Trigger", "percentage": 30, "isRecycled": False}, {"name": "Washable Microfiber Pad", "percentage": 20, "isRecycled": True}],
    "pack": "Cardboard packaging",
    "plastic_free": True,
    "certs": [{"id": "quality", "name": "Prestige Clean Home Certified", "issuer": "TTK Prestige", "verified": True, "description": "Tested trigger mechanism"}],
    "strengths": ["Uses 90% less water than traditional bucket mopping", "Eliminates heavy dirty water bucket lugging", "Machine-washable microfiber pads reusable 100+ times"],
    "improvements": ["Trigger spray mechanism requires clean water to avoid mineral clogs"]
  },
  {
    "id": "philips-viva-juicer-mixer-grinder",
    "name": "Philips Viva Collection 700W Juicer Mixer Grinder (HL7715/00, Pistachio)",
    "brand": "Philips",
    "cat": "Home & Kitchen",
    "subcat": "Kitchen Appliances",
    "price": 4499,
    "score": 85.0,
    "carbon": 30.0,
    "conv_carb": 62.0,
    "water": 440,
    "lifespan": 10.0,
    "sub": [84, 85, 92, 85, 87, 89, 88],
    "explanation": "Large fruit pulp chamber with micro-mesh filter extracts 20% more juice; pure copper wound motor.",
    "mats": [{"name": "Stainless Steel Jars & Cutter", "percentage": 42, "isRecycled": True}, {"name": "Copper Motor Assembly", "percentage": 33, "isRecycled": True}, {"name": "Food Grade ABS Casing", "percentage": 25, "isRecycled": False}],
    "pack": "Recyclable cardboard carton",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "National approval"}],
    "strengths": ["Extracts maximum juice without needing chemical clarifying additives", "Removable spout for easy sink cleaning"],
    "improvements": ["Plastic fruit pusher feels light"]
  },
  {
    "id": "prestige-omega-deluxe-granite-fry-pan",
    "name": "Prestige Omega Deluxe Granite Fry Pan 24cm with Induction Base",
    "brand": "Prestige",
    "cat": "Home & Kitchen",
    "subcat": "Cookware",
    "price": 1150,
    "score": 75.0,
    "carbon": 16.0,
    "conv_carb": 25.0,
    "water": 360,
    "lifespan": 3.5,
    "sub": [74, 73, 79, 76, 84, 70, 78],
    "explanation": "5-layer non-stick granite spatter finish engineered for German technology standards; PFOA free.",
    "mats": [{"name": "Aluminium Core", "percentage": 76, "isRecycled": False}, {"name": "PTFE Granite Coating", "percentage": 10, "isRecycled": False}, {"name": "Induction Steel Base", "percentage": 10, "isRecycled": True}, {"name": "Bakelite Handle", "percentage": 4, "isRecycled": False}],
    "pack": "Printed carton with shrink sleeve",
    "plastic_free": False,
    "certs": [{"id": "pfoa-free", "name": "PFOA Free Certified", "issuer": "Greblon Germany", "verified": True, "description": "Safe non-stick standard"}],
    "strengths": ["Smooth glide requires minimal oil for egg and pancake cooking", "Induction and gas compatible"],
    "improvements": ["Requires wooden or silicone spatulas to prevent coating scratches"]
  }
]

