# Electronics Catalog Data (75 products)
# Indian Market Electronics: Smartphones, Laptops, Audio, Wearables, Monitors, Power & Tablets

electronics_items = [
  # --- SMARTPHONES (25 items) ---
  {
    "id": "apple-iphone-15-pro",
    "name": "Apple iPhone 15 Pro (128GB, Natural Titanium)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 129900,
    "score": 82.5,
    "carbon": 66.0,
    "conv_carb": 85.0,
    "water": 1650,
    "lifespan": 5.5,
    "sub": [78, 85, 88, 82, 92, 70, 82],
    "explanation": "Grade 5 Titanium substructure with 100% recycled aluminium inner frame and 100% recycled cobalt battery.",
    "mats": [{"name": "Recycled Aluminium", "percentage": 38, "isRecycled": True}, {"name": "Titanium", "percentage": 22, "isRecycled": False}, {"name": "Recycled Cobalt & Rare Earths", "percentage": 15, "isRecycled": True}, {"name": "Ceramic Shield Glass", "percentage": 25, "isRecycled": False}],
    "pack": "100% fiber-based plastic-free retail box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Global eco rating"}],
    "strengths": ["100% recycled cobalt in battery", "100% recycled gold in logic board", "Zero leather accessories"],
    "improvements": ["Software pairing restricts DIY display repairs"]
  },
  {
    "id": "apple-iphone-15",
    "name": "Apple iPhone 15 (128GB, Pastel Pink)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 71999,
    "score": 81.0,
    "carbon": 61.0,
    "conv_carb": 82.0,
    "water": 1520,
    "lifespan": 5.0,
    "sub": [76, 84, 86, 81, 92, 70, 82],
    "explanation": "Color-infused back glass with 75% recycled aluminium frame and 100% recycled copper foil.",
    "mats": [{"name": "Recycled Aluminium", "percentage": 42, "isRecycled": True}, {"name": "Bio-silicate Glass", "percentage": 30, "isRecycled": False}, {"name": "Copper & Lithium", "percentage": 28, "isRecycled": False}],
    "pack": "100% plastic-free compact box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco standard"}],
    "strengths": ["USB-C universally compatible connector cuts e-waste", "Long 5+ year iOS software update lifespan"],
    "improvements": ["Battery glued with strong adhesive strips"]
  },
  {
    "id": "apple-iphone-14",
    "name": "Apple iPhone 14 (128GB, Midnight Blue)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 58999,
    "score": 78.0,
    "carbon": 61.0,
    "conv_carb": 82.0,
    "water": 1520,
    "lifespan": 5.0,
    "sub": [75, 80, 84, 78, 90, 68, 80],
    "explanation": "Removable back glass allows cheaper independent repairs than previous generation.",
    "mats": [{"name": "Aerospace Aluminium", "percentage": 40, "isRecycled": True}, {"name": "Ceramic Glass", "percentage": 35, "isRecycled": False}, {"name": "Internal Electronics", "percentage": 25, "isRecycled": False}],
    "pack": "FSC-certified paper packaging",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco verified"}],
    "strengths": ["Manufactured with 100% certified clean supplier energy", "Long update cycle"],
    "improvements": ["Lightning port legacy cable redundancy"]
  },
  {
    "id": "apple-iphone-13",
    "name": "Apple iPhone 13 (128GB, Starlight)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 49999,
    "score": 76.5,
    "carbon": 64.0,
    "conv_carb": 80.0,
    "water": 1580,
    "lifespan": 4.5,
    "sub": [74, 78, 83, 76, 88, 66, 80],
    "explanation": "Upcycled plastic water bottles used in internal antenna lines with 100% recycled rare earth magnets.",
    "mats": [{"name": "Aluminium", "percentage": 42, "isRecycled": True}, {"name": "Glass", "percentage": 33, "isRecycled": False}, {"name": "Electronics", "percentage": 25, "isRecycled": False}],
    "pack": "Plastic-wrap eliminated box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco standard"}],
    "strengths": ["High trade-in residual value supports second-hand reuse", "IP68 water resistance"],
    "improvements": ["Back glass replacement requires specialized laser machine"]
  },
  {
    "id": "samsung-galaxy-s24-ultra",
    "name": "Samsung Galaxy S24 Ultra 5G (256GB, Titanium Gray)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 129999,
    "score": 81.0,
    "carbon": 68.0,
    "conv_carb": 89.0,
    "water": 1720,
    "lifespan": 5.5,
    "sub": [76, 84, 87, 80, 88, 72, 80],
    "explanation": "50% recycled cobalt in battery and recycled ocean-bound plastics in speaker modules.",
    "mats": [{"name": "Titanium & Recycled Steel", "percentage": 35, "isRecycled": True}, {"name": "Gorilla Armor Glass", "percentage": 30, "isRecycled": False}, {"name": "Recycled Cobalt Battery", "percentage": 35, "isRecycled": True}],
    "pack": "100% recycled paper packaging box",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO Gold", "issuer": "UL", "verified": True, "description": "Lifecycle certification"}],
    "strengths": ["7 generations of Android OS and security updates", "Anti-reflective Gorilla Armor"],
    "improvements": ["High silicon fabrication carbon footprint"]
  },
  {
    "id": "samsung-galaxy-s24-plus",
    "name": "Samsung Galaxy S24+ 5G (256GB, Cobalt Violet)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 99999,
    "score": 80.5,
    "carbon": 62.0,
    "conv_carb": 84.0,
    "water": 1610,
    "lifespan": 5.0,
    "sub": [76, 83, 86, 80, 88, 72, 80],
    "explanation": "Uses recycled aluminium, glass, and ocean-bound plastics with 7-year OS commitment.",
    "mats": [{"name": "Armor Aluminium 2.0", "percentage": 38, "isRecycled": True}, {"name": "Recycled Glass", "percentage": 28, "isRecycled": True}, {"name": "Batteries & Circuits", "percentage": 34, "isRecycled": False}],
    "pack": "100% recycled box",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO", "issuer": "UL", "verified": True, "description": "Eco standard"}],
    "strengths": ["7 years of software updates extends device lifespan", "QHD+ Dynamic AMOLED LTPO panel"],
    "improvements": ["Fast charger sold separately"]
  },
  {
    "id": "samsung-galaxy-s24",
    "name": "Samsung Galaxy S24 5G (128GB, Amber Yellow)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 74999,
    "score": 81.5,
    "carbon": 56.0,
    "conv_carb": 78.0,
    "water": 1490,
    "lifespan": 5.0,
    "sub": [78, 84, 86, 81, 88, 73, 80],
    "explanation": "Compact 167g form factor consumes 15% fewer raw materials than phablet counterparts.",
    "mats": [{"name": "Armor Aluminium", "percentage": 40, "isRecycled": True}, {"name": "Recycled Glass", "percentage": 30, "isRecycled": True}, {"name": "Internal Electronics", "percentage": 30, "isRecycled": False}],
    "pack": "100% recycled paper box",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO", "issuer": "UL", "verified": True, "description": "Eco rating"}],
    "strengths": ["7 years of official Android OS upgrades", "Compact mass reduces logistics footprint"],
    "improvements": ["Thermal throttling under heavy prolonged 3D gaming"]
  },
  {
    "id": "samsung-galaxy-a55-5g",
    "name": "Samsung Galaxy A55 5G (128GB, Awesome Iceblue)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 39999,
    "score": 77.0,
    "carbon": 54.0,
    "conv_carb": 75.0,
    "water": 1420,
    "lifespan": 4.5,
    "sub": [76, 76, 82, 75, 86, 68, 78],
    "explanation": "First Galaxy A-series with metal frame made with 20% post-consumer recycled aluminium.",
    "mats": [{"name": "Recycled Aluminium Frame", "percentage": 35, "isRecycled": True}, {"name": "Gorilla Glass Victus+", "percentage": 35, "isRecycled": False}, {"name": "Electronics", "percentage": 30, "isRecycled": False}],
    "pack": "Recycled cardboard box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "Indian standard"}],
    "strengths": ["4 OS updates + 5 years security patches", "Samsung Knox Vault hardware security"],
    "improvements": ["No wall charger included in retail bundle"]
  },
  {
    "id": "samsung-galaxy-a54-5g",
    "name": "Samsung Galaxy A54 5G (128GB, Awesome Lime)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 33499,
    "score": 76.5,
    "carbon": 52.0,
    "conv_carb": 74.0,
    "water": 1380,
    "lifespan": 4.5,
    "sub": [76, 75, 80, 74, 85, 68, 78],
    "explanation": "Recycled glass back panel and post-consumer recycled plastic buttons.",
    "mats": [{"name": "PCR Plastics", "percentage": 22, "isRecycled": True}, {"name": "Recycled Glass", "percentage": 28, "isRecycled": True}, {"name": "Aluminium Traces", "percentage": 50, "isRecycled": False}],
    "pack": "Recycled Kraft box",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO", "issuer": "UL", "verified": True, "description": "Eco standard"}],
    "strengths": ["IP67 water resistance", "Bright 1000-nit Super AMOLED screen"],
    "improvements": ["Moderate bezel thickness"]
  },
  {
    "id": "samsung-galaxy-a35-5g",
    "name": "Samsung Galaxy A35 5G (128GB, Awesome Lilac)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 27999,
    "score": 75.0,
    "carbon": 50.0,
    "conv_carb": 71.0,
    "water": 1340,
    "lifespan": 4.0,
    "sub": [75, 73, 79, 73, 84, 67, 76],
    "explanation": "Equipped with Knox Matrix security and side key components made from discarded fishing nets.",
    "mats": [{"name": "Recycled Ocean Plastic", "percentage": 20, "isRecycled": True}, {"name": "Glass Back", "percentage": 35, "isRecycled": False}, {"name": "Electronics", "percentage": 45, "isRecycled": False}],
    "pack": "Minimal paper box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS", "verified": True, "description": "Quality assurance"}],
    "strengths": ["4 OS upgrades guaranteed", "Made in India in Noida mega-facility"],
    "improvements": ["Plastic side frame prone to scratches without case"]
  },
  {
    "id": "samsung-galaxy-m34-5g",
    "name": "Samsung Galaxy M34 5G (128GB, Prism Silver)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 15999,
    "score": 73.0,
    "carbon": 46.0,
    "conv_carb": 68.0,
    "water": 1250,
    "lifespan": 4.0,
    "sub": [74, 70, 76, 72, 80, 68, 72],
    "explanation": "6000mAh battery provides 2 full days of runtime, reducing charging cycle degradation.",
    "mats": [{"name": "Polycarbonate with PCR", "percentage": 45, "isRecycled": True}, {"name": "Display Glass", "percentage": 25, "isRecycled": False}, {"name": "Silicon", "percentage": 30, "isRecycled": False}],
    "pack": "Compact recycled box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS ISI", "issuer": "BIS", "verified": True, "description": "National standard"}],
    "strengths": ["Huge 6000mAh battery cuts recharge frequency", "4 OS updates in budget tier"],
    "improvements": ["Heavier 208g weight"]
  },
  {
    "id": "samsung-galaxy-f54-5g",
    "name": "Samsung Galaxy F54 5G (256GB, Meteor Blue)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 24999,
    "score": 74.0,
    "carbon": 49.0,
    "conv_carb": 70.0,
    "water": 1310,
    "lifespan": 4.0,
    "sub": [74, 72, 78, 73, 82, 67, 74],
    "explanation": "108MP camera with OIS and extended battery lifespan built at Samsung India facility.",
    "mats": [{"name": "Glossy Polycarbonate", "percentage": 42, "isRecycled": False}, {"name": "OLED Display", "percentage": 28, "isRecycled": False}, {"name": "Battery & Motherboard", "percentage": 30, "isRecycled": False}],
    "pack": "Soy-ink printed paper box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Safety compliance"}],
    "strengths": ["6000mAh battery with AI power management", "4 OS version upgrades"],
    "improvements": ["Plastic back panel attracts fingerprints"]
  },
  {
    "id": "oneplus-12",
    "name": "OnePlus 12 5G (256GB, Silky Black)",
    "brand": "OnePlus",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 64999,
    "score": 74.0,
    "carbon": 58.0,
    "conv_carb": 78.0,
    "water": 1480,
    "lifespan": 4.5,
    "sub": [72, 74, 82, 73, 76, 65, 74],
    "explanation": "Battery Health Engine preserves 80% battery capacity after 1,600 charging cycles (over 4 years).",
    "mats": [{"name": "Aluminium Frame (20% Recycled)", "percentage": 35, "isRecycled": True}, {"name": "Gorilla Glass Victus 2", "percentage": 30, "isRecycled": False}, {"name": "Lithium Cells", "percentage": 25, "isRecycled": False}, {"name": "Alloys", "percentage": 10, "isRecycled": False}],
    "pack": "Red paperboard box",
    "plastic_free": False,
    "certs": [{"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Chemical safety"}],
    "strengths": ["Battery Health Engine doubles industry standard battery cycle lifespan", "IP65 rated"],
    "improvements": ["Large wall charger brick increases bundle volume"]
  },
  {
    "id": "oneplus-12r",
    "name": "OnePlus 12R 5G (128GB, Cool Blue)",
    "brand": "OnePlus",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 39999,
    "score": 73.5,
    "carbon": 53.0,
    "conv_carb": 72.0,
    "water": 1390,
    "lifespan": 4.0,
    "sub": [73, 72, 80, 72, 75, 66, 72],
    "explanation": "5500mAh high capacity cell paired with power efficient LTPO 4.0 AMOLED screen.",
    "mats": [{"name": "Aluminium Alloy", "percentage": 38, "isRecycled": False}, {"name": "Gorilla Glass Victus 2", "percentage": 32, "isRecycled": False}, {"name": "Lithium Battery", "percentage": 30, "isRecycled": False}],
    "pack": "Cardboard gift box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "Quality standard"}],
    "strengths": ["LTPO 4.0 display scales down to 1Hz dynamically saving 30% display power", "Smooth software"],
    "improvements": ["Only 3 OS updates compared to Google/Samsung 7 years"]
  },
  {
    "id": "oneplus-nord-ce4",
    "name": "OnePlus Nord CE4 5G (128GB, Celadon Marble)",
    "brand": "OnePlus",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 24999,
    "score": 72.5,
    "carbon": 47.0,
    "conv_carb": 65.0,
    "water": 1290,
    "lifespan": 3.5,
    "sub": [73, 71, 76, 70, 75, 66, 70],
    "explanation": "100W SUPERVOOC charging with 4-year battery health guarantee and expandable microSD slot.",
    "mats": [{"name": "Polycarbonate", "percentage": 50, "isRecycled": False}, {"name": "Recycled Solder Tin", "percentage": 12, "isRecycled": True}, {"name": "Glass & Copper", "percentage": 38, "isRecycled": False}],
    "pack": "Compact paperboard box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Safety standard"}],
    "strengths": ["MicroSD card slot extends storage without phone replacement", "Long 5500mAh cell"],
    "improvements": ["Back plastic is not post-consumer recycled"]
  },
  {
    "id": "oneplus-nord-3",
    "name": "OnePlus Nord 3 5G (128GB, Misty Green)",
    "brand": "OnePlus",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 28999,
    "score": 73.0,
    "carbon": 49.0,
    "conv_carb": 68.0,
    "water": 1330,
    "lifespan": 3.5,
    "sub": [73, 72, 78, 71, 75, 65, 72],
    "explanation": "Corning Gorilla Glass 5 back cover with Alert Slider physical hardware toggle.",
    "mats": [{"name": "Glass Back", "percentage": 36, "isRecycled": False}, {"name": "Polycarbonate Frame", "percentage": 34, "isRecycled": False}, {"name": "Electronics", "percentage": 30, "isRecycled": False}],
    "pack": "Paper packaging",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Registered", "issuer": "BIS", "verified": True, "description": "National approval"}],
    "strengths": ["Flagship MediaTek Dimensity 9000 efficiency", "Alert slider hardware durability"],
    "improvements": ["Plastic frame prone to scuffs over time"]
  },
  {
    "id": "oneplus-open-foldable",
    "name": "OnePlus Open Foldable 5G (512GB, Emerald Dusk)",
    "brand": "OnePlus",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 139999,
    "score": 75.0,
    "carbon": 74.0,
    "conv_carb": 98.0,
    "water": 1850,
    "lifespan": 4.5,
    "sub": [71, 76, 82, 74, 78, 62, 75],
    "explanation": "Proprietary Flexion Hinge made from cobalt molybdenum alloy and titanium reduces parts from 100 to 69.",
    "mats": [{"name": "Titanium & Cobalt Alloy Hinge", "percentage": 35, "isRecycled": False}, {"name": "Ultra Thin Glass & Ceramic Guard", "percentage": 30, "isRecycled": False}, {"name": "Dual Batteries", "percentage": 35, "isRecycled": False}],
    "pack": "Luxury rigid presentation box",
    "plastic_free": False,
    "certs": [{"id": "tuv-rheinland", "name": "TÜV Rheinland 1,000,000 Folds", "issuer": "TÜV", "verified": True, "description": "Extreme durability testing"}],
    "strengths": ["Tested for 1,000,000 fold operations (10 years of typical usage)", "Streamlined hinge has fewer friction wear components"],
    "improvements": ["Inner flexible display screen replacement is very costly"]
  },
  {
    "id": "nothing-phone-2a",
    "name": "Nothing Phone (2a) 5G (128GB, Milk White)",
    "brand": "Nothing",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 23999,
    "score": 84.0,
    "carbon": 52.0,
    "conv_carb": 78.0,
    "water": 1320,
    "lifespan": 4.5,
    "sub": [82, 86, 83, 84, 92, 75, 82],
    "explanation": "52 kg CO₂e lowest lifecycle footprint in category with 100% recycled aluminium midframe and 100% renewable assembly.",
    "mats": [{"name": "100% Recycled Aluminium Midframe", "percentage": 32, "isRecycled": True}, {"name": "Recycled Tin Solder", "percentage": 18, "isRecycled": True}, {"name": "50% Bio-based & PCR Plastics", "percentage": 24, "isRecycled": True}, {"name": "Recycled Steel Scrap", "percentage": 12, "isRecycled": True}, {"name": "Gorilla Glass 5", "percentage": 14, "isRecycled": False}],
    "pack": "Zero-plastic biodegradable unbleached pulp box",
    "plastic_free": True,
    "certs": [{"id": "carbon-trust", "name": "Carbon Trust Audited", "issuer": "Carbon Trust", "verified": True, "description": "Certified carbon lifecycle"}],
    "strengths": ["Lowest audited carbon footprint in segment (52 kg CO₂e)", "Zero plastic in retail packaging", "100% renewable electricity used in final assembly"],
    "improvements": ["Rear transparent plastic back cover can attract fine dust without pouch"]
  },
  {
    "id": "nothing-phone-2",
    "name": "Nothing Phone (2) Flagship 5G (256GB, Dark Grey)",
    "brand": "Nothing",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 36999,
    "score": 83.5,
    "carbon": 53.4,
    "conv_carb": 79.0,
    "water": 1360,
    "lifespan": 4.5,
    "sub": [81, 85, 84, 82, 92, 74, 82],
    "explanation": "SGS-certified lifecycle with 100% recycled aluminium frame and 9 circuit boards using 100% recycled tin.",
    "mats": [{"name": "100% Recycled Aluminium Frame", "percentage": 35, "isRecycled": True}, {"name": "Recycled Tin & Copper", "percentage": 16, "isRecycled": True}, {"name": "PCR Plastics", "percentage": 22, "isRecycled": True}, {"name": "Curved Gorilla Glass", "percentage": 27, "isRecycled": False}],
    "pack": "FSC-certified plastic-free paper carton",
    "plastic_free": True,
    "certs": [{"id": "carbon-trust", "name": "Carbon Trust Certified", "issuer": "Carbon Trust", "verified": True, "description": "Certified product footprint"}],
    "strengths": ["Transparent design reveals sustainability craftsmanship", "Plastic-free tape-free packaging"],
    "improvements": ["Glyph LED matrix adds slight electronic component complexity"]
  },
  {
    "id": "cmf-phone-1",
    "name": "CMF Phone 1 by Nothing (128GB, Light Green)",
    "brand": "Nothing",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 15999,
    "score": 85.5,
    "carbon": 44.0,
    "conv_carb": 72.0,
    "water": 1180,
    "lifespan": 4.5,
    "sub": [85, 87, 85, 86, 92, 92, 80],
    "explanation": "Revolutionary modular removable back case with standard screwdriver, enabling easy case swapping and battery access.",
    "mats": [{"name": "Removable PCR Polycarbonate Shell", "percentage": 45, "isRecycled": True}, {"name": "Recycled Internal Chassis", "percentage": 25, "isRecycled": True}, {"name": "Electronics & AMOLED", "percentage": 30, "isRecycled": False}],
    "pack": "Ultra-slim plastic-free carton",
    "plastic_free": True,
    "certs": [{"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Lead-free"}],
    "strengths": ["User-removable back case enables DIY personalization & repair", "Modular accessory attachment system", "Plastic-free packaging"],
    "improvements": ["No NFC hardware chip onboard"]
  },
  {
    "id": "xiaomi-14",
    "name": "Xiaomi 14 5G Leica Flagship (512GB, Jade Green)",
    "brand": "Xiaomi",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 69999,
    "score": 73.5,
    "carbon": 62.0,
    "conv_carb": 82.0,
    "water": 1540,
    "lifespan": 4.5,
    "sub": [72, 74, 80, 73, 75, 66, 72],
    "explanation": "High energy density silicon-carbon battery pack reduces raw materials weight while retaining 4610mAh.",
    "mats": [{"name": "Aluminium (15% Recycled)", "percentage": 34, "isRecycled": True}, {"name": "Bio-ceramic Skin / Glass", "percentage": 26, "isRecycled": False}, {"name": "Silicon-Carbon Cells", "percentage": 24, "isRecycled": False}, {"name": "Optics", "percentage": 16, "isRecycled": False}],
    "pack": "Rigid white board",
    "plastic_free": False,
    "certs": [{"id": "rohs", "name": "RoHS Compliant", "issuer": "SGS", "verified": True, "description": "Hazardous free"}],
    "strengths": ["Compact palm-friendly 6.36-inch form factor", "IP68 water sealing"],
    "improvements": ["High air freight transit emissions from overseas assembly"]
  },
  {
    "id": "redmi-note-13-pro-plus",
    "name": "Redmi Note 13 Pro+ 5G (256GB, Fusion Purple)",
    "brand": "Redmi",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 31999,
    "score": 71.0,
    "carbon": 54.0,
    "conv_carb": 72.0,
    "water": 1390,
    "lifespan": 3.5,
    "sub": [70, 71, 77, 71, 74, 64, 68],
    "explanation": "Curved AMOLED with vegan leather option, assembled locally in Noida under 'Make in India'.",
    "mats": [{"name": "Vegan Bio-Leather / Glass", "percentage": 30, "isRecycled": False}, {"name": "Polycarbonate Inner", "percentage": 40, "isRecycled": False}, {"name": "Electronics", "percentage": 30, "isRecycled": False}],
    "pack": "Cardboard with soy ink",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Registered", "issuer": "BIS India", "verified": True, "description": "National approval"}],
    "strengths": ["Local domestic assembly lowers shipping miles", "IP68 water protection"],
    "improvements": ["Proprietary 120W charging brick contributes to e-waste"]
  },
  {
    "id": "redmi-note-13-5g",
    "name": "Redmi Note 13 5G (128GB, Stealth Black)",
    "brand": "Redmi",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 16999,
    "score": 72.0,
    "carbon": 46.0,
    "conv_carb": 66.0,
    "water": 1260,
    "lifespan": 3.5,
    "sub": [72, 71, 76, 71, 75, 65, 70],
    "explanation": "Slim 7.6mm lightweight profile using reduced polymer chassis mass.",
    "mats": [{"name": "Polycarbonate Blend", "percentage": 48, "isRecycled": False}, {"name": "Display Glass", "percentage": 27, "isRecycled": False}, {"name": "Circuits", "percentage": 25, "isRecycled": False}],
    "pack": "Standard carton",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS ISI", "issuer": "BIS", "verified": True, "description": "Standard compliance"}],
    "strengths": ["Extremely lightweight 173.5g reduces shipping footprint", "Slim bezels"],
    "improvements": ["Plastic back prone to scuffing"]
  },
  {
    "id": "redmi-13c-5g",
    "name": "Redmi 13C 5G (128GB, Starlight Silver)",
    "brand": "Redmi",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 10499,
    "score": 71.0,
    "carbon": 43.0,
    "conv_carb": 62.0,
    "water": 1190,
    "lifespan": 3.0,
    "sub": [71, 69, 74, 70, 75, 66, 68],
    "explanation": "Mass-market 5G accessibility made in India with 5000mAh battery.",
    "mats": [{"name": "Molded ABS/PC", "percentage": 50, "isRecycled": False}, {"name": "Gorilla Glass", "percentage": 25, "isRecycled": False}, {"name": "Battery & Motherboard", "percentage": 25, "isRecycled": False}],
    "pack": "Printed carton",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "Indian standard"}],
    "strengths": ["Democratizes 5G connectivity under ₹11,000", "Gorilla Glass screen"],
    "improvements": ["Shorter software upgrade schedule"]
  },
  {
    "id": "google-pixel-8a",
    "name": "Google Pixel 8a 5G (128GB, Bay Blue)",
    "brand": "Google",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 49999,
    "score": 86.0,
    "carbon": 47.0,
    "conv_carb": 76.0,
    "water": 1210,
    "lifespan": 7.0,
    "sub": [84, 88, 86, 85, 95, 78, 88],
    "explanation": "100% recycled aluminium enclosure and 76% recycled plastic in back cover, backed by 7 years of full OS updates.",
    "mats": [{"name": "100% Recycled Aluminium", "percentage": 40, "isRecycled": True}, {"name": "76% Recycled Plastic Back", "percentage": 24, "isRecycled": True}, {"name": "Recycled Tin Solder", "percentage": 10, "isRecycled": True}, {"name": "Gorilla Glass 3", "percentage": 26, "isRecycled": False}],
    "pack": "100% plastic-free unbleached paperboard box",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO Gold", "issuer": "UL", "verified": True, "description": "Gold eco standard"}],
    "strengths": ["7 full years of Android OS updates & security patches", "Back cover made with 76% recycled plastic", "100% plastic-free packaging"],
    "improvements": ["Charging speed capped at 18W"]
  },
  {
    "id": "google-pixel-8-pro",
    "name": "Google Pixel 8 Pro (128GB, Obsidian)",
    "brand": "Google",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 93999,
    "score": 85.0,
    "carbon": 61.0,
    "conv_carb": 88.0,
    "water": 1510,
    "lifespan": 7.0,
    "sub": [83, 87, 86, 84, 95, 76, 88],
    "explanation": "100% recycled aluminium in frame and 7-year software guarantee eliminates planned obsolescence.",
    "mats": [{"name": "100% Recycled Aluminium Frame", "percentage": 42, "isRecycled": True}, {"name": "Recycled Rare Earths & Tin", "percentage": 16, "isRecycled": True}, {"name": "Gorilla Glass Victus 2", "percentage": 42, "isRecycled": False}],
    "pack": "100% plastic-free packaging",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO Gold", "issuer": "UL", "verified": True, "description": "Eco rating"}],
    "strengths": ["7 years of software support", "Official genuine iFixit replacement parts partnership"],
    "improvements": ["Glass camera visor difficult to separate in recycling"]
  },
  {
    "id": "google-pixel-7a",
    "name": "Google Pixel 7a (128GB, Sea Foam)",
    "brand": "Google",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 36999,
    "score": 83.0,
    "carbon": 49.0,
    "conv_carb": 75.0,
    "water": 1280,
    "lifespan": 5.0,
    "sub": [81, 85, 84, 83, 94, 74, 85],
    "explanation": "Aluminium enclosure made with 100% recycled content; plastic-free paper packaging.",
    "mats": [{"name": "Recycled Aluminium", "percentage": 38, "isRecycled": True}, {"name": "Recycled Plastic in Backplate", "percentage": 25, "isRecycled": True}, {"name": "Display Glass & Battery", "percentage": 37, "isRecycled": False}],
    "pack": "100% paper packaging",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO", "issuer": "UL", "verified": True, "description": "Eco certification"}],
    "strengths": ["Compact body", "Clean stock Android with 5 years security patches"],
    "improvements": ["Wireless charging efficiency produces slight thermal loss"]
  },
  {
    "id": "motorola-edge-50-pro",
    "name": "Motorola Edge 50 Pro 5G (256GB, Moonlight Pearl)",
    "brand": "Motorola",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 31999,
    "score": 81.0,
    "carbon": 49.0,
    "conv_carb": 75.0,
    "water": 1280,
    "lifespan": 4.0,
    "sub": [80, 82, 83, 81, 94, 70, 78],
    "explanation": "100% plastic-free packaging box printed with soy ink and fragranced with bio-sourced scent.",
    "mats": [{"name": "Italian Handcrafted Acetate", "percentage": 32, "isRecycled": False}, {"name": "100% Recycled Aluminium", "percentage": 30, "isRecycled": True}, {"name": "Recycled Solder Tin", "percentage": 12, "isRecycled": True}, {"name": "Glass & Electronics", "percentage": 26, "isRecycled": False}],
    "pack": "100% plastic-free eco box printed with soy ink",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified Box", "issuer": "FSC", "verified": True, "description": "Eco forestry"}],
    "strengths": ["100% plastic-free box with soy ink", "Pantone verified display"],
    "improvements": ["Curved glass edges susceptible to impact cracks"]
  },
  {
    "id": "motorola-edge-50-ultra",
    "name": "Motorola Edge 50 Ultra 5G (512GB, Nordic Wood)",
    "brand": "Motorola",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 54999,
    "score": 83.0,
    "carbon": 53.0,
    "conv_carb": 78.0,
    "water": 1340,
    "lifespan": 4.5,
    "sub": [82, 86, 84, 82, 94, 72, 80],
    "explanation": "Real sustainable FSC-certified natural wood back cover infused with wood aroma; plastic-free packaging.",
    "mats": [{"name": "FSC Certified Real Wood Back", "percentage": 35, "isRecycled": False, "isRenewable": True}, {"name": "Sandblasted Aluminium Frame", "percentage": 32, "isRecycled": True}, {"name": "Electronics & Battery", "percentage": 33, "isRecycled": False}],
    "pack": "100% plastic-free eco box",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified Wood", "issuer": "FSC", "verified": True, "description": "Sustainably harvested wood"}],
    "strengths": ["Real bio-based FSC certified wood back plate replaces petrochemical plastics", "IP68 water resistance"],
    "improvements": ["Natural wood finish requires gentle cleaning care"]
  },
  {
    "id": "moto-g84-5g",
    "name": "Moto G84 5G (256GB, Viva Magenta)",
    "brand": "Motorola",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 17999,
    "score": 74.0,
    "carbon": 45.0,
    "conv_carb": 66.0,
    "water": 1240,
    "lifespan": 3.5,
    "sub": [74, 73, 77, 72, 86, 68, 72],
    "explanation": "Pantone Color of the Year vegan leather back with clean near-stock Android software.",
    "mats": [{"name": "Vegan Bio-Leather", "percentage": 34, "isRecycled": False}, {"name": "Polycarbonate Inner", "percentage": 36, "isRecycled": False}, {"name": "Circuits", "percentage": 30, "isRecycled": False}],
    "pack": "Soy ink printed paper box",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "Safety standard"}],
    "strengths": ["Sub-170g lightweight body cuts transit carbon", "OLED display in budget segment"],
    "improvements": ["Only 1 major Android OS upgrade"]
  },
  {
    "id": "realme-12-pro-plus",
    "name": "Realme 12 Pro+ 5G (256GB, Submarine Blue)",
    "brand": "Realme",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 29999,
    "score": 71.5,
    "carbon": 52.0,
    "conv_carb": 73.0,
    "water": 1360,
    "lifespan": 3.5,
    "sub": [71, 72, 78, 70, 74, 63, 69],
    "explanation": "Luxury watch dial inspired design with vegan leather rear panel.",
    "mats": [{"name": "Vegan Leather", "percentage": 28, "isRecycled": False}, {"name": "Plastic & Alloy", "percentage": 42, "isRecycled": False}, {"name": "Optics & PCB", "percentage": 30, "isRecycled": False}],
    "pack": "Yellow cardboard box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS ISI", "issuer": "BIS", "verified": True, "description": "National approval"}],
    "strengths": ["Periscope telephoto zoom in sub-₹30k", "5000mAh battery"],
    "improvements": ["Software upgrade commitments are relatively brief"]
  },
  {
    "id": "realme-narzo-70-pro",
    "name": "Realme Narzo 70 Pro 5G (128GB, Glass Green)",
    "brand": "Realme",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 18999,
    "score": 72.0,
    "carbon": 47.0,
    "conv_carb": 67.0,
    "water": 1280,
    "lifespan": 3.5,
    "sub": [72, 71, 76, 71, 75, 65, 70],
    "explanation": "Horizon glass design back with Sony IMX890 OIS camera sensor.",
    "mats": [{"name": "Glass Back", "percentage": 38, "isRecycled": False}, {"name": "Plastic Frame", "percentage": 32, "isRecycled": False}, {"name": "Electronics", "percentage": 30, "isRecycled": False}],
    "pack": "Cardboard box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Certified", "issuer": "BIS", "verified": True, "description": "Safety standard"}],
    "strengths": ["Air gesture control minimizes screen touching", "Flagship Sony camera sensor"],
    "improvements": ["Bloatware apps pre-installed requiring manual removal"]
  },
  {
    "id": "vivo-v30-pro-5g",
    "name": "Vivo V30 Pro 5G ZEISS Optics (512GB, Andaman Blue)",
    "brand": "Vivo",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 41999,
    "score": 72.5,
    "carbon": 53.0,
    "conv_carb": 74.0,
    "water": 1390,
    "lifespan": 3.5,
    "sub": [72, 72, 78, 71, 76, 64, 71],
    "explanation": "Ultra-slim 7.45mm body with 5000mAh high-density battery.",
    "mats": [{"name": "Ag Satin Glass", "percentage": 35, "isRecycled": False}, {"name": "Aluminium Alloy", "percentage": 30, "isRecycled": False}, {"name": "Circuits", "percentage": 35, "isRecycled": False}],
    "pack": "Cardboard gift box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "National approval"}],
    "strengths": ["ZEISS optical color science and portrait tuning", "Slim design"],
    "improvements": ["Curved display screen edge fragile against corner impacts"]
  },
  {
    "id": "iqoo-12-5g",
    "name": "iQOO 12 5G (256GB, Legend White BMW Edition)",
    "brand": "iQOO",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 52999,
    "score": 73.0,
    "carbon": 59.0,
    "conv_carb": 80.0,
    "water": 1490,
    "lifespan": 4.0,
    "sub": [71, 73, 81, 72, 76, 66, 72],
    "explanation": "Snapdragon 8 Gen 3 flagship with vapor chamber cooling and graphite thermal sheets.",
    "mats": [{"name": "Fluorite AG Glass", "percentage": 36, "isRecycled": False}, {"name": "Aluminium Midframe", "percentage": 34, "isRecycled": False}, {"name": "Vapor Chamber & Circuits", "percentage": 30, "isRecycled": False}],
    "pack": "Luxury carton",
    "plastic_free": False,
    "certs": [{"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Chemical safety"}],
    "strengths": ["Large 6010mm² vapor chamber prolongs battery and chip thermal lifespan", "High refresh LTPO screen"],
    "improvements": ["120W flash charger brick adds electronic mass"]
  },
  {
    "id": "poco-x6-pro-5g",
    "name": "POCO X6 Pro 5G (256GB, Racing Yellow)",
    "brand": "POCO",
    "cat": "Electronics",
    "subcat": "Smartphones",
    "price": 24999,
    "score": 72.0,
    "carbon": 48.0,
    "conv_carb": 68.0,
    "water": 1310,
    "lifespan": 3.5,
    "sub": [72, 70, 77, 71, 75, 66, 70],
    "explanation": "Eco-leather yellow back panel with MediaTek Dimensity 8300-Ultra processor.",
    "mats": [{"name": "Vegan Eco-Leather", "percentage": 32, "isRecycled": False}, {"name": "Polycarbonate", "percentage": 38, "isRecycled": False}, {"name": "Display & Battery", "percentage": 30, "isRecycled": False}],
    "pack": "Black and yellow carton",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "National approval"}],
    "strengths": ["Dimensity 8300-Ultra delivers exceptional performance per watt", "Gorilla Glass 5 display"],
    "improvements": ["Plastic side rails wear down without cover"]
  },

  # --- LAPTOPS (16 items) ---
  {
    "id": "apple-macbook-air-m3",
    "name": "Apple MacBook Air 13-inch (M3, 8GB RAM, 256GB SSD, Starlight)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 104990,
    "score": 89.0,
    "carbon": 135.0,
    "conv_carb": 285.0,
    "water": 3200,
    "lifespan": 7.0,
    "sub": [88, 92, 94, 89, 96, 68, 92],
    "explanation": "Made with over 50% recycled materials including 100% recycled aluminium enclosure and 100% recycled cobalt in battery.",
    "mats": [{"name": "100% Recycled Aluminium Enclosure", "percentage": 50, "isRecycled": True}, {"name": "Recycled Rare Earth Magnets", "percentage": 15, "isRecycled": True}, {"name": "Recycled Cobalt Battery", "percentage": 12, "isRecycled": True}, {"name": "Retina Display & Glass", "percentage": 23, "isRecycled": False}],
    "pack": "100% fiber-based plastic-free retail box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Top environmental rating"}, {"id": "energy-star", "name": "ENERGY STAR 8.0", "issuer": "EPA", "verified": True, "description": "High energy efficiency"}],
    "strengths": ["Over 50% total recycled materials by mass", "Fanless zero-moving-parts silent operation", "18-hour battery cycle"],
    "improvements": ["Unified memory is non-upgradable after purchase"]
  },
  {
    "id": "apple-macbook-air-m2-15",
    "name": "Apple MacBook Air 15-inch (M2, 8GB, 256GB SSD, Midnight)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 119900,
    "score": 87.5,
    "carbon": 142.0,
    "conv_carb": 290.0,
    "water": 3350,
    "lifespan": 7.0,
    "sub": [87, 90, 93, 88, 96, 68, 92],
    "explanation": "100% recycled aluminium unibody enclosure with 100% recycled gold in main logic board plating.",
    "mats": [{"name": "100% Recycled Aluminium", "percentage": 52, "isRecycled": True}, {"name": "Recycled Tin Solder & Gold", "percentage": 14, "isRecycled": True}, {"name": "Liquid Retina Panel", "percentage": 34, "isRecycled": False}],
    "pack": "100% fiber box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco standard"}],
    "strengths": ["Thin 11.5mm chassis with fanless reliability", "100% recycled rare earth elements across all magnets"],
    "improvements": ["Midnight color finish shows minor finger oil scuffs"]
  },
  {
    "id": "apple-macbook-pro-14-m3",
    "name": "Apple MacBook Pro 14-inch (M3 Pro, 18GB, 512GB, Space Black)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 199900,
    "score": 87.5,
    "carbon": 162.0,
    "conv_carb": 340.0,
    "water": 3600,
    "lifespan": 7.5,
    "sub": [86, 90, 95, 88, 95, 67, 92],
    "explanation": "Breakthrough anodization seal reduces finger smudge wear, built with 100% recycled aluminium and clean energy.",
    "mats": [{"name": "100% Recycled Aluminium", "percentage": 52, "isRecycled": True}, {"name": "Recycled Rare Earths & Gold", "percentage": 18, "isRecycled": True}, {"name": "Mini-LED XDR Display", "percentage": 30, "isRecycled": False}],
    "pack": "100% fiber packaging",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Top rating"}],
    "strengths": ["M3 Pro architecture cuts energy draw by up to 50% vs x86 workstation laptops", "Long lifespan"],
    "improvements": ["Internal chassis screws require pentalobe screwdriver"]
  },
  {
    "id": "apple-macbook-pro-16-m3-max",
    "name": "Apple MacBook Pro 16-inch (M3 Max, 36GB, 1TB, Silver)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 349900,
    "score": 86.0,
    "carbon": 210.0,
    "conv_carb": 420.0,
    "water": 4100,
    "lifespan": 8.0,
    "sub": [84, 89, 95, 87, 95, 66, 92],
    "explanation": "Workstation compute efficiency delivers massive render workflows on battery power with zero thermal degradation.",
    "mats": [{"name": "Recycled Aluminium", "percentage": 54, "isRecycled": True}, {"name": "100% Recycled Cobalt & Tin", "percentage": 16, "isRecycled": True}, {"name": "Display & Fans", "percentage": 30, "isRecycled": False}],
    "pack": "100% fiber packaging",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco standard"}],
    "strengths": ["Class-leading 22-hour battery life eliminates constant wall outlet draw", "100Wh battery"],
    "improvements": ["High initial financial investment"]
  },
  {
    "id": "lenovo-thinkpad-l14-gen4",
    "name": "Lenovo ThinkPad L14 Gen 4 (AMD Ryzen 5 Pro, 16GB, 512GB)",
    "brand": "Lenovo",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 68500,
    "score": 86.5,
    "carbon": 155.0,
    "conv_carb": 290.0,
    "water": 3100,
    "lifespan": 6.5,
    "sub": [84, 86, 95, 88, 92, 94, 90],
    "explanation": "User-replaceable SO-DIMM RAM slots, M.2 SSD, and modular keyboard with 50% PCR plastic battery frame.",
    "mats": [{"name": "50% PCR Plastic in Battery Frame", "percentage": 25, "isRecycled": True}, {"name": "90% Recycled Magnesium Keyboard Frame", "percentage": 35, "isRecycled": True}, {"name": "Motherboard & Cooling", "percentage": 40, "isRecycled": False}],
    "pack": "FSC-certified box with 90% recycled cushioning",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold Climate+", "issuer": "GEC", "verified": True, "description": "Climate verified"}, {"id": "tco-gen9", "name": "TCO Certified Gen 9", "issuer": "TCO", "verified": True, "description": "Responsible supply chain"}],
    "strengths": ["Exceptional 9/10 DIY repairability with standard Philips screws", "MIL-STD-810H ruggedness"],
    "improvements": ["Display bezel uses non-recycled ABS"]
  },
  {
    "id": "lenovo-thinkpad-t14s-gen4",
    "name": "Lenovo ThinkPad T14s Gen 4 (Intel Core i7, 16GB, 512GB SSD)",
    "brand": "Lenovo",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 109990,
    "score": 85.0,
    "carbon": 160.0,
    "conv_carb": 295.0,
    "water": 3200,
    "lifespan": 6.0,
    "sub": [83, 85, 94, 87, 92, 86, 90],
    "explanation": "Carbon fiber top cover with 90% recycled magnesium D-cover and plastic-free bamboo pulp packaging.",
    "mats": [{"name": "90% Recycled Magnesium Base", "percentage": 38, "isRecycled": True}, {"name": "Carbon Fiber Hybrid Top", "percentage": 28, "isRecycled": False}, {"name": "Motherboard & Panel", "percentage": 34, "isRecycled": False}],
    "pack": "Plastic-free bamboo and sugarcane packaging",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Sustainability leader"}],
    "strengths": ["Carbon neutral offset service included at factory", "Long keyboard lifespan"],
    "improvements": ["Soldered LPDDR5X RAM limits future upgrades"]
  },
  {
    "id": "lenovo-yoga-slim-7x",
    "name": "Lenovo Yoga Slim 7x Copilot+ PC (Snapdragon X Elite, 16GB, 1TB)",
    "brand": "Lenovo",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 137990,
    "score": 85.0,
    "carbon": 142.0,
    "conv_carb": 280.0,
    "water": 2950,
    "lifespan": 6.0,
    "sub": [85, 84, 90, 86, 94, 74, 88],
    "explanation": "Snapdragon X Elite ARM architecture delivers 60% lower power draw, housed in recycled aluminium unibody.",
    "mats": [{"name": "Recycled Aluminium Lid & Base", "percentage": 48, "isRecycled": True}, {"name": "OLED Panel", "percentage": 28, "isRecycled": False}, {"name": "Internal Battery", "percentage": 24, "isRecycled": False}],
    "pack": "Plastic-free bamboo box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco rating"}],
    "strengths": ["ARM chip runs cool without fan throttling", "Zero plastic retail box"],
    "improvements": ["ARM Windows application emulation overhead on legacy software"]
  },
  {
    "id": "lenovo-ideapad-slim-5-14",
    "name": "Lenovo IdeaPad Slim 5 14-inch (AMD Ryzen 7, 16GB, 512GB SSD)",
    "brand": "Lenovo",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 62990,
    "score": 81.0,
    "carbon": 172.0,
    "conv_carb": 290.0,
    "water": 3300,
    "lifespan": 5.0,
    "sub": [79, 81, 85, 82, 88, 80, 84],
    "explanation": "Military-grade certified thin-and-light laptop with 90% recycled packaging cushion.",
    "mats": [{"name": "Aluminium Top", "percentage": 35, "isRecycled": False}, {"name": "PC-ABS Base (30% PCR)", "percentage": 35, "isRecycled": True}, {"name": "Electronics & Battery", "percentage": 30, "isRecycled": False}],
    "pack": "Recycled cardboard box",
    "plastic_free": True,
    "certs": [{"id": "energy-star", "name": "ENERGY STAR", "issuer": "EPA", "verified": True, "description": "Power conservation"}],
    "strengths": ["Rapid Charge Boost gives 2 hours in 15 minutes", "Physical webcam privacy shutter"],
    "improvements": ["Display brightness capped at 300 nits"]
  },
  {
    "id": "hp-pavilion-aero-13",
    "name": "HP Pavilion Aero 13 (AMD Ryzen 7, 16GB, 512GB SSD, Ultra-light 970g)",
    "brand": "HP",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 72999,
    "score": 84.5,
    "carbon": 148.0,
    "conv_carb": 275.0,
    "water": 2900,
    "lifespan": 5.5,
    "sub": [83, 86, 85, 85, 92, 80, 88],
    "explanation": "Sub-1kg magnesium-aluminium body with ocean-bound plastic in speaker enclosure and bezel.",
    "mats": [{"name": "Recycled Magnesium Alloy", "percentage": 40, "isRecycled": True}, {"name": "Ocean-Bound Plastics", "percentage": 22, "isRecycled": True}, {"name": "PCR Keycaps", "percentage": 18, "isRecycled": True}, {"name": "Panel", "percentage": 20, "isRecycled": False}],
    "pack": "100% molded pulp box with zero foam",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco rating"}],
    "strengths": ["Lightweight 970g mass cuts air logistics carbon", "Ocean-bound plastics diverted from waterways"],
    "improvements": ["Thin magnesium alloy can flex under concentrated weight"]
  },
  {
    "id": "hp-envy-x360-14",
    "name": "HP Envy x360 2-in-1 Laptop 14 (Intel Core Ultra 5, 16GB, 512GB)",
    "brand": "HP",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 84999,
    "score": 83.0,
    "carbon": 156.0,
    "conv_carb": 285.0,
    "water": 3100,
    "lifespan": 5.5,
    "sub": [82, 84, 88, 84, 90, 76, 86],
    "explanation": "Recycled aluminium chassis with 360-degree convertible hinge tested for 25,000 cycles.",
    "mats": [{"name": "Recycled Aluminium", "percentage": 45, "isRecycled": True}, {"name": "Ocean-bound Plastic Bezel", "percentage": 15, "isRecycled": True}, {"name": "Touch Digitizer & Circuits", "percentage": 40, "isRecycled": False}],
    "pack": "Molded pulp box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco verified"}],
    "strengths": ["Recycled metal body", "Durable hinge prevents early mechanical failure"],
    "improvements": ["Glass touch digitizer adds weight"]
  },
  {
    "id": "hp-spectre-x360-14",
    "name": "HP Spectre x360 14 (Intel Core Ultra 7, 32GB, 1TB OLED)",
    "brand": "HP",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 164999,
    "score": 85.5,
    "carbon": 150.0,
    "conv_carb": 290.0,
    "water": 3050,
    "lifespan": 6.5,
    "sub": [84, 87, 92, 86, 94, 76, 90],
    "explanation": "CNC-machined recycled aluminium with 50% post-consumer recycled plastic keycaps and 2.8K OLED.",
    "mats": [{"name": "Recycled CNC Aluminium", "percentage": 50, "isRecycled": True}, {"name": "Ocean Plastic Accents", "percentage": 14, "isRecycled": True}, {"name": "OLED Display & Hardware", "percentage": 36, "isRecycled": False}],
    "pack": "100% sustainably sourced packaging",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Gold standard"}],
    "strengths": ["9MP webcam with AI auto-framing reduces external peripheral needs", "Zero plastic packaging"],
    "improvements": ["OLED panel power draw is higher on white background web pages"]
  },
  {
    "id": "dell-inspiron-14-5430",
    "name": "Dell Inspiron 14 5430 (13th Gen Intel Core i5, 16GB, 512GB SSD)",
    "brand": "Dell",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 61490,
    "score": 82.0,
    "carbon": 165.0,
    "conv_carb": 295.0,
    "water": 3250,
    "lifespan": 5.0,
    "sub": [80, 83, 86, 84, 92, 82, 85],
    "explanation": "Features low-emission aluminium and 100% recycled or renewable packaging trays.",
    "mats": [{"name": "PCR Plastics", "percentage": 30, "isRecycled": True}, {"name": "Low-emission Aluminium", "percentage": 35, "isRecycled": True}, {"name": "Motherboard & Panel", "percentage": 35, "isRecycled": False}],
    "pack": "100% recycled packaging tray",
    "plastic_free": True,
    "certs": [{"id": "epeat-silver", "name": "EPEAT Silver", "issuer": "GEC", "verified": True, "description": "Eco rating"}],
    "strengths": ["Dell AR Assistant app provides step-by-step part replacement guide", "Sturdy hinges"],
    "improvements": ["Thermal fan requires annual cleaning in dusty rooms"]
  },
  {
    "id": "dell-xps-13-plus",
    "name": "Dell XPS 13 (Intel Core Ultra 7, 16GB, 1TB SSD, Platinum)",
    "brand": "Dell",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 144990,
    "score": 84.0,
    "carbon": 152.0,
    "conv_carb": 290.0,
    "water": 3100,
    "lifespan": 6.0,
    "sub": [82, 85, 92, 85, 94, 70, 88],
    "explanation": "CNC-machined hydro-smelted low-carbon aluminium with 100% ocean-bound plastic packaging trays.",
    "mats": [{"name": "Hydro-smelted Low-Carbon Aluminium", "percentage": 55, "isRecycled": True}, {"name": "Gorilla Glass 7", "percentage": 20, "isRecycled": False}, {"name": "Motherboard & Battery", "percentage": 25, "isRecycled": False}],
    "pack": "100% recycled ocean plastic tray + paper box",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Gold standard"}],
    "strengths": ["Hydro-powered smelter aluminium has 70% lower extraction footprint", "InfinityEdge display"],
    "improvements": ["Capacitive touch function row cannot be individually repaired"]
  },
  {
    "id": "asus-zenbook-s13-oled",
    "name": "ASUS Zenbook S 13 OLED (Intel Core Ultra 7, 16GB, 1TB, Basalt Grey)",
    "brand": "ASUS",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 124990,
    "score": 88.5,
    "carbon": 138.0,
    "conv_carb": 285.0,
    "water": 2850,
    "lifespan": 6.0,
    "sub": [87, 91, 89, 88, 95, 76, 92],
    "explanation": "Exclusive Plasma Ceramic Aluminium lid uses zero synthetic polymers or paints; packaging folds into laptop stand.",
    "mats": [{"name": "Plasma Ceramic Aluminium", "percentage": 48, "isRecycled": True}, {"name": "Recycled Magnesium Alloy Base", "percentage": 22, "isRecycled": True}, {"name": "Ocean Plastic in Speakers", "percentage": 12, "isRecycled": True}, {"name": "OLED Panel", "percentage": 18, "isRecycled": False}],
    "pack": "100% FSC Mix certified box that doubles as laptop stand",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Top circularity"}, {"id": "carbon-neutral", "name": "Carbon Neutral Product", "issuer": "SGS", "verified": True, "description": "Net zero audited"}],
    "strengths": ["Ceramic aluminium lid is 100% recyclable with pure water-bath process", "Packaging transforms into ergonomic desk stand"],
    "improvements": ["Thin 1cm chassis restricts internal port variety"]
  },
  {
    "id": "acer-aspire-vero-15",
    "name": "Acer Aspire Vero 15 Green PC (Core i5, 16GB, 512GB, Cobblestone Gray)",
    "brand": "Acer",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 54990,
    "score": 87.0,
    "carbon": 140.0,
    "conv_carb": 285.0,
    "water": 2900,
    "lifespan": 6.0,
    "sub": [86, 90, 88, 88, 95, 92, 88],
    "explanation": "Chassis made with 40% post-consumer recycled plastic with zero paint and standard Philips screws for full DIY repair.",
    "mats": [{"name": "Post-Consumer Recycled Plastics (PCR)", "percentage": 40, "isRecycled": True}, {"name": "OceanGlass Touchpad", "percentage": 10, "isRecycled": True}, {"name": "Motherboard & Panel", "percentage": 50, "isRecycled": False}],
    "pack": "100% recycled paper packaging with reusable internal dividers",
    "plastic_free": True,
    "certs": [{"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Top circular PC"}],
    "strengths": ["40% PCR plastic body cuts CO2 emissions by 30%", "Standard Philips screws allow easy battery and RAM upgrades", "Paint-free speckled casing"],
    "improvements": ["Slightly thicker 17.9mm profile"]
  },
  {
    "id": "acer-swift-go-14",
    "name": "Acer Swift Go 14 OLED (Intel Core Ultra 5, 16GB, 512GB)",
    "brand": "Acer",
    "cat": "Electronics",
    "subcat": "Laptops",
    "price": 69990,
    "score": 81.5,
    "carbon": 168.0,
    "conv_carb": 295.0,
    "water": 3200,
    "lifespan": 5.0,
    "sub": [79, 82, 84, 83, 88, 78, 82],
    "explanation": "Features OceanGlass touchpad made from 100% ocean-bound plastic with PCR chassis components.",
    "mats": [{"name": "OceanGlass Touchpad", "percentage": 8, "isRecycled": True}, {"name": "PCR Plastics", "percentage": 28, "isRecycled": True}, {"name": "Aluminium Lid", "percentage": 34, "isRecycled": False}, {"name": "Electronics", "percentage": 30, "isRecycled": False}],
    "pack": "100% recyclable molded paper pulp",
    "plastic_free": True,
    "certs": [{"id": "epeat-silver", "name": "EPEAT Silver", "issuer": "GEC", "verified": True, "description": "Eco standard"}],
    "strengths": ["OceanGlass touchpad diverts coastal marine waste", "VeroSense eco power utility"],
    "improvements": ["Plastic base feels slightly more flexible than unibody"]
  },

  # --- AUDIO & HEADPHONES (15 items) ---
  {
    "id": "sony-wh-1000xm5",
    "name": "Sony WH-1000XM5 Wireless Noise Canceling Headphones (Silver)",
    "brand": "Sony",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 29990,
    "score": 85.5,
    "carbon": 28.0,
    "conv_carb": 52.0,
    "water": 890,
    "lifespan": 6.0,
    "sub": [84, 88, 90, 86, 96, 74, 88],
    "explanation": "Headband crafted from recycled automobile parts; 100% plastic-free Original Blended Material packaging.",
    "mats": [{"name": "Recycled Automobile Plastics", "percentage": 45, "isRecycled": True}, {"name": "Synthetic Soft Vegan Leather", "percentage": 25, "isRecycled": False}, {"name": "Carbon Composite Drivers", "percentage": 10, "isRecycled": False}, {"name": "Circuits & Battery", "percentage": 20, "isRecycled": False}],
    "pack": "Zero-plastic bamboo and sugarcane fiber packaging",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Responsible paper"}],
    "strengths": ["Packaging contains zero plastic from raw material to shelf", "Recycled plastic from discarded Japanese cars", "30h battery life"],
    "improvements": ["Non-foldable headband design takes more bag volume"]
  },
  {
    "id": "sony-wh-ch720n",
    "name": "Sony WH-CH720N Wireless Over-Ear ANC Headphones (Blue)",
    "brand": "Sony",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 9990,
    "score": 82.0,
    "carbon": 22.0,
    "conv_carb": 39.0,
    "water": 680,
    "lifespan": 5.0,
    "sub": [81, 84, 85, 83, 94, 72, 84],
    "explanation": "Weighs only 192g using recycled plastics; plastic-free retail packaging.",
    "mats": [{"name": "Recycled Polycarbonate", "percentage": 50, "isRecycled": True}, {"name": "Synthetic Ear Cushions", "percentage": 25, "isRecycled": False}, {"name": "Internal Electronics", "percentage": 25, "isRecycled": False}],
    "pack": "Zero-plastic paper pulp box",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Eco forestry"}],
    "strengths": ["Ultra-lightweight 192g build saves raw material resources", "35h battery run time"],
    "improvements": ["Yoke hinge made of plastic rather than metal"]
  },
  {
    "id": "sony-wf-c500",
    "name": "Sony WF-C500 Truly Wireless Bluetooth Earbuds (Green)",
    "brand": "Sony",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 4990,
    "score": 81.0,
    "carbon": 13.5,
    "conv_carb": 24.0,
    "water": 420,
    "lifespan": 4.0,
    "sub": [80, 83, 84, 81, 95, 60, 84],
    "explanation": "Zero plastic in individual packaging; body constructed from recycled plastic resins.",
    "mats": [{"name": "Recycled Plastics", "percentage": 55, "isRecycled": True}, {"name": "Micro Lithium Cells", "percentage": 20, "isRecycled": False}, {"name": "Neodymium Drivers", "percentage": 25, "isRecycled": False}],
    "pack": "Zero-plastic recycled paper pulp box",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified Paper", "issuer": "FSC", "verified": True, "description": "Sustainably managed paper"}],
    "strengths": ["Plastic-free packaging material", "Ergonomic surface match for secure fit"],
    "improvements": ["Case does not support wireless Qi charging"]
  },
  {
    "id": "sony-linkbuds-s-earth-blue",
    "name": "Sony LinkBuds S Noise Cancelling Earbuds (Earth Blue)",
    "brand": "Sony",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 13990,
    "score": 87.0,
    "carbon": 14.0,
    "conv_carb": 27.0,
    "water": 430,
    "lifespan": 4.5,
    "sub": [86, 92, 86, 88, 96, 64, 88],
    "explanation": "Body and case made from recycled factory water dispensers and water cooler bottles, creating unique marble pattern.",
    "mats": [{"name": "Recycled Water Cooler Bottles (PET/PC)", "percentage": 65, "isRecycled": True}, {"name": "Circuits & Micro Battery", "percentage": 20, "isRecycled": False}, {"name": "5mm Audio Drivers", "percentage": 15, "isRecycled": False}],
    "pack": "100% plastic-free packaging made from bamboo & sugarcane",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Eco forestry"}, {"id": "1pct", "name": "1% for the Planet Partner", "issuer": "1% for the Planet", "verified": True, "description": "Portion donated to ocean conservation"}],
    "strengths": ["Made directly from recycled office water dispenser bottles", "Each unit has a distinct marble texture pattern", "Zero plastic packaging"],
    "improvements": ["Earbud batteries non-replaceable"]
  },
  {
    "id": "jbl-flip-6",
    "name": "JBL Flip 6 Portable Waterproof Bluetooth Speaker (Forest Green)",
    "brand": "JBL",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 10999,
    "score": 83.0,
    "carbon": 24.0,
    "conv_carb": 42.0,
    "water": 710,
    "lifespan": 5.5,
    "sub": [82, 85, 92, 83, 92, 70, 84],
    "explanation": "Speaker grille fabric made from 100% recycled plastic bottles; packaged in FSC-certified soy-ink printed box.",
    "mats": [{"name": "100% Recycled PET Grille Fabric", "percentage": 48, "isRecycled": True}, {"name": "PCR Plastic Housing", "percentage": 22, "isRecycled": True}, {"name": "Battery & Drivers", "percentage": 30, "isRecycled": False}],
    "pack": "FSC-certified paper box with soy ink",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Eco paper"}],
    "strengths": ["IP67 waterproof and dustproof submersible casing", "Durable silicone end caps absorb shock"],
    "improvements": ["Battery glued inside chassis"]
  },
  {
    "id": "jbl-charge-5",
    "name": "JBL Charge 5 Portable Powerbank Speaker (Squad Camo)",
    "brand": "JBL",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 14999,
    "score": 82.5,
    "carbon": 32.0,
    "conv_carb": 56.0,
    "water": 880,
    "lifespan": 6.0,
    "sub": [81, 84, 93, 83, 90, 72, 84],
    "explanation": "Doubles as a 7500mAh emergency powerbank; fabric cover uses 90% recycled polyester.",
    "mats": [{"name": "Recycled Polyester Fabric", "percentage": 45, "isRecycled": True}, {"name": "7500mAh Lithium Cell", "percentage": 30, "isRecycled": False}, {"name": "Internal Frame", "percentage": 25, "isRecycled": False}],
    "pack": "Recyclable cardboard box",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Paper sustainability"}],
    "strengths": ["2-in-1 speaker and phone powerbank cuts duplicate hardware", "Rugged drop-tested bumpers"],
    "improvements": ["Heavier 960g weight"]
  },
  {
    "id": "jbl-tune-510bt",
    "name": "JBL Tune 510BT On-Ear Wireless Headphones (Pure Bass, Black)",
    "brand": "JBL",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 2999,
    "score": 75.0,
    "carbon": 18.0,
    "conv_carb": 30.0,
    "water": 520,
    "lifespan": 4.0,
    "sub": [74, 73, 78, 75, 85, 68, 74],
    "explanation": "40 hours of playtime from a single charge reduces electricity draw and battery cycling.",
    "mats": [{"name": "PCR Resin Blend", "percentage": 30, "isRecycled": True}, {"name": "ABS Polymer", "percentage": 40, "isRecycled": False}, {"name": "Drivers & Cushions", "percentage": 30, "isRecycled": False}],
    "pack": "Recyclable cardboard",
    "plastic_free": False,
    "certs": [{"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Lead-free"}],
    "strengths": ["Exceptional 40-hour battery life", "Foldable flat design"],
    "improvements": ["On-ear cushions cause ear fatigue in hot humid conditions"]
  },
  {
    "id": "boat-airdopes-141",
    "name": "boAt Airdopes 141 True Wireless Earbuds (42H Playtime, Bold Black)",
    "brand": "boAt",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 1299,
    "score": 68.0,
    "carbon": 14.5,
    "conv_carb": 19.0,
    "water": 380,
    "lifespan": 2.5,
    "sub": [69, 64, 70, 65, 74, 50, 62],
    "explanation": "Assembled domestically in India under 'Make in India' reducing international air shipping emissions.",
    "mats": [{"name": "ABS Plastic", "percentage": 65, "isRecycled": False}, {"name": "Lithium Polymer Battery", "percentage": 20, "isRecycled": False}, {"name": "Copper Drivers", "percentage": 15, "isRecycled": False}],
    "pack": "Cardboard box with paper tray",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Safety standard"}],
    "strengths": ["Made in India domestic manufacturing", "Affordable digital access"],
    "improvements": ["Ultrasonically glued casing cannot be repaired"]
  },
  {
    "id": "boat-rockerz-255-pro-plus",
    "name": "boAt Rockerz 255 Pro+ Bluetooth Neckband (40H Playtime, Teal Green)",
    "brand": "boAt",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 1499,
    "score": 71.0,
    "carbon": 12.0,
    "conv_carb": 18.0,
    "water": 320,
    "lifespan": 3.0,
    "sub": [72, 68, 76, 68, 75, 56, 66],
    "explanation": "IPX7 water resistance prevents sweat corrosion failures; ASAP fast charge provides 10h in 10 minutes.",
    "mats": [{"name": "Silicone Neckband", "percentage": 40, "isRecycled": False}, {"name": "ABS Controls", "percentage": 30, "isRecycled": False}, {"name": "Internal Wiring & Magnets", "percentage": 30, "isRecycled": False}],
    "pack": "Cardboard box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Registered", "issuer": "BIS", "verified": True, "description": "Safety compliance"}],
    "strengths": ["IPX7 water sealing prolongs outdoor lifespan", "Fast charging capability"],
    "improvements": ["Silicone cable fixed to earbuds"]
  },
  {
    "id": "boat-nirvana-ion-anc",
    "name": "boAt Nirvana Ion ANC True Wireless Earbuds (120H Playtime, Silver)",
    "brand": "boAt",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 2499,
    "score": 72.0,
    "carbon": 16.0,
    "conv_carb": 24.0,
    "water": 410,
    "lifespan": 3.5,
    "sub": [73, 70, 75, 71, 76, 54, 68],
    "explanation": "Class-leading 120 hours total battery reserve minimizes charging socket cycles.",
    "mats": [{"name": "Polycarbonate Casing", "percentage": 60, "isRecycled": False}, {"name": "High-density Battery", "percentage": 25, "isRecycled": False}, {"name": "Crystal Bionic Drivers", "percentage": 15, "isRecycled": False}],
    "pack": "Paperboard box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Safety standard"}],
    "strengths": ["Massive 120-hour battery cycle longevity", "Active noise cancellation under ₹2500"],
    "improvements": ["Case volume is larger than typical pocket cases"]
  },
  {
    "id": "oneplus-bullets-wireless-z2",
    "name": "OnePlus Bullets Wireless Z2 Bluetooth Neckband (Acoustic Red)",
    "brand": "OnePlus",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 1999,
    "score": 72.0,
    "carbon": 13.0,
    "conv_carb": 20.0,
    "water": 350,
    "lifespan": 3.0,
    "sub": [73, 69, 77, 69, 76, 54, 68],
    "explanation": "Magnetic earbuds auto-pause audio and power down when clipped, eliminating standby battery drain.",
    "mats": [{"name": "Silicone Wire", "percentage": 45, "isRecycled": False}, {"name": "Magnetic Earbuds", "percentage": 25, "isRecycled": False}, {"name": "Lithium Battery", "percentage": 30, "isRecycled": False}],
    "pack": "Compact paper box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Safety certified"}],
    "strengths": ["Magnetic sleep switch prevents battery discharge", "10 min charge gives 20 hours"],
    "improvements": ["Single-piece cable not replaceable if severed"]
  },
  {
    "id": "nothing-ear-a",
    "name": "Nothing Ear (a) High-Res Wireless Earbuds (Bright Yellow)",
    "brand": "Nothing",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 7999,
    "score": 83.5,
    "carbon": 16.0,
    "conv_carb": 28.0,
    "water": 490,
    "lifespan": 4.5,
    "sub": [82, 85, 84, 82, 94, 65, 82],
    "explanation": "Audited lifecycle footprint of 16 kg CO₂e with plastic-free recycled paper packaging.",
    "mats": [{"name": "Recycled Polycarbonate", "percentage": 48, "isRecycled": True}, {"name": "Recycled Solder Tin", "percentage": 18, "isRecycled": True}, {"name": "Ceramic Driver Diaphragm", "percentage": 14, "isRecycled": False}, {"name": "Micro Battery Cells", "percentage": 20, "isRecycled": False}],
    "pack": "100% plastic-free recycled paper box",
    "plastic_free": True,
    "certs": [{"id": "carbon-trust", "name": "Carbon Trust Audited", "issuer": "Carbon Trust", "verified": True, "description": "Audited product footprint"}],
    "strengths": ["Plastic-free packaging", "Hi-Res Audio LDAC certification with custom ceramic diaphragm"],
    "improvements": ["Clear polycarbonate case shows fine key marks"]
  },
  {
    "id": "nothing-ear-2024",
    "name": "Nothing Ear Flagship Wireless Earbuds (White)",
    "brand": "Nothing",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 11999,
    "score": 84.5,
    "carbon": 17.5,
    "conv_carb": 30.0,
    "water": 510,
    "lifespan": 4.5,
    "sub": [83, 86, 85, 84, 94, 66, 84],
    "explanation": "Ceramic driver upgrade delivers acoustic clarity with 100% renewable electricity in final assembly.",
    "mats": [{"name": "Recycled Plastics in Case", "percentage": 50, "isRecycled": True}, {"name": "Recycled Tin Solder", "percentage": 16, "isRecycled": True}, {"name": "Ceramic Driver Assembly", "percentage": 14, "isRecycled": False}, {"name": "Batteries", "percentage": 20, "isRecycled": False}],
    "pack": "100% plastic-free packaging",
    "plastic_free": True,
    "certs": [{"id": "carbon-trust", "name": "Carbon Trust Certified", "issuer": "Carbon Trust", "verified": True, "description": "Audited emissions"}],
    "strengths": ["Wireless Qi charging on case", "Plastic-free packaging", "Renewable assembly"],
    "improvements": ["Earbud batteries cannot be opened without breaking water seal"]
  },
  {
    "id": "apple-airpods-pro-2",
    "name": "Apple AirPods Pro 2nd Gen with USB-C Case (White)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 24900,
    "score": 82.0,
    "carbon": 22.0,
    "conv_carb": 38.0,
    "water": 650,
    "lifespan": 4.5,
    "sub": [80, 85, 86, 81, 95, 52, 85],
    "explanation": "100% recycled gold in circuit board plating and 100% recycled rare earth elements across all magnets.",
    "mats": [{"name": "Recycled Rare Earth Magnets", "percentage": 28, "isRecycled": True}, {"name": "Recycled Gold & Tin", "percentage": 22, "isRecycled": True}, {"name": "Bio-polymers & Sensors", "percentage": 50, "isRecycled": False}],
    "pack": "100% fiber packaging, zero plastic wrap",
    "plastic_free": True,
    "certs": [{"id": "energy-star", "name": "ENERGY STAR Charger", "issuer": "EPA", "verified": True, "description": "Efficiency rating"}],
    "strengths": ["100% recycled rare earth magnets", "Clinical hearing aid feature firmware extends health utility"],
    "improvements": ["iFixit repairability rating of 0/10"]
  },
  {
    "id": "realme-buds-air-5-pro",
    "name": "Realme Buds Air 5 Pro ANC Earbuds (Sunrise Beige)",
    "brand": "Realme",
    "cat": "Electronics",
    "subcat": "Audio",
    "price": 4999,
    "score": 75.0,
    "carbon": 16.0,
    "conv_carb": 26.0,
    "water": 460,
    "lifespan": 3.5,
    "sub": [75, 74, 78, 73, 80, 60, 72],
    "explanation": "Dual coaxial driver setup with 50dB deep noise cancellation in compact lightweight housing.",
    "mats": [{"name": "Polycarbonate Case", "percentage": 60, "isRecycled": False}, {"name": "Lithium Polymer Battery", "percentage": 22, "isRecycled": False}, {"name": "Dual Drivers", "percentage": 18, "isRecycled": False}],
    "pack": "Paperboard box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Safety standard"}],
    "strengths": ["LDAC high-resolution codec", "40-hour total runtime"],
    "improvements": ["Glossy finish shows scratches over time"]
  },

  # --- WEARABLES & WATCHES (6 items) ---
  {
    "id": "apple-watch-series-9-carbon-neutral",
    "name": "Apple Watch Series 9 (GPS 41mm, Midnight Aluminium with Sport Loop)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Wearables",
    "price": 41900,
    "score": 92.0,
    "carbon": 14.0,
    "conv_carb": 36.0,
    "water": 510,
    "lifespan": 6.0,
    "sub": [93, 94, 91, 92, 96, 64, 95],
    "explanation": "Certified Carbon Neutral product combination; 100% recycled aluminium case and Sport Loop made with 82% recycled yarn.",
    "mats": [{"name": "100% Recycled Aluminium Case", "percentage": 45, "isRecycled": True}, {"name": "Sport Loop Recycled Yarn", "percentage": 20, "isRecycled": True}, {"name": "100% Recycled Gold, Tin & Rare Earths", "percentage": 15, "isRecycled": True}, {"name": "Ion-X Glass", "percentage": 20, "isRecycled": False}],
    "pack": "100% fiber plastic-free packaging",
    "plastic_free": True,
    "certs": [{"id": "carbon-neutral", "name": "Carbon Neutral Certified", "issuer": "SCS Global", "verified": True, "description": "Over 78% absolute emissions reduction + verified nature sinks"}],
    "strengths": ["Officially verified carbon neutral product pair", "100% clean supplier electricity", "Recycled yarn loop"],
    "improvements": ["Display glued to enclosure"]
  },
  {
    "id": "apple-watch-se-carbon-neutral",
    "name": "Apple Watch SE (GPS 40mm, Starlight Aluminium with Sport Loop)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Wearables",
    "price": 29900,
    "score": 91.0,
    "carbon": 18.0,
    "conv_carb": 39.0,
    "water": 580,
    "lifespan": 5.5,
    "sub": [92, 92, 90, 91, 96, 64, 94],
    "explanation": "100% recycled aluminium case paired with Sport Loop made of 82% recycled yarn.",
    "mats": [{"name": "100% Recycled Aluminium Case", "percentage": 45, "isRecycled": True}, {"name": "Recycled Yarn", "percentage": 20, "isRecycled": True}, {"name": "Recycled Internal Metals", "percentage": 15, "isRecycled": True}, {"name": "Glass & Bio-Nylon Back", "percentage": 20, "isRecycled": False}],
    "pack": "100% fiber packaging",
    "plastic_free": True,
    "certs": [{"id": "carbon-neutral", "name": "Carbon Neutral Certified", "issuer": "SCS Global", "verified": True, "description": "Audited zero footprint"}],
    "strengths": ["Carbon neutral certification", "Comprehensive heart health and fall detection sensors"],
    "improvements": ["Battery glued under screen"]
  },
  {
    "id": "samsung-galaxy-watch-6",
    "name": "Samsung Galaxy Watch 6 (40mm Bluetooth, Graphite)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Wearables",
    "price": 19999,
    "score": 82.5,
    "carbon": 21.0,
    "conv_carb": 36.0,
    "water": 640,
    "lifespan": 4.5,
    "sub": [81, 83, 88, 82, 90, 66, 82],
    "explanation": "Sapphire Crystal display dramatically prevents scratch failures; 100% recycled paper packaging.",
    "mats": [{"name": "Armor Aluminium", "percentage": 42, "isRecycled": False}, {"name": "Sapphire Crystal Glass", "percentage": 25, "isRecycled": False}, {"name": "Recycled Plastic Parts", "percentage": 15, "isRecycled": True}, {"name": "Sensors", "percentage": 18, "isRecycled": False}],
    "pack": "100% recycled paper box",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO", "issuer": "UL", "verified": True, "description": "Eco rating"}],
    "strengths": ["Sapphire Crystal screen resists scratch degradation", "4 years Wear OS platform updates"],
    "improvements": ["Battery requires daily recharging"]
  },
  {
    "id": "noise-colorfit-pulse-3",
    "name": "Noise ColorFit Pulse 3 Smartwatch (1.96-inch TFT, Jet Black)",
    "brand": "Noise",
    "cat": "Electronics",
    "subcat": "Wearables",
    "price": 1599,
    "score": 70.0,
    "carbon": 15.0,
    "conv_carb": 24.0,
    "water": 390,
    "lifespan": 3.0,
    "sub": [71, 67, 74, 68, 78, 55, 65],
    "explanation": "Assembled in India; standard 22mm interchangeable strap mechanism prevents disposal when strap wears out.",
    "mats": [{"name": "Zinc Alloy Bezel", "percentage": 38, "isRecycled": False}, {"name": "Silicone Strap", "percentage": 32, "isRecycled": False}, {"name": "TFT Display & PCB", "percentage": 30, "isRecycled": False}],
    "pack": "Cardboard box with paper sleeve",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS ISI Certified", "issuer": "BIS", "verified": True, "description": "Consumer safety"}],
    "strengths": ["Universal quick-release strap lugs", "Made in India assembly"],
    "improvements": ["Display is TFT rather than energy efficient AMOLED"]
  },
  {
    "id": "boat-wave-call-2",
    "name": "boAt Wave Call 2 Smartwatch with Bluetooth Calling (Active Black)",
    "brand": "boAt",
    "cat": "Electronics",
    "subcat": "Wearables",
    "price": 1499,
    "score": 69.5,
    "carbon": 15.5,
    "conv_carb": 24.0,
    "water": 410,
    "lifespan": 3.0,
    "sub": [70, 66, 73, 67, 78, 54, 65],
    "explanation": "IP67 sweat and splash resistance; manufactured locally in Noida facility.",
    "mats": [{"name": "Zinc Alloy Dial", "percentage": 40, "isRecycled": False}, {"name": "Silicone Strap", "percentage": 30, "isRecycled": False}, {"name": "Display & Battery", "percentage": 30, "isRecycled": False}],
    "pack": "Cardboard packaging",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS India", "verified": True, "description": "National approval"}],
    "strengths": ["Local domestic assembly", "7-day battery life per charge"],
    "improvements": ["Proprietary magnetic charging pin cable"]
  },
  {
    "id": "fire-boltt-phoenix-ultra",
    "name": "Fire-Boltt Phoenix Ultra Luxury Stainless Steel Smartwatch (Gold)",
    "brand": "Fire-Boltt",
    "cat": "Electronics",
    "subcat": "Wearables",
    "price": 1999,
    "score": 71.0,
    "carbon": 18.0,
    "conv_carb": 27.0,
    "water": 460,
    "lifespan": 3.5,
    "sub": [71, 68, 80, 72, 76, 56, 66],
    "explanation": "Durable stainless steel luxury mesh chain and case resists cosmetic wear far longer than coated plastic.",
    "mats": [{"name": "Stainless Steel Mesh Strap & Case", "percentage": 55, "isRecycled": False}, {"name": "High-res TFT Display", "percentage": 25, "isRecycled": False}, {"name": "Lithium Cell", "percentage": 20, "isRecycled": False}],
    "pack": "Cardboard gift box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Approved", "issuer": "BIS", "verified": True, "description": "Safety standard"}],
    "strengths": ["Stainless steel casing does not chip or peel like plastic paint", "Durable magnetic clasp"],
    "improvements": ["Higher mineral extraction mass"]
  },

  # --- POWER BANKS & GAN CHARGERS (6 items) ---
  {
    "id": "anker-511-nano-3-charger",
    "name": "Anker 511 Charger (Nano 3 30W GaN Fast Charger, Natural Green)",
    "brand": "Anker",
    "cat": "Electronics",
    "subcat": "Power Banks",
    "price": 1899,
    "score": 86.0,
    "carbon": 8.5,
    "conv_carb": 18.0,
    "water": 210,
    "lifespan": 7.0,
    "sub": [88, 85, 92, 82, 94, 60, 86],
    "explanation": "GaN semiconductors reduce size by 70% and electrical energy waste by 95%; outer shell made with 30.9% PCR plastic.",
    "mats": [{"name": "Post-Consumer Recycled Plastics", "percentage": 31, "isRecycled": True}, {"name": "Gallium Nitride (GaN) Semiconductors", "percentage": 25, "isRecycled": False}, {"name": "Copper Coils", "percentage": 30, "isRecycled": False}, {"name": "Aluminium Shield", "percentage": 14, "isRecycled": False}],
    "pack": "100% plastic-free paper pulp box",
    "plastic_free": True,
    "certs": [{"id": "energy-star", "name": "DOE Level VI Energy Efficiency", "issuer": "US DOE", "verified": True, "description": "Highest conversion efficiency"}],
    "strengths": ["GaN efficiency cuts heat loss drastically", "Compact volume saves shipping freight fuel", "30.9% PCR plastic in shell"],
    "improvements": ["Fixed non-foldable Indian two-pin plug"]
  },
  {
    "id": "anker-735-ganprime-65w",
    "name": "Anker 735 Charger (GaNPrime 65W 3-Port Wall Charger, Black)",
    "brand": "Anker",
    "cat": "Electronics",
    "subcat": "Power Banks",
    "price": 3999,
    "score": 85.0,
    "carbon": 14.0,
    "conv_carb": 28.0,
    "water": 320,
    "lifespan": 7.5,
    "sub": [86, 84, 94, 82, 92, 62, 86],
    "explanation": "Powers phone, tablet, and laptop simultaneously from one brick, replacing three separate bulky chargers.",
    "mats": [{"name": "GaN Semiconductors", "percentage": 28, "isRecycled": False}, {"name": "Flame Retardant PCR Plastic", "percentage": 32, "isRecycled": True}, {"name": "Copper & Brass Connectors", "percentage": 40, "isRecycled": False}],
    "pack": "Plastic-free paper box",
    "plastic_free": True,
    "certs": [{"id": "energy-star", "name": "DOE Level VI", "issuer": "DOE", "verified": True, "description": "Efficiency standard"}],
    "strengths": ["Replaces 3 individual power adapters", "PowerIQ 4.0 dynamic wattage allocation saves energy"],
    "improvements": ["Internal silicone potting prevents individual component replacement"]
  },
  {
    "id": "mi-power-bank-3i-20000",
    "name": "Mi 20000mAh 18W Fast Charging Power Bank 3i (Sandstone Black)",
    "brand": "Xiaomi",
    "cat": "Electronics",
    "subcat": "Power Banks",
    "price": 2149,
    "score": 74.0,
    "carbon": 22.0,
    "conv_carb": 32.0,
    "water": 580,
    "lifespan": 4.0,
    "sub": [75, 72, 80, 74, 78, 58, 70],
    "explanation": "12-layer advanced circuit protection prevents battery burnout; assembled in Sri City, Andhra Pradesh.",
    "mats": [{"name": "Lithium Polymer Battery Cells", "percentage": 60, "isRecycled": False}, {"name": "PC-ABS Flame-Retardant Casing", "percentage": 28, "isRecycled": False}, {"name": "Power Management PCB", "percentage": 12, "isRecycled": False}],
    "pack": "Cardboard box with paper slip",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS IS 16046 Certified", "issuer": "BIS India", "verified": True, "description": "Secondary cell safety"}],
    "strengths": ["Domestic Indian production", "12-layer short-circuit safety safeguards against premature battery cell death"],
    "improvements": ["Ultrasonically welded enclosure cannot be opened for cell replacement"]
  },
  {
    "id": "ambrane-stylo-20k",
    "name": "Ambrane 20000mAh 20W Fast Charging Power Bank (Stylo 20k, Green)",
    "brand": "Ambrane",
    "cat": "Electronics",
    "subcat": "Power Banks",
    "price": 1899,
    "score": 73.0,
    "carbon": 23.0,
    "conv_carb": 33.0,
    "water": 610,
    "lifespan": 3.5,
    "sub": [74, 71, 78, 73, 76, 56, 68],
    "explanation": "Manufactured in Kundli, Haryana reducing international freight logistics emissions.",
    "mats": [{"name": "Lithium Polymer Cells", "percentage": 62, "isRecycled": False}, {"name": "ABS Plastic Casing", "percentage": 26, "isRecycled": False}, {"name": "Chipsets & Wiring", "percentage": 12, "isRecycled": False}],
    "pack": "Recyclable paperboard box",
    "plastic_free": False,
    "certs": [{"id": "bis-isi", "name": "BIS Certified", "issuer": "BIS", "verified": True, "description": "National approval"}],
    "strengths": ["Manufactured locally in Haryana", "Multi-device pass-through charging"],
    "improvements": ["Heavy 410g mass"]
  },
  {
    "id": "portronics-konnect-l-cable",
    "name": "Portronics Konnect L 1.2M Braided USB-C Cable (Fast Charge, Black)",
    "brand": "Portronics",
    "cat": "Electronics",
    "subcat": "Power Banks",
    "price": 299,
    "score": 78.0,
    "carbon": 3.2,
    "conv_carb": 6.5,
    "water": 85,
    "lifespan": 5.0,
    "sub": [80, 76, 88, 76, 82, 60, 72],
    "explanation": "Heavy-duty nylon braided exterior tested for 10,000+ bends prevents cable fraying waste.",
    "mats": [{"name": "High-durability Nylon Braid", "percentage": 40, "isRecycled": False}, {"name": "Pure Copper Core", "percentage": 35, "isRecycled": False}, {"name": "Aluminium Connector Shells", "percentage": 25, "isRecycled": False}],
    "pack": "Paper envelope",
    "plastic_free": True,
    "certs": [{"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Heavy metal free"}],
    "strengths": ["Nylon braid prevents typical PVC jacket cracking", "Tested for 10,000 bends"],
    "improvements": ["Nylon cannot be easily separated from copper during recycling"]
  },
  {
    "id": "belkin-boostcharge-pro-65w",
    "name": "Belkin BoostCharge Pro Dual USB-C GaN 65W Wall Charger (White)",
    "brand": "Belkin",
    "cat": "Electronics",
    "subcat": "Power Banks",
    "price": 3999,
    "score": 86.5,
    "carbon": 12.0,
    "conv_carb": 26.0,
    "water": 290,
    "lifespan": 7.0,
    "sub": [87, 88, 92, 84, 94, 60, 88],
    "explanation": "Housing made with 72% post-consumer recycled plastic and 100% plastic-free packaging.",
    "mats": [{"name": "Post-Consumer Recycled Plastics (PCR)", "percentage": 72, "isRecycled": True}, {"name": "GaN Semiconductors", "percentage": 15, "isRecycled": False}, {"name": "Copper & Brass", "percentage": 13, "isRecycled": False}],
    "pack": "100% plastic-free packaging",
    "plastic_free": True,
    "certs": [{"id": "rohs", "name": "RoHS Compliant", "issuer": "EU", "verified": True, "description": "Chemical compliance"}],
    "strengths": ["72% PCR plastic housing", "100% plastic-free packaging", "PPS dynamic voltage power delivery"],
    "improvements": ["Premium price point"]
  },

  # --- MONITORS & COMPUTING (7 items) ---
  {
    "id": "benq-gw2790qt-monitor",
    "name": "BenQ GW2790QT 27-inch 2K QHD Eye-Care USB-C Monitor (White)",
    "brand": "BenQ",
    "cat": "Electronics",
    "subcat": "Monitors & Displays",
    "price": 24990,
    "score": 84.0,
    "carbon": 210.0,
    "conv_carb": 380.0,
    "water": 4800,
    "lifespan": 8.0,
    "sub": [82, 85, 92, 84, 90, 82, 88],
    "explanation": "85% post-consumer recycled plastics in monitor body and stand, packaged with zero EPS foam.",
    "mats": [{"name": "Post-Consumer Recycled Plastics (PCR)", "percentage": 48, "isRecycled": True}, {"name": "IPS LED Backlight Panel", "percentage": 32, "isRecycled": False}, {"name": "Steel Stand & Internal Frame", "percentage": 20, "isRecycled": True}],
    "pack": "85% recycled cardboard with molded paper inserts (zero EPS foam)",
    "plastic_free": True,
    "certs": [{"id": "tco-gen9", "name": "TCO Certified Gen 9", "issuer": "TCO", "verified": True, "description": "Stringent electronics standard"}, {"id": "energy-star", "name": "ENERGY STAR 8.0", "issuer": "EPA", "verified": True, "description": "Power efficiency"}],
    "strengths": ["85% PCR plastics in chassis", "Brightness Intelligence Gen2 saves up to 40% backlight electricity", "Zero EPS foam packaging"],
    "improvements": ["Backlight panel contains non-recycled optical diffuser sheets"]
  },
  {
    "id": "lg-ultrafine-27-4k-monitor",
    "name": "LG UltraFine 27-inch 4K UHD IPS Monitor (27UN880 Ergo Stand)",
    "brand": "LG",
    "cat": "Electronics",
    "subcat": "Monitors & Displays",
    "price": 36999,
    "score": 81.5,
    "carbon": 235.0,
    "conv_carb": 410.0,
    "water": 5200,
    "lifespan": 8.5,
    "sub": [80, 82, 92, 82, 86, 80, 84],
    "explanation": "Heavy-duty C-clamp ergonomic arm avoids plastic desktop bases; LG Smart Energy Saving algorithm.",
    "mats": [{"name": "Recycled Steel Ergo Clamp Arm", "percentage": 40, "isRecycled": True}, {"name": "PCR Plastic Housing", "percentage": 25, "isRecycled": True}, {"name": "UHD IPS Panel", "percentage": 35, "isRecycled": False}],
    "pack": "Recycled cardboard box",
    "plastic_free": False,
    "certs": [{"id": "epeat-silver", "name": "EPEAT Silver", "issuer": "GEC", "verified": True, "description": "Eco rating"}],
    "strengths": ["Steel ergo clamp eliminates plastic desk foot", "Long display lifespan"],
    "improvements": ["Power supply brick uses external plastic housing"]
  },
  {
    "id": "logitech-pebble-keys-2",
    "name": "Logitech Pebble Keys 2 K380s Multi-Device Bluetooth Keyboard (Tonal Rose)",
    "brand": "Logitech",
    "cat": "Electronics",
    "subcat": "Computing Accessories",
    "price": 2495,
    "score": 88.0,
    "carbon": 6.8,
    "conv_carb": 15.0,
    "water": 170,
    "lifespan": 6.0,
    "sub": [89, 92, 90, 88, 94, 76, 88],
    "explanation": "Certified Carbon Neutral; manufactured with minimum 49% certified post-consumer recycled plastic.",
    "mats": [{"name": "Post-Consumer Recycled Plastics (PCR)", "percentage": 49, "isRecycled": True}, {"name": "Scissor Key Switches & PCB", "percentage": 35, "isRecycled": False}, {"name": "Steel Stiffener Plate", "percentage": 16, "isRecycled": True}],
    "pack": "FSC-certified paper packaging",
    "plastic_free": True,
    "certs": [{"id": "carbon-neutral", "name": "Carbon Neutral Certified", "issuer": "SCS Global", "verified": True, "description": "Net zero footprint"}, {"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Responsible forestry"}],
    "strengths": ["Certified Carbon Neutral", "Minimum 49% PCR plastic content", "36-month battery lifespan eliminates recharging cycles"],
    "improvements": ["Requires AAA batteries rather than internal lithium (though easily recyclable)"]
  },
  {
    "id": "logitech-pebble-mouse-2",
    "name": "Logitech Pebble Mouse 2 M350s Slim Bluetooth Mouse (Tonal White)",
    "brand": "Logitech",
    "cat": "Electronics",
    "subcat": "Computing Accessories",
    "price": 1495,
    "score": 88.5,
    "carbon": 4.2,
    "conv_carb": 9.5,
    "water": 110,
    "lifespan": 6.0,
    "sub": [90, 92, 90, 88, 95, 74, 88],
    "explanation": "Certified Carbon Neutral with minimum 58% certified post-consumer recycled plastic and 24-month battery life.",
    "mats": [{"name": "Post-Consumer Recycled Plastics (PCR)", "percentage": 58, "isRecycled": True}, {"name": "Optical Sensor & Silent Switches", "percentage": 27, "isRecycled": False}, {"name": "Metal Scroll Wheel Mechanism", "percentage": 15, "isRecycled": True}],
    "pack": "FSC-certified paper packaging",
    "plastic_free": True,
    "certs": [{"id": "carbon-neutral", "name": "Carbon Neutral Certified", "issuer": "SCS Global", "verified": True, "description": "Verified net zero"}, {"id": "fsc", "name": "FSC Certified", "issuer": "FSC", "verified": True, "description": "Forestry standard"}],
    "strengths": ["58% certified PCR plastic body", "SilentTouch technology cuts click noise by 90%", "2-year single AA battery life"],
    "improvements": ["Low-profile shape less suitable for large hand palm grips"]
  },
  {
    "id": "apple-ipad-10th-gen",
    "name": "Apple iPad 10th Gen (10.9-inch Wi-Fi 64GB, Blue)",
    "brand": "Apple",
    "cat": "Electronics",
    "subcat": "Tablets",
    "price": 34900,
    "score": 83.0,
    "carbon": 72.0,
    "conv_carb": 118.0,
    "water": 1690,
    "lifespan": 6.0,
    "sub": [81, 85, 90, 83, 95, 65, 86],
    "explanation": "100% recycled aluminium enclosure and 100% recycled gold in logic board plating; plastic-free fiber packaging.",
    "mats": [{"name": "100% Recycled Aluminium Enclosure", "percentage": 52, "isRecycled": True}, {"name": "Liquid Retina Display Glass", "percentage": 28, "isRecycled": False}, {"name": "Lithium Polymer Battery", "percentage": 20, "isRecycled": False}],
    "pack": "100% fiber plastic-free packaging",
    "plastic_free": True,
    "certs": [{"id": "energy-star", "name": "ENERGY STAR", "issuer": "EPA", "verified": True, "description": "High efficiency"}, {"id": "epeat-gold", "name": "EPEAT Gold", "issuer": "GEC", "verified": True, "description": "Eco standard"}],
    "strengths": ["100% recycled aluminium body", "USB-C universal port", "5+ years of iPadOS software updates"],
    "improvements": ["Display glass not laminated to digitizer"]
  },
  {
    "id": "samsung-galaxy-tab-s9-fe",
    "name": "Samsung Galaxy Tab S9 FE (10.9-inch 128GB Wi-Fi with S Pen, Mint)",
    "brand": "Samsung",
    "cat": "Electronics",
    "subcat": "Tablets",
    "price": 36999,
    "score": 82.5,
    "carbon": 74.0,
    "conv_carb": 120.0,
    "water": 1720,
    "lifespan": 5.5,
    "sub": [80, 84, 91, 82, 90, 68, 84],
    "explanation": "IP68 water and dust resistant tablet and S Pen; uses components made from recycled discarded fishing nets.",
    "mats": [{"name": "Recycled Ocean Plastics & Aluminium", "percentage": 48, "isRecycled": True}, {"name": "IPS 90Hz Display", "percentage": 28, "isRecycled": False}, {"name": "Battery & Motherboard", "percentage": 24, "isRecycled": False}],
    "pack": "100% recycled paper box",
    "plastic_free": True,
    "certs": [{"id": "ul-ecologo", "name": "UL ECOLOGO", "issuer": "UL", "verified": True, "description": "Eco certification"}],
    "strengths": ["IP68 water resistance ensures longevity in humid conditions", "S Pen included in box with zero battery needed (EMR resonance)"],
    "improvements": ["Battery glued into chassis"]
  },
  {
    "id": "oneplus-pad-go",
    "name": "OnePlus Pad Go (11.35-inch 2.4K Display, 128GB Wi-Fi, Twin Mint)",
    "brand": "OnePlus",
    "cat": "Electronics",
    "subcat": "Tablets",
    "price": 19999,
    "score": 76.0,
    "carbon": 68.0,
    "conv_carb": 105.0,
    "water": 1580,
    "lifespan": 4.5,
    "sub": [76, 75, 82, 75, 82, 66, 76],
    "explanation": "Large 8000mAh battery with 33W SUPERVOOC charging, housed in an ergonomic curved metal unibody.",
    "mats": [{"name": "Aluminium Unibody (Twin-tone)", "percentage": 45, "isRecycled": False}, {"name": "2.4K Eye-Care Display", "percentage": 30, "isRecycled": False}, {"name": "8000mAh Battery Cell", "percentage": 25, "isRecycled": False}],
    "pack": "Cardboard box with paper sleeve",
    "plastic_free": False,
    "certs": [{"id": "tuv-rheinland", "name": "TÜV Rheinland Low Blue Light", "issuer": "TÜV", "verified": True, "description": "Eye health certified"}],
    "strengths": ["8000mAh battery provides long endurance between recharges", "TÜV certified low blue light display"],
    "improvements": ["Slower software update rollout cycle compared to Apple"]
  }
]

