# Personal Care Catalog Data (45 products)
# Indian Market Personal Care: Hair, Skin, Bath, Oral & Grooming

personal_care_items = [
  # --- HAIR CARE & SHAMPOOS (10 items) ---
  {
    "id": "himalaya-anti-hair-fall-shampoo",
    "name": "Himalaya Anti-Hair Fall Bhringaraja Herbal Shampoo 400ml",
    "brand": "Himalaya",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 280,
    "score": 83.5,
    "carbon": 1.4,
    "conv_carb": 3.8,
    "water": 45,
    "lifespan": 0.5,
    "sub": [84, 86, 82, 80, 85, 78, 88],
    "explanation": "Botanical formulation enriched with Butea Frondosa and Bhringaraja herbs grown on sustainable contract farms in Karnataka.",
    "mats": [{"name": "Herbal Extracts (Bhringaraja & Palasha)", "percentage": 30, "isRecycled": False, "isRenewable": True}, {"name": "Aqua & Gentle Cleansers", "percentage": 60, "isRecycled": False}, {"name": "Recyclable HDPE Bottle", "percentage": 10, "isRecycled": True}],
    "pack": "100% recyclable HDPE plastic bottle",
    "plastic_free": False,
    "certs": [{"id": "ayush", "name": "Ministry of AYUSH Certified", "issuer": "Govt of India", "verified": True, "description": "Authentic Ayurvedic medicine standard"}, {"id": "cruelty-free", "name": "Cruelty-Free International", "issuer": "PETA India", "verified": True, "description": "Never tested on animals"}],
    "strengths": ["Herbal ingredients sourced via fair contract farming with smallholder Indian growers", "Biodegradable rinse formula", "Paraben-free"],
    "improvements": ["Liquid format still requires plastic packaging compared to solid shampoo bars"]
  },
  {
    "id": "mamaearth-onion-hair-fall-shampoo",
    "name": "Mamaearth Onion Hair Fall Control Shampoo with Plant Keratin 400ml",
    "brand": "Mamaearth",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 499,
    "score": 84.0,
    "carbon": 1.5,
    "conv_carb": 4.0,
    "water": 50,
    "lifespan": 0.5,
    "sub": [85, 87, 82, 82, 86, 78, 88],
    "explanation": "Asia's first MadeSafe certified brand; recycles more plastic than it consumes through verified EPR offsets.",
    "mats": [{"name": "Organic Red Onion Seed Oil", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Plant Keratin (Wheat & Soy Amino Acids)", "percentage": 15, "isRecycled": False, "isRenewable": True}, {"name": "Purified Water & Eco Surfactants", "percentage": 50, "isRecycled": False}, {"name": "PCR Polymer Bottle", "percentage": 10, "isRecycled": True}],
    "pack": "50% PCR plastic bottle with pump",
    "plastic_free": False,
    "certs": [{"id": "madesafe", "name": "MadeSafe Certified Non-Toxic", "issuer": "Made Safe USA", "verified": True, "description": "Free of behavioral toxins, carcinogens, and endocrine disruptors"}, {"id": "plastic-positive", "name": "Plastic Positive Certified", "issuer": "The Disposal Company", "verified": True, "description": "Offsets 2x plastic footprint"}],
    "strengths": ["Plant keratin replaces animal keratin", "Zero sulfates, parabens, silicones, dyes, or mineral oil", "Plastic positive certified brand"],
    "improvements": ["Pump dispenser mechanism contains mixed internal metal springs complicating recycling"]
  },
  {
    "id": "dove-hair-fall-rescue-shampoo-pcr",
    "name": "Dove Hair Fall Rescue Shampoo in 100% Recycled Plastic Bottle 650ml",
    "brand": "Dove",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 549,
    "score": 82.0,
    "carbon": 1.8,
    "conv_carb": 4.5,
    "water": 55,
    "lifespan": 0.6,
    "sub": [83, 85, 84, 84, 88, 76, 84],
    "explanation": "Packaged in 100% post-consumer recycled (PCR) plastic bottle; PETA cruelty-free certified global formula.",
    "mats": [{"name": "100% Post-Consumer Recycled Plastic Bottle", "percentage": 12, "isRecycled": True}, {"name": "Nutrilock Actives & Cleansers", "percentage": 38, "isRecycled": False}, {"name": "Water Base", "percentage": 50, "isRecycled": False}],
    "pack": "100% PCR recycled plastic bottle (excluding cap)",
    "plastic_free": False,
    "certs": [{"id": "peta-cruelty-free", "name": "PETA Approved Cruelty-Free", "issuer": "PETA", "verified": True, "description": "Global animal testing ban compliance"}],
    "strengths": ["100% PCR recycled bottle diverts post-consumer plastic scrap from landfills", "Micro-moisture serum reduces hair breakage by 98%"],
    "improvements": ["Contains standard synthetic sulfates (SLES) for lathering"]
  },
  {
    "id": "head-and-shoulders-cool-menthol",
    "name": "Head & Shoulders Cool Menthol Anti-Dandruff Shampoo 650ml",
    "brand": "Head & Shoulders",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 575,
    "score": 75.0,
    "carbon": 2.2,
    "conv_carb": 4.2,
    "water": 65,
    "lifespan": 0.6,
    "sub": [76, 74, 80, 78, 82, 72, 76],
    "explanation": "Zinc pyrithione clinically clears fungal dandruff; bottle is 100% recyclable HDPE.",
    "mats": [{"name": "Active Zinc Pyrithione", "percentage": 5, "isRecycled": False}, {"name": "Menthol & Surfactants", "percentage": 45, "isRecycled": False}, {"name": "Recyclable HDPE Plastic", "percentage": 12, "isRecycled": False}, {"name": "Water", "percentage": 38, "isRecycled": False}],
    "pack": "Recyclable HDPE bottle",
    "plastic_free": False,
    "certs": [{"id": "rohs-cosmetics", "name": "Dermatologically Tested", "issuer": "Skin Health Alliance", "verified": True, "description": "Skin safety endorsement"}],
    "strengths": ["Proven clinical efficacy reduces unnecessary product switching waste", "HDPE bottle easily identified and processed in municipal Indian recycling"],
    "improvements": ["Zinc pyrithione can have mild aquatic toxicity if washed untreated into waterways"]
  },
  {
    "id": "tresemme-keratin-smooth-shampoo",
    "name": "Tresemme Keratin Smooth Sulfate-Free Salon Shampoo 580ml",
    "brand": "Tresemme",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 599,
    "score": 78.0,
    "carbon": 2.0,
    "conv_carb": 4.4,
    "water": 58,
    "lifespan": 0.6,
    "sub": [79, 78, 82, 80, 84, 74, 78],
    "explanation": "Formulated with lightweight marula oil and gentle cleansers with zero added parabens or harsh dyes.",
    "mats": [{"name": "African Marula Seed Oil", "percentage": 10, "isRecycled": False, "isRenewable": True}, {"name": "Hydrolyzed Keratin", "percentage": 10, "isRecycled": False}, {"name": "Recycled Plastic Bottle Resin", "percentage": 25, "isRecycled": True}, {"name": "Aqua", "percentage": 55, "isRecycled": False}],
    "pack": "25% PCR plastic bottle",
    "plastic_free": False,
    "certs": [{"id": "peta-approved", "name": "PETA Cruelty-Free", "issuer": "PETA", "verified": True, "description": "No animal testing"}],
    "strengths": ["Marula oil sustainably harvested from wild cooperative trees", "Lower sulfate foaming cleansers preserve natural scalp lipid balance"],
    "improvements": ["Silicones present in smoothing blend"]
  },
  {
    "id": "biotique-bio-kelp-protein-shampoo",
    "name": "Biotique Bio Kelp Protein Fresh Growth Stimulating Shampoo 400ml",
    "brand": "Biotique",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 299,
    "score": 86.0,
    "carbon": 1.2,
    "conv_carb": 3.6,
    "water": 40,
    "lifespan": 0.5,
    "sub": [87, 88, 84, 82, 88, 80, 90],
    "explanation": "100% botanical Ayurvedic recipe using natural ocean sea kelp, peppermint oil, and ritha (soapnut) natural foaming agents.",
    "mats": [{"name": "Pure Sea Kelp & Neem Bark", "percentage": 28, "isRecycled": False, "isRenewable": True}, {"name": "Natural Soapnut Foamers (Ritha)", "percentage": 22, "isRecycled": False, "isRenewable": True}, {"name": "Spring Water Base", "percentage": 42, "isRecycled": False}, {"name": "Recyclable Polymer", "percentage": 8, "isRecycled": True}],
    "pack": "100% recyclable green bottle",
    "plastic_free": False,
    "certs": [{"id": "ayush-gmp", "name": "AYUSH GMP Certified", "issuer": "Ministry of AYUSH", "verified": True, "description": "Good Manufacturing Practices for traditional medicine"}, {"id": "dermatologist", "name": "100% Botanical Extracts", "issuer": "Biotique Labs Switzerland/India", "verified": True, "description": "Zero chemical preservatives"}],
    "strengths": ["Uses natural soapnut (Sapindus mukorossi) for foaming rather than petroleum sulfates", "100% biodegradable wastewater runoff"],
    "improvements": ["Bottle plastic is green-tinted which has slightly lower recycled resale value than clear PET"]
  },
  {
    "id": "arata-natural-super-shampoo",
    "name": "Arata Natural Super Shampoo with Onion Oil & Argan Oil 300ml",
    "brand": "Arata",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 549,
    "score": 88.0,
    "carbon": 1.1,
    "conv_carb": 3.8,
    "water": 38,
    "lifespan": 0.4,
    "sub": [88, 92, 85, 86, 92, 80, 92],
    "explanation": "India's first 100% nature-derived wellness brand; certified 100% plastic neutral and packaged in 100% recycled waste plastic bottles.",
    "mats": [{"name": "100% Post-Consumer Recycled (PCR) Plastic", "percentage": 10, "isRecycled": True}, {"name": "Organic Onion Oil & Moroccan Argan Oil", "percentage": 30, "isRecycled": False, "isRenewable": True}, {"name": "Coconut-derived Cleansers (Coco Glucoside)", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Purified Water Base", "percentage": 35, "isRecycled": False}],
    "pack": "100% recycled plastic bottle made from Indian municipal waste",
    "plastic_free": False,
    "certs": [{"id": "plastic-neutral", "name": "100% Plastic Neutral Certified", "issuer": "rePurpose Global", "verified": True, "description": "Finances removal of verified ocean-bound plastic"}, {"id": "ewg-verified", "name": "EWG Verified Standards", "issuer": "Environmental Working Group", "verified": True, "description": "Zero toxic ingredients"}],
    "strengths": ["100% PCR recycled bottle diverted from Indian dump sites", "Coconut glucoside cleansers are 100% rapidly biodegradable in septic systems", "Zero artificial fragrance or phthalates"],
    "improvements": ["Costs more than mass commercial synthetic shampoos"]
  },
  {
    "id": "rustic-art-sandalwood-shampoo-butter",
    "name": "Rustic Art Organic Sandalwood Hair Cleansing Butter Bar 100g",
    "brand": "Rustic Art",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 425,
    "score": 95.0,
    "carbon": 0.4,
    "conv_carb": 3.8,
    "water": 8,
    "lifespan": 0.5,
    "sub": [96, 98, 90, 96, 98, 90, 95],
    "explanation": "Waterless concentrated shampoo butter in an aluminum tin; replaces 3 plastic shampoo bottles, saves water, and creates zero plastic waste.",
    "mats": [{"name": "Cold-Pressed Organic Sesame & Coconut Oils", "percentage": 45, "isRecycled": False, "isRenewable": True}, {"name": "Plant Amino Acid Surfactants (Sodium Cocoyl Isethionate)", "percentage": 35, "isRecycled": False, "isRenewable": True}, {"name": "Pure Sandalwood Essential Oil", "percentage": 10, "isRecycled": False, "isRenewable": True}, {"name": "100% Recyclable Aluminium Tin", "percentage": 10, "isRecycled": True}],
    "pack": "100% infinitely recyclable aluminium tin with seed paper label",
    "plastic_free": True,
    "certs": [{"id": "usda-organic", "name": "Certified Organic Ingredients", "issuer": "USDA Organic", "verified": True, "description": "Organically farmed agricultural inputs"}, {"id": "waterless", "name": "Waterless Beauty Standard", "issuer": "Rustic Art Labs", "verified": True, "description": "Zero shipping of water volume"}],
    "strengths": ["Waterless concentrated formula cuts shipping transport carbon by 85%", "100% plastic-free packaging in an endlessly recyclable aluminium tin", "Zero preservatives needed because formula contains no water"],
    "improvements": ["Requires rubbing between wet palms or applying direct to scalp, different from liquid shampoo routine"]
  },
  {
    "id": "wow-skin-science-apple-cider-shampoo",
    "name": "Wow Skin Science Himalayan Apple Cider Vinegar Shampoo 300ml",
    "brand": "Wow Skin Science",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 399,
    "score": 83.0,
    "carbon": 1.4,
    "conv_carb": 3.9,
    "water": 45,
    "lifespan": 0.4,
    "sub": [84, 85, 82, 81, 86, 76, 86],
    "explanation": "100% raw Himalayan apple cider vinegar clarifies scalp buildup; dermatologically tested without parabens or mineral oils.",
    "mats": [{"name": "Pure Himalayan Apple Cider Vinegar", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Sweet Almond & Argan Oils", "percentage": 15, "isRecycled": False, "isRenewable": True}, {"name": "Gentle Cleansers & Aqua", "percentage": 50, "isRecycled": False}, {"name": "PET Bottle", "percentage": 10, "isRecycled": True}],
    "pack": "Recyclable amber PET bottle",
    "plastic_free": False,
    "certs": [{"id": "cruelty-free", "name": "PETA Cruelty-Free", "issuer": "PETA India", "verified": True, "description": "Never tested on animals"}],
    "strengths": ["Natural vinegar acid restores optimal scalp pH (5.5) without synthetic chemical balancers", "Locally sourced Himalayan apple inputs"],
    "improvements": ["Slight natural vinegar scent may not appeal to all users"]
  },
  {
    "id": "plum-olive-macadamia-hair-mask",
    "name": "Plum Olive & Macadamia Mega Hydration Hair Mask 250g",
    "brand": "Plum",
    "cat": "Personal Care",
    "subcat": "Hair Care",
    "price": 675,
    "score": 86.5,
    "carbon": 1.2,
    "conv_carb": 3.5,
    "water": 35,
    "lifespan": 0.6,
    "sub": [87, 88, 86, 85, 88, 78, 90],
    "explanation": "100% vegan hair spa treatment with cold-pressed olive and macadamia nut oils; brand runs empty plastic tub return recycling program.",
    "mats": [{"name": "Cold-Pressed Virgin Olive Oil", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Macadamia Nut Oil", "percentage": 20, "isRecycled": False, "isRenewable": True}, {"name": "Shea Butter & Conditioning Actives", "percentage": 45, "isRecycled": False, "isRenewable": True}, {"name": "Recycled PP Tub", "percentage": 10, "isRecycled": True}],
    "pack": "100% recyclable polypropylene tub backed by free brand mail-back recycling rewards",
    "plastic_free": False,
    "certs": [{"id": "peta-vegan", "name": "100% Vegan & Cruelty-Free", "issuer": "PETA", "verified": True, "description": "Strictly zero animal-derived ingredients"}],
    "strengths": ["100% vegan formula uses plant waxes instead of animal lanolin", "Free Plum Empties4Good program collects used tubs from customer doorsteps for recycling into school desks"],
    "improvements": ["Plastic jar format rather than cardboard refill tube"]
  },

  # --- FACE CARE, SERUMS & SUNSCREENS (16 items) ---
  {
    "id": "minimalist-10-niacinamide-serum",
    "name": "Minimalist 10% Niacinamide + Zinc Daily Face Serum 30ml",
    "brand": "Minimalist",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 599,
    "score": 89.0,
    "carbon": 0.8,
    "conv_carb": 2.8,
    "water": 22,
    "lifespan": 0.4,
    "sub": [90, 92, 88, 90, 94, 82, 90],
    "explanation": "Pure pharmaceutical grade Niacinamide (Vitamin B3) in amber UV-protective pharmaceutical glass dropper bottle with 100% ingredient transparency.",
    "mats": [{"name": "Pharmaceutical Grade Amber Glass Dropper Bottle", "percentage": 65, "isRecycled": True}, {"name": "Pure Niacinamide (99% pure EU grade) & Zinc PCA", "percentage": 12, "isRecycled": False}, {"name": "Centella Asiatica (Cica) & Aloe Juice", "percentage": 20, "isRecycled": False, "isRenewable": True}, {"name": "Rubber Pipette Bulb", "percentage": 3, "isRecycled": False}],
    "pack": "100% recyclable pharmaceutical amber glass bottle in FSC-certified paper carton",
    "plastic_free": False,
    "certs": [{"id": "clean-label", "name": "Clean Chemistry Audited", "issuer": "Minimalist Open Lab", "verified": True, "description": "Zero fragrance, essential oils, or dyes"}, {"id": "fsc", "name": "FSC Certified Paper Box", "issuer": "FSC", "verified": True, "description": "Eco forestry"}],
    "strengths": ["Amber glass preserves actives without synthetic chemical preservatives", "Publishes exact purity and sourcing supplier certificates online", "Fragrance-free formula safe for eczema and reactive barrier repair"],
    "improvements": ["Rubber dropper pipette bulb must be separated before municipal glass recycling"]
  },
  {
    "id": "minimalist-salicylic-acid-2-serum",
    "name": "Minimalist 2% Salicylic Acid Face Serum with Oligopeptide 30ml",
    "brand": "Minimalist",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 549,
    "score": 88.5,
    "carbon": 0.8,
    "conv_carb": 2.7,
    "water": 20,
    "lifespan": 0.4,
    "sub": [89, 91, 88, 90, 94, 82, 90],
    "explanation": "Oil-soluble BHA exfoliates inside pores to prevent blackheads; packaged in amber glass bottle with aloe vera base.",
    "mats": [{"name": "Amber Glass Bottle", "percentage": 65, "isRecycled": True}, {"name": "Salicylic Acid & Oligopeptide-10", "percentage": 5, "isRecycled": False}, {"name": "Aloe Barbadensis Juice", "percentage": 27, "isRecycled": False, "isRenewable": True}, {"name": "Pipette", "percentage": 3, "isRecycled": False}],
    "pack": "Glass bottle with paper box",
    "plastic_free": False,
    "certs": [{"id": "fsc", "name": "FSC Certified Box", "issuer": "FSC", "verified": True, "description": "Sustainable forestry"}],
    "strengths": ["Uses soothing aloe vera juice base instead of plain demineralized water", "Zero parabens, alcohol, or synthetic fragrance"],
    "improvements": ["Rubber dropper bulb contains trace synthetic polymers"]
  },
  {
    "id": "the-ordinary-hyaluronic-acid-serum",
    "name": "The Ordinary Hyaluronic Acid 2% + B5 Multi-Depth Hydration Serum 30ml",
    "brand": "The Ordinary",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 750,
    "score": 87.5,
    "carbon": 0.9,
    "conv_carb": 2.9,
    "water": 24,
    "lifespan": 0.4,
    "sub": [88, 90, 87, 88, 92, 80, 90],
    "explanation": "3 molecular weights of hyaluronic acid provide layered hydration; minimalist frosted glass bottle with B-Corp certified supply chain.",
    "mats": [{"name": "Frosted Recyclable Glass Bottle", "percentage": 68, "isRecycled": True}, {"name": "Hyaluronic Acid (Bio-fermented) & Pro-Vitamin B5", "percentage": 6, "isRecycled": False, "isRenewable": True}, {"name": "Aqua & Glycerin Base", "percentage": 23, "isRecycled": False}, {"name": "Dropper Cap", "percentage": 3, "isRecycled": False}],
    "pack": "Frosted glass bottle in recyclable paper carton",
    "plastic_free": False,
    "certs": [{"id": "b-corp", "name": "Certified B Corporation", "issuer": "B Lab", "verified": True, "description": "Highest verified social and ecological performance standards"}, {"id": "leaping-bunny", "name": "Leaping Bunny Certified", "issuer": "Cruelty Free International", "verified": True, "description": "Zero animal testing standard"}],
    "strengths": ["DECIEM B-Corp certified brand accountability", "Vegan bio-fermentation hyaluronic acid avoids animal rooster comb origins"],
    "improvements": ["Imported from international manufacturing facilities adds ocean freight emissions"]
  },
  {
    "id": "plum-green-tea-pore-cleansing-face-wash",
    "name": "Plum Green Tea Pore Cleansing Face Wash with Glycolic Acid 100ml",
    "brand": "Plum",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 345,
    "score": 85.5,
    "carbon": 1.1,
    "conv_carb": 3.2,
    "water": 32,
    "lifespan": 0.3,
    "sub": [86, 88, 84, 84, 88, 78, 88],
    "explanation": "Soap-free gentle cleanser with real green tea antioxidant leaves and cellulose beads (zero plastic microbeads).",
    "mats": [{"name": "Green Tea Leaf Extract", "percentage": 20, "isRecycled": False, "isRenewable": True}, {"name": "Plant Cellulose Soft Beads (Biodegradable)", "percentage": 8, "isRecycled": False, "isRenewable": True}, {"name": "Glycolic Acid & Aqua", "percentage": 62, "isRecycled": False}, {"name": "Recycled Tube Plastic", "percentage": 10, "isRecycled": True}],
    "pack": "100% recyclable plastic tube",
    "plastic_free": False,
    "certs": [{"id": "microbead-free", "name": "100% Plastic Microbead-Free Certified", "issuer": "Plum Goodness", "verified": True, "description": "Zero microplastics released to ocean"}, {"id": "peta-vegan", "name": "PETA Certified 100% Vegan", "issuer": "PETA", "verified": True, "description": "No animal ingredients"}],
    "strengths": ["Uses 100% biodegradable natural cellulose beads instead of toxic polyethylene microbeads that poison marine life", "Soap-free SLS-free base"],
    "improvements": ["Plastic flip-top tube is harder to fully squeeze empty without cutting"]
  },
  {
    "id": "himalaya-purifying-neem-face-wash",
    "name": "Himalaya Purifying Neem Face Wash with Turmeric 200ml",
    "brand": "Himalaya",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 240,
    "score": 83.0,
    "carbon": 1.3,
    "conv_carb": 3.4,
    "water": 36,
    "lifespan": 0.4,
    "sub": [84, 85, 82, 80, 84, 76, 86],
    "explanation": "India's bestselling herbal face wash; combines antibacterial organic neem leaves and turmeric root extracts.",
    "mats": [{"name": "Organic Neem (Azadirachta Indica) Extracts", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Turmeric (Curcuma Longa)", "percentage": 10, "isRecycled": False, "isRenewable": True}, {"name": "Gentle Cleansing Base", "percentage": 55, "isRecycled": False}, {"name": "LDPE Recyclable Tube", "percentage": 10, "isRecycled": False}],
    "pack": "Recyclable plastic squeeze tube",
    "plastic_free": False,
    "certs": [{"id": "ayush", "name": "AYUSH Ayurvedic Formulation", "issuer": "Govt of India", "verified": True, "description": "Authentic herbal medicine"}],
    "strengths": ["Time-tested Ayurvedic formulation gently eliminates acne bacteria naturally without synthetic antibiotics", "Affordable pricing"],
    "improvements": ["Tube plastic is virgin polymer"]
  },
  {
    "id": "mamaearth-ubtan-natural-face-wash",
    "name": "Mamaearth Ubtan Natural Face Wash with Turmeric & Saffron 150ml",
    "brand": "Mamaearth",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 399,
    "score": 84.5,
    "carbon": 1.2,
    "conv_carb": 3.3,
    "water": 34,
    "lifespan": 0.3,
    "sub": [85, 87, 83, 82, 86, 78, 88],
    "explanation": "Traditional Indian wedding Ubtan recipe with walnut beads, carrot seed oil, saffron, and turmeric; MadeSafe certified.",
    "mats": [{"name": "Turmeric Root & Saffron Threads", "percentage": 18, "isRecycled": False, "isRenewable": True}, {"name": "Natural Walnut Shell Exfoliating Beads", "percentage": 12, "isRecycled": False, "isRenewable": True}, {"name": "Carrot Seed Oil & Aqua", "percentage": 60, "isRecycled": False, "isRenewable": True}, {"name": "Recycled Tube", "percentage": 10, "isRecycled": True}],
    "pack": "Recyclable tube",
    "plastic_free": False,
    "certs": [{"id": "madesafe", "name": "MadeSafe Certified", "issuer": "Made Safe USA", "verified": True, "description": "Toxin-free guarantee"}],
    "strengths": ["Walnut shell powder replaces synthetic plastic exfoliating beads", "Plastic positive footprint"],
    "improvements": ["Flip-cap plastic hinge can crack if dropped"]
  },
  {
    "id": "forest-essentials-delicate-facial-cleanser",
    "name": "Forest Essentials Delicate Facial Cleanser Kashmiri Saffron & Neem 200ml",
    "brand": "Forest Essentials",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 1550,
    "score": 90.0,
    "carbon": 1.0,
    "conv_carb": 3.6,
    "water": 28,
    "lifespan": 0.5,
    "sub": [91, 94, 88, 90, 92, 82, 92],
    "explanation": "Luxury Ayurvedic cleanser crafted in Uttarakhand using pure spring water, organic cold-pressed oils, and hand-harvested Kashmiri saffron.",
    "mats": [{"name": "Organic Kashmiri Saffron Stigmas", "percentage": 15, "isRecycled": False, "isRenewable": True}, {"name": "Neem Oil & Kewda Floral Water", "percentage": 35, "isRecycled": False, "isRenewable": True}, {"name": "Himalayan Spring Water & Gentle Base", "percentage": 40, "isRecycled": False}, {"name": "Recyclable PET Dispenser Bottle", "percentage": 10, "isRecycled": True}],
    "pack": "Recyclable PET bottle with gold pump in artisanal paper box",
    "plastic_free": False,
    "certs": [{"id": "ayush-premium", "name": "AYUSH Premium Mark", "issuer": "Quality Council of India", "verified": True, "description": "Highest purity export quality Indian herbal benchmark"}, {"id": "cruelty-free", "name": "Cruelty-Free Certified", "issuer": "PETA", "verified": True, "description": "Never tested on animals"}],
    "strengths": ["Made in artisanal workshops powered by renewable hydro power in Uttarakhand foothills", "Zero synthetic petrochemical fragrances or colors", "Saffron sourced from fair-trade cooperatives in Pampore, Kashmir"],
    "improvements": ["Premium luxury pricing limits mass adoption"]
  },
  {
    "id": "forest-essentials-soundarya-radiance-cream",
    "name": "Forest Essentials Soundarya Radiance Cream with 24K Gold 50g",
    "brand": "Forest Essentials",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 5400,
    "score": 91.5,
    "carbon": 0.9,
    "conv_carb": 3.8,
    "water": 22,
    "lifespan": 0.6,
    "sub": [92, 95, 92, 92, 94, 84, 92],
    "explanation": "Traditional Ayurvedic Bhasma recipe prepared by infusing pure 24K gold leaves with saffron and cold-pressed sesame oil in an amber glass jar.",
    "mats": [{"name": "Heavyweight Recyclable Glass Cosmetic Jar", "percentage": 60, "isRecycled": True}, {"name": "Cold-Pressed Sesame & Ghee Base", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Saffron, Ashwagandha & 24K Gold Bhasma", "percentage": 15, "isRecycled": False, "isRenewable": True}],
    "pack": "Heavy luxury glass jar with metal-finish lid in handcrafted gift box",
    "plastic_free": True,
    "certs": [{"id": "ayush-premium", "name": "AYUSH Premium Mark", "issuer": "QCI", "verified": True, "description": "Highest quality standard"}],
    "strengths": ["Packed in heavy 100% recyclable glass jar that can be repurposed indefinitely", "All-natural SPF 25 protection using pure zinc and natural sesame oil filters without oxybenzone"],
    "improvements": ["Ultra-luxury pricing tier"]
  },
  {
    "id": "juicy-chemistry-rosehip-seed-oil",
    "name": "Juicy Chemistry 100% Organic Cold Pressed Rosehip Seed Oil 30ml",
    "brand": "Juicy Chemistry",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 650,
    "score": 93.5,
    "carbon": 0.6,
    "conv_carb": 3.0,
    "water": 14,
    "lifespan": 0.5,
    "sub": [94, 98, 90, 94, 96, 85, 95],
    "explanation": "Certified Organic by Ecocert under COSMOS standards; single ingredient, unrefined, cold-pressed rosehip seed oil in dark UV-resistant glass.",
    "mats": [{"name": "100% Cold-Pressed Organic Rosehip Seed Oil", "percentage": 35, "isRecycled": False, "isRenewable": True}, {"name": "Dark Amber Dropper Bottle (Recycled Glass)", "percentage": 60, "isRecycled": True}, {"name": "Glass Pipette & Rubber Bulb", "percentage": 5, "isRecycled": False}],
    "pack": "100% recyclable amber glass bottle with glass dropper",
    "plastic_free": False,
    "certs": [{"id": "ecocert-cosmos", "name": "ECOCERT COSMOS Organic", "issuer": "Ecocert Greenlife France", "verified": True, "description": "Globally recognized strict organic cosmetic certification"}, {"id": "gmo-free", "name": "Non-GMO Project Verified", "issuer": "Non-GMO Project", "verified": True, "description": "Zero genetic modification"}],
    "strengths": ["100% pure single ingredient with zero fillers, silicones, water, or preservatives", "ECOCERT certified organic farming prevents synthetic pesticide runoff into soils", "Rich in natural trans-retinoic acid for scar and pigmentation healing"],
    "improvements": ["Must be stored away from direct sunlight to preserve active Vitamin A potency"]
  },
  {
    "id": "dot-and-key-cica-calming-sunscreen",
    "name": "Dot & Key Cica Calming Sunscreen SPF 50 PA++++ 80g",
    "brand": "Dot & Key",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 495,
    "score": 85.0,
    "carbon": 1.0,
    "conv_carb": 3.0,
    "water": 28,
    "lifespan": 0.3,
    "sub": [86, 87, 84, 84, 86, 78, 88],
    "explanation": "Water-light chemical-mineral hybrid sunscreen infused with Centella Asiatica (Cica) and Niacinamide; certified reef safe without Oxybenzone or Octinoxate.",
    "mats": [{"name": "Centella Asiatica (Cica) Extract", "percentage": 20, "isRecycled": False, "isRenewable": True}, {"name": "Reef-Safe UV Filter Complex (Tinosorb S & M)", "percentage": 15, "isRecycled": False}, {"name": "Niacinamide & Aqua", "percentage": 55, "isRecycled": False}, {"name": "Recyclable Squeeze Tube", "percentage": 10, "isRecycled": False}],
    "pack": "Recyclable plastic tube with flip cap",
    "plastic_free": False,
    "certs": [{"id": "reef-safe", "name": "Reef Safe Certified (Hawaii Act 104 Compliant)", "issuer": "EcoSun Laboratory", "verified": True, "description": "Free of coral bleaching chemicals Oxybenzone & Octinoxate"}],
    "strengths": ["Reef-safe sunscreen formula protects ocean coral ecosystems from chemical bleaching", "Ultra-lightweight zero white cast formulation suits all Indian skin tones"],
    "improvements": ["Plastic tube packaging"]
  },
  {
    "id": "the-derma-co-1-hyaluronic-sunscreen",
    "name": "The Derma Co 1% Hyaluronic Sunscreen Aqua Gel SPF 50 PA++++ 50g",
    "brand": "The Derma Co",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 499,
    "score": 84.0,
    "carbon": 0.9,
    "conv_carb": 2.9,
    "water": 26,
    "lifespan": 0.3,
    "sub": [85, 86, 83, 83, 85, 78, 86],
    "explanation": "Dermatologist-designed broad spectrum sun protection with 1% hyaluronic acid and Vitamin E, designed specifically for humid Indian climate.",
    "mats": [{"name": "Hyaluronic Acid & Vitamin E", "percentage": 10, "isRecycled": False, "isRenewable": True}, {"name": "Safe UV Blocking Actives", "percentage": 18, "isRecycled": False}, {"name": "Aqua Gel Base", "percentage": 62, "isRecycled": False}, {"name": "Airless Pump Dispenser Tube", "percentage": 10, "isRecycled": False}],
    "pack": "Recyclable plastic pump tube",
    "plastic_free": False,
    "certs": [{"id": "derm-tested", "name": "Dermatologically Tested", "issuer": "Clinical Lab India", "verified": True, "description": "Safe for sensitive skin"}],
    "strengths": ["Non-greasy aqueous gel base absorbs in seconds without leaving oily film", "Protects against blue light from digital screens as well as UVA/UVB"],
    "improvements": ["Airless pump mechanism contains mixed plastic and steel spring components"]
  },
  {
    "id": "foxtale-coverup-dewy-sunscreen",
    "name": "Foxtale CoverUp Dewy Sunscreen SPF 50 PA++++ with Niacinamide 50ml",
    "brand": "Foxtale",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 545,
    "score": 84.5,
    "carbon": 0.9,
    "conv_carb": 2.8,
    "water": 25,
    "lifespan": 0.3,
    "sub": [85, 87, 84, 83, 86, 78, 86],
    "explanation": "Formulated with safe organic UV filters and Provitamin B5 to prevent sun damage while repairing skin barrier.",
    "mats": [{"name": "Provitamin B5 & Niacinamide", "percentage": 15, "isRecycled": False, "isRenewable": True}, {"name": "Broad-spectrum Photostable Filters", "percentage": 18, "isRecycled": False}, {"name": "Hydrating Gel Emulsion", "percentage": 57, "isRecycled": False}, {"name": "Pump Container", "percentage": 10, "isRecycled": False}],
    "pack": "Recyclable plastic pump",
    "plastic_free": False,
    "certs": [{"id": "cruelty-free", "name": "PETA Approved Cruelty-Free", "issuer": "PETA", "verified": True, "description": "No animal testing"}],
    "strengths": ["Zero pilling under makeup or daily moisturizer", "Photostable filters maintain UV protection for 6 continuous hours"],
    "improvements": ["Dispenser bottle is opaque making remaining product volume hard to check"]
  },
  {
    "id": "kama-ayurveda-pure-rose-water",
    "name": "Kama Ayurveda Pure Rose Water Hydrating Face Mist 200ml",
    "brand": "Kama Ayurveda",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 1450,
    "score": 92.0,
    "carbon": 0.8,
    "conv_carb": 3.2,
    "water": 18,
    "lifespan": 0.5,
    "sub": [93, 96, 90, 92, 94, 84, 92],
    "explanation": "Steam distilled from the legendary Rosa Damascena roses of Kannauj (the perfume capital of India), producing 100% pure floral water with zero added alcohol or chemical fragrance.",
    "mats": [{"name": "100% Pure Steam-Distilled Rose Flower Hydrosol", "percentage": 90, "isRecycled": False, "isRenewable": True}, {"name": "Recycled Plastic Spray Bottle", "percentage": 10, "isRecycled": True}],
    "pack": "Recyclable dark spray bottle in luxury paper box",
    "plastic_free": False,
    "certs": [{"id": "ayush-gmp", "name": "AYUSH GMP Certified", "issuer": "Govt of India", "verified": True, "description": "Authentic Ayurvedic distillation standard"}, {"id": "100-natural", "name": "100% Natural Botanical", "issuer": "Kama Ayurveda Labs", "verified": True, "description": "Zero synthetic chemicals"}],
    "strengths": ["Traditional hydro-distillation method preserves natural volatile essential oils without petrochemical solvents", "Provides soothing toner, after-shave, and makeup setting hydration in one bottle"],
    "improvements": ["Spray nozzle mechanism cannot be completely recycled with curbside plastics"]
  },
  {
    "id": "khadi-natural-pure-aloe-vera-gel",
    "name": "Khadi Natural Ayurvedic Pure Aloe Vera Gel 200g (Transparent)",
    "brand": "Khadi Natural",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 220,
    "score": 89.0,
    "carbon": 0.7,
    "conv_carb": 2.8,
    "water": 15,
    "lifespan": 0.5,
    "sub": [90, 93, 86, 88, 90, 80, 92],
    "explanation": "Certified by Khadi and Village Industries Commission (KVIC); pure transparent gel extracted from fresh organic aloe vera barbadensis leaves.",
    "mats": [{"name": "Organic Cold-Extracted Aloe Vera Inner Leaf Gel", "percentage": 92, "isRecycled": False, "isRenewable": True}, {"name": "Natural Food-Grade Stabilizers", "percentage": 3, "isRecycled": False}, {"name": "Recycled Plastic Jar", "percentage": 5, "isRecycled": True}],
    "pack": "Recyclable transparent plastic jar",
    "plastic_free": False,
    "certs": [{"id": "kvic", "name": "Khadi India Certified (KVIC)", "issuer": "Govt of India", "verified": True, "description": "Empowering rural village artisans and farmers"}],
    "strengths": ["Zero artificial green dye; 100% transparent authentic aloe appearance", "Supports rural women farmers and small-scale aloe cultivation in Rajasthan", "Multi-purpose soothing for sunburns, insect bites, and hair conditioning"],
    "improvements": ["Plastic jar lid could be transitioned to metal tin"]
  },
  {
    "id": "cetaphil-gentle-skin-cleanser",
    "name": "Cetaphil Gentle Skin Cleanser for Sensitive Skin 250ml",
    "brand": "Cetaphil",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 540,
    "score": 79.0,
    "carbon": 1.4,
    "conv_carb": 3.2,
    "water": 40,
    "lifespan": 0.5,
    "sub": [80, 78, 84, 80, 84, 74, 82],
    "explanation": "Hypoallergenic, soap-free, non-foaming cleanser with niacinamide and panthenol for compromised skin barriers.",
    "mats": [{"name": "Niacinamide & Panthenol", "percentage": 10, "isRecycled": False}, {"name": "Gentle Cleansing Emulsion", "percentage": 80, "isRecycled": False}, {"name": "HDPE Bottle", "percentage": 10, "isRecycled": False}],
    "pack": "Recyclable HDPE bottle with pump",
    "plastic_free": False,
    "certs": [{"id": "dermatologist", "name": "Dermatologist Recommended", "issuer": "Global Dermatology Board", "verified": True, "description": "Safe for compromised skin barrier"}],
    "strengths": ["Does not strip natural skin moisture lipids", "Can be wiped off with cotton pad without requiring rinse water"],
    "improvements": ["Uses virgin plastics in bottle production"]
  },
  {
    "id": "simple-kind-to-skin-face-wash",
    "name": "Simple Kind to Skin Refreshing Facial Wash 150ml (100% Soap Free)",
    "brand": "Simple",
    "cat": "Personal Care",
    "subcat": "Face Care",
    "price": 385,
    "score": 85.0,
    "carbon": 1.0,
    "conv_carb": 3.0,
    "water": 28,
    "lifespan": 0.4,
    "sub": [86, 87, 84, 84, 88, 78, 88],
    "explanation": "100% soap-free facial wash with triple purified water and vitamin B5; bottle made with 100% post-consumer recycled plastic.",
    "mats": [{"name": "100% PCR Recycled Plastic Tube", "percentage": 10, "isRecycled": True}, {"name": "Pro-Vitamin B5 & Vitamin E", "percentage": 10, "isRecycled": False, "isRenewable": True}, {"name": "Triple Purified Water & Gentle Foamer", "percentage": 80, "isRecycled": False}],
    "pack": "100% PCR recycled plastic tube",
    "plastic_free": False,
    "certs": [{"id": "peta-cruelty-free", "name": "PETA Cruelty-Free Certified", "issuer": "PETA", "verified": True, "description": "Global animal protection"}, {"id": "clean-beauty", "name": "Zero Harsh Chemicals Certified", "issuer": "Simple Skincare", "verified": True, "description": "No artificial perfume or color"}],
    "strengths": ["Tube manufactured from 100% post-consumer recycled plastic", "Free from harsh chemicals, soap, artificial perfume, and parabens"],
    "improvements": ["Liquid gel format consumes water in manufacturing"]
  },

  # --- BATH, BODY & NATURAL SOAPS (10 items) ---
  {
    "id": "dove-deep-moisture-body-wash-pcr",
    "name": "Dove Deep Moisture Nourishing Body Wash in 100% PCR Bottle 800ml",
    "brand": "Dove",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 499,
    "score": 82.5,
    "carbon": 1.7,
    "conv_carb": 4.5,
    "water": 50,
    "lifespan": 0.6,
    "sub": [83, 85, 84, 84, 88, 76, 84],
    "explanation": "Plant-based cleansers with 24-hour microbiome gentle technology; bottle body made from 100% recycled plastic.",
    "mats": [{"name": "100% PCR Recycled Plastic Bottle", "percentage": 12, "isRecycled": True}, {"name": "Plant-based Moisturizers", "percentage": 30, "isRecycled": False, "isRenewable": True}, {"name": "Aqua & Gentle Surfactants", "percentage": 58, "isRecycled": False}],
    "pack": "100% PCR plastic bottle with dispenser pump",
    "plastic_free": False,
    "certs": [{"id": "peta-approved", "name": "PETA Approved Cruelty-Free", "issuer": "PETA", "verified": True, "description": "Global cruelty-free certification"}],
    "strengths": ["100% recycled plastic bottle cuts virgin plastic resin demand by 28 tons annually in India", "Gentle sulfate-free microbiome nourishing wash"],
    "improvements": ["Dispenser pump has internal non-recyclable metal spring"]
  },
  {
    "id": "nivea-creme-soft-shower-gel",
    "name": "Nivea Creme Soft Shower Gel with Almond Oil 500ml",
    "brand": "Nivea",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 375,
    "score": 81.0,
    "carbon": 1.6,
    "conv_carb": 4.2,
    "water": 48,
    "lifespan": 0.5,
    "sub": [82, 83, 83, 82, 86, 76, 82],
    "explanation": "99% biodegradable formula (according to OECD methods) with 96% recycled plastic bottle body.",
    "mats": [{"name": "96% Recycled Plastic Bottle (PCR)", "percentage": 12, "isRecycled": True}, {"name": "Almond Oil & Biodegradable Cleansers", "percentage": 38, "isRecycled": False, "isRenewable": True}, {"name": "Aqua", "percentage": 50, "isRecycled": False}],
    "pack": "96% recycled plastic bottle",
    "plastic_free": False,
    "certs": [{"id": "oecd-biodegradable", "name": "99% Biodegradable Formula", "issuer": "OECD Test 301", "verified": True, "description": "Rapid ecological decomposition in water"}],
    "strengths": ["99% biodegradable formula prevents aquatic ecological buildup", "96% PCR plastic bottle body"],
    "improvements": ["Flip cap made from non-recycled plastic"]
  },
  {
    "id": "khadi-natural-handmade-sandalwood-soap",
    "name": "Khadi Natural Handmade Sandalwood & Honey Herbal Soap Bar 125g",
    "brand": "Khadi Natural",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 105,
    "score": 95.0,
    "carbon": 0.3,
    "conv_carb": 2.4,
    "water": 6,
    "lifespan": 0.3,
    "sub": [96, 98, 92, 96, 98, 92, 94],
    "explanation": "Solid handmade cold-process herbal soap bar packed in 100% plastic-free recycled paper box; uses zero plastic packaging.",
    "mats": [{"name": "Pure Sandalwood Extract & Raw Honey", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Cold-Pressed Coconut & Castor Saponified Oils", "percentage": 65, "isRecycled": False, "isRenewable": True}, {"name": "Glycerin & Natural Spring Water", "percentage": 10, "isRecycled": False}],
    "pack": "100% plastic-free unbleached recycled paper box",
    "plastic_free": True,
    "certs": [{"id": "kvic", "name": "KVIC Khadi Certified", "issuer": "Govt of India", "verified": True, "description": "Supports rural cottage village artisan industries"}, {"id": "plastic-free", "name": "100% Plastic Free Packaging", "issuer": "Khadi Natural", "verified": True, "description": "Zero synthetic polymers"}],
    "strengths": ["100% plastic-free paper carton packaging produces zero municipal plastic waste", "Solid bar format avoids shipping heavy liquid water weight", "Cold-process saponification retains natural glycerin moisturizer"],
    "improvements": ["Must be stored on draining soap dish to prevent bar from dissolving in standing water"]
  },
  {
    "id": "mysore-sandal-gold-soap-125g",
    "name": "Mysore Sandal Gold Pure Natural Sandalwood Oil Soap 125g",
    "brand": "Mysore Sandal",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 175,
    "score": 93.5,
    "carbon": 0.4,
    "conv_carb": 2.5,
    "water": 7,
    "lifespan": 0.3,
    "sub": [94, 96, 92, 95, 96, 90, 95],
    "explanation": "Only soap in the world made with 100% pure natural sandalwood oil distilled from certified sustainable Karnataka government forest reserves (KSDL).",
    "mats": [{"name": "100% Pure Sandalwood Oil (Santalum Album)", "percentage": 15, "isRecycled": False, "isRenewable": True}, {"name": "Pure Vegetable Oil Soap Base", "percentage": 75, "isRecycled": False, "isRenewable": True}, {"name": "Moisturizers & Scent", "percentage": 10, "isRecycled": False}],
    "pack": "Gold foil wrapped in FSC-certified paperboard box",
    "plastic_free": True,
    "certs": [{"id": "gi-tag", "name": "Geographical Indication (GI Tag)", "issuer": "Govt of India GI Registry", "verified": True, "description": "Certified Mysore Sandalwood provenance"}, {"id": "ksdl-pure", "name": "KSDL Pure Sandalwood Oil Mark", "issuer": "Karnataka Soaps & Detergents Ltd", "verified": True, "description": "100% government distilled sandalwood oil"}],
    "strengths": ["Made with pure sandalwood oil from Karnataka state forest conservation reserves", "Solid bar creates zero plastic bottle waste", "Historic 108-year heritage brand"],
    "improvements": ["Inner gold foil wrap has thin protective wax lining"]
  },
  {
    "id": "fiama-gel-bathing-bar-blackcurrant-pack",
    "name": "Fiama Gel Bathing Bar Blackcurrant & Bearberry (Pack of 3, 125g each)",
    "brand": "Fiama",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 240,
    "score": 86.0,
    "carbon": 0.8,
    "conv_carb": 3.0,
    "water": 14,
    "lifespan": 0.4,
    "sub": [87, 88, 86, 86, 90, 84, 86],
    "explanation": "Clear glycerin gel bar infused with natural blackcurrant and bearberry extracts; cardboard carton packaging.",
    "mats": [{"name": "Pure Vegetable Glycerin Base", "percentage": 65, "isRecycled": False, "isRenewable": True}, {"name": "Bearberry & Fruit Extracts", "percentage": 20, "isRecycled": False, "isRenewable": True}, {"name": "Aqua & Gentle Cleansers", "percentage": 15, "isRecycled": False}],
    "pack": "Recyclable cardboard box",
    "plastic_free": True,
    "certs": [{"id": "dermatologist", "name": "Dermatologically Tested", "issuer": "ITC Life Sciences Center", "verified": True, "description": "Skin safety tested"}],
    "strengths": ["Solid gel format avoids plastic pump bottle waste", "High glycerin content keeps skin hydrated in winter"],
    "improvements": ["Inner bars wrapped in thin film moisture barrier"]
  },
  {
    "id": "medimix-ayurvedic-18-herbs-soap-5pack",
    "name": "Medimix Ayurvedic 18 Herbs Classic Bathing Soap (Pack of 5, 125g each)",
    "brand": "Medimix",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 275,
    "score": 93.0,
    "carbon": 0.6,
    "conv_carb": 2.8,
    "water": 12,
    "lifespan": 0.6,
    "sub": [94, 96, 92, 94, 96, 90, 94],
    "explanation": "Traditional Ayurvedic medicinal soap crafted with 18 pure herbal extracts in cold-pressed coconut oil, clinically preventing prickly heat and skin irritation.",
    "mats": [{"name": "18 Ayurvedic Herbs (Neem, Guggulu, Chitraka, etc.)", "percentage": 30, "isRecycled": False, "isRenewable": True}, {"name": "Saponified Pure Coconut Oil", "percentage": 60, "isRecycled": False, "isRenewable": True}, {"name": "Natural Essential Oils & Water", "percentage": 10, "isRecycled": False}],
    "pack": "100% recyclable paperboard outer box",
    "plastic_free": True,
    "certs": [{"id": "ayush", "name": "AYUSH Ayurvedic Drug License", "issuer": "Govt of India", "verified": True, "description": "Medicinal Ayurvedic formulation"}],
    "strengths": ["18 natural herbs treat prickly heat, body odor, and skin rashes with zero synthetic antibacterial triclosan", "Plastic-free paper carton packaging", "Coconut oil base creates dense rich foam with hard groundwater"],
    "improvements": ["Distinct herbal aroma may be strong for users accustomed to floral perfumes"]
  },
  {
    "id": "pears-pure-and-gentle-glycerin-soap-4pack",
    "name": "Pears Pure & Gentle 98% Pure Glycerin Soap (Pack of 4, 125g each)",
    "brand": "Pears",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 340,
    "score": 88.0,
    "carbon": 0.7,
    "conv_carb": 2.8,
    "water": 13,
    "lifespan": 0.5,
    "sub": [89, 90, 88, 88, 92, 85, 88],
    "explanation": "Iconic transparent soap made with 98% pure glycerin and natural oils, aged for 10 weeks in traditional molding vats.",
    "mats": [{"name": "98% Pure Vegetable Glycerin & Natural Oils", "percentage": 85, "isRecycled": False, "isRenewable": True}, {"name": "Natural Rosemary & Thyme Extracts", "percentage": 10, "isRecycled": False, "isRenewable": True}, {"name": "Aqua", "percentage": 5, "isRecycled": False}],
    "pack": "100% recyclable cardboard outer carton",
    "plastic_free": True,
    "certs": [{"id": "dermatologist", "name": "Dermatologically Tested", "issuer": "Unilever R&D", "verified": True, "description": "Ultra gentle for sensitive skin"}],
    "strengths": ["Solid bar format eliminates plastic bottle packaging", "Natural glycerin locks in moisture without petroleum mineral oil"],
    "improvements": ["Glycerin bar wears down faster in humid bathrooms"]
  },
  {
    "id": "dettol-original-antiseptic-soap-4pack",
    "name": "Dettol Original Antiseptic Germ Protection Bathing Soap (Pack of 4, 125g each)",
    "brand": "Dettol",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 260,
    "score": 81.0,
    "carbon": 1.1,
    "conv_carb": 3.0,
    "water": 18,
    "lifespan": 0.5,
    "sub": [82, 81, 86, 84, 88, 80, 82],
    "explanation": "Classic germ protection bar trusted by the Indian Medical Association (IMA) for 100% defense against illness-causing germs.",
    "mats": [{"name": "Vegetable Soap Base (Sodium Palmate/Palm Kernelate)", "percentage": 80, "isRecycled": False, "isRenewable": True}, {"name": "Chloroxylenol (PCMX) Antiseptic", "percentage": 5, "isRecycled": False}, {"name": "Moisturizers & Fragrance", "percentage": 15, "isRecycled": False}],
    "pack": "Paper carton packaging",
    "plastic_free": True,
    "certs": [{"id": "ima", "name": "Indian Medical Association Endorsed", "issuer": "IMA", "verified": True, "description": "Clinical germ protection endorsement"}],
    "strengths": ["Proven clinical defense against tropical skin infections", "Zero plastic bottle waste compared to liquid handwash"],
    "improvements": ["Uses conventional palm oil soap base"]
  },
  {
    "id": "lifebuoy-total-10-soap-4pack",
    "name": "Lifebuoy Total 10 Antibacterial Soap Bar (Pack of 4, 125g each)",
    "brand": "Lifebuoy",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 180,
    "score": 80.0,
    "carbon": 1.2,
    "conv_carb": 3.0,
    "water": 19,
    "lifespan": 0.5,
    "sub": [81, 80, 85, 83, 88, 80, 82],
    "explanation": "Activ Silver+ formula protects against 10 infection-causing germs; paper carton multi-pack.",
    "mats": [{"name": "Soap Noodles (Vegetable Palm Blend)", "percentage": 82, "isRecycled": False, "isRenewable": True}, {"name": "Silver Oxide & Germ Protection Actives", "percentage": 8, "isRecycled": False}, {"name": "Aqua & Fragrance", "percentage": 10, "isRecycled": False}],
    "pack": "Cardboard outer carton",
    "plastic_free": True,
    "certs": [{"id": "bis-isi", "name": "BIS Toilet Soap Standard (IS 2888)", "issuer": "BIS India", "verified": True, "description": "Grade 1 toilet soap standard"}],
    "strengths": ["High Total Fatty Matter (TFM 70%) Grade 1 toilet soap", "Affordable public hygiene protection in cardboard wrapper"],
    "improvements": ["Contains artificial red coloring dye"]
  },
  {
    "id": "cinthol-original-soap-4pack",
    "name": "Cinthol Original Deodorant and Complexion Soap (Pack of 4, 100g each)",
    "brand": "Godrej",
    "cat": "Personal Care",
    "subcat": "Body & Bath",
    "price": 210,
    "score": 82.0,
    "carbon": 0.9,
    "conv_carb": 2.8,
    "water": 16,
    "lifespan": 0.4,
    "sub": [83, 83, 86, 84, 88, 82, 84],
    "explanation": "High 79% TFM Grade 1 soap bar with active deodorant formula; manufactured at Godrej green factory.",
    "mats": [{"name": "Grade 1 TFM 79% Vegetable Soap Base", "percentage": 85, "isRecycled": False, "isRenewable": True}, {"name": "Active Deodorant Fragrance & TCC", "percentage": 10, "isRecycled": False}, {"name": "Aqua", "percentage": 5, "isRecycled": False}],
    "pack": "Paper carton",
    "plastic_free": True,
    "certs": [{"id": "bis-grade1", "name": "BIS Grade 1 Toilet Soap", "issuer": "BIS", "verified": True, "description": "Highest cleansing and lather quality standard"}],
    "strengths": ["High 79% TFM means bar lasts significantly longer without turning mushy in soap dish", "Paper carton packaging"],
    "improvements": ["Strong distinctive scent"]
  },

  # --- ORAL CARE (5 items) ---
  {
    "id": "colgate-total-antibacterial-toothpaste",
    "name": "Colgate Total 12H Antibacterial Protection Fluoride Toothpaste 150g",
    "brand": "Colgate",
    "cat": "Personal Care",
    "subcat": "Oral Care",
    "price": 145,
    "score": 84.0,
    "carbon": 0.6,
    "conv_carb": 1.6,
    "water": 12,
    "lifespan": 0.25,
    "sub": [85, 86, 84, 85, 88, 80, 86],
    "explanation": "Packaged in first-of-its-kind recyclable HDPE toothpaste tube (Tube #2 HDPE), certified for curbside plastic recycling streams.",
    "mats": [{"name": "100% Recyclable High-Density Polyethylene Tube (#2 HDPE)", "percentage": 12, "isRecycled": False}, {"name": "Zinc & Arginine Dual-Action Plaque Defense", "percentage": 18, "isRecycled": False}, {"name": "Hydrated Silica & Fluoride", "percentage": 30, "isRecycled": False}, {"name": "Aqua & Glycerin Base", "percentage": 40, "isRecycled": False}],
    "pack": "100% recyclable HDPE tube in FSC-certified paperboard carton",
    "plastic_free": False,
    "certs": [{"id": "apr-recyclable", "name": "Association of Plastic Recyclers (APR) Certified", "issuer": "APR USA", "verified": True, "description": "First globally certified curbside recyclable toothpaste tube"}, {"id": "ida", "name": "Indian Dental Association (IDA) Accepted", "issuer": "IDA", "verified": True, "description": "Clinically proven plaque defense"}],
    "strengths": ["First major brand to open-source its recyclable HDPE toothpaste tube design to competitors for free", "Zinc and arginine technology fights plaque bacteria for 12 continuous hours", "Fluoride protects enamel from dental decay"],
    "improvements": ["Tube cap is polypropylene (#5) which must be screwed on tightly before recycling"]
  },
  {
    "id": "dabur-red-ayurvedic-toothpaste",
    "name": "Dabur Red Ayurvedic Herbal Toothpaste with Clove & Mint 300g",
    "brand": "Dabur",
    "cat": "Personal Care",
    "subcat": "Oral Care",
    "price": 185,
    "score": 86.5,
    "carbon": 0.8,
    "conv_carb": 2.0,
    "water": 15,
    "lifespan": 0.4,
    "sub": [87, 89, 86, 86, 88, 82, 90],
    "explanation": "India's No. 1 Ayurvedic toothpaste crafted with 13 traditional herbs including Clove oil (Laung), Pudina, and Tomar seed.",
    "mats": [{"name": "13 Ayurvedic Botanical Herbs (Clove, Mint, Tomar)", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Calcium Carbonate Natural Abrasive", "percentage": 35, "isRecycled": False, "isRenewable": True}, {"name": "Recyclable Tube & Herbal Aqua Base", "percentage": 40, "isRecycled": False}],
    "pack": "Recyclable tube in paper carton",
    "plastic_free": False,
    "certs": [{"id": "ayush", "name": "AYUSH Ayurvedic Formulation", "issuer": "Govt of India", "verified": True, "description": "Authentic herbal medicine"}, {"id": "clinical", "name": "Clinically Proven 35% Better Oral Care", "issuer": "Indian Dental University", "verified": True, "description": "Reduces plaque and gingivitis"}],
    "strengths": ["Clove oil (eugenol) provides natural pain relief and antibacterial protection without synthetic triclosan", "Tomar seed protects against common dental sensitivity"],
    "improvements": ["Traditional spicy clove taste may be intense for young children"]
  },
  {
    "id": "sensodyne-rapid-relief-toothpaste",
    "name": "Sensodyne Rapid Relief Clinically Proven Toothpaste 80g",
    "brand": "Sensodyne",
    "cat": "Personal Care",
    "subcat": "Oral Care",
    "price": 220,
    "score": 80.0,
    "carbon": 0.5,
    "conv_carb": 1.4,
    "water": 10,
    "lifespan": 0.2,
    "sub": [81, 80, 82, 80, 84, 76, 84],
    "explanation": "Stannous fluoride formula creates an occlusive mineral barrier over exposed dentin tubules in 60 seconds, eliminating tooth sensitivity.",
    "mats": [{"name": "Stannous Fluoride Actives", "percentage": 10, "isRecycled": False}, {"name": "Hydrated Silica & Glycerin Base", "percentage": 78, "isRecycled": False}, {"name": "Recyclable Polymer Tube", "percentage": 12, "isRecycled": False}],
    "pack": "FSC-certified paper carton with recyclable tube",
    "plastic_free": False,
    "certs": [{"id": "ida", "name": "IDA Accepted", "issuer": "Indian Dental Association", "verified": True, "description": "Clinically proven sensitivity relief"}],
    "strengths": ["Provides rapid 60-second sensitivity relief", "Prevents unnecessary dental nerve intervention treatments"],
    "improvements": ["Tube is smaller (80g) producing higher packaging-to-product ratio"]
  },
  {
    "id": "colgate-bamboo-charcoal-toothbrush-2pack",
    "name": "Colgate Bamboo Charcoal Soft Bristle Eco Toothbrush (Pack of 2)",
    "brand": "Colgate",
    "cat": "Personal Care",
    "subcat": "Oral Care",
    "price": 249,
    "score": 93.0,
    "carbon": 0.3,
    "conv_carb": 1.8,
    "water": 5,
    "lifespan": 0.3,
    "sub": [94, 96, 88, 95, 96, 92, 92],
    "explanation": "Handle carved from 100% natural sustainably grown biodegradable Moso bamboo, coated with beeswax to prevent bathroom moisture mold.",
    "mats": [{"name": "100% Natural Biodegradable Bamboo Handle", "percentage": 92, "isRecycled": False, "isRenewable": True}, {"name": "Natural Beeswax Waterproof Coating", "percentage": 2, "isRecycled": False, "isRenewable": True}, {"name": "BPA-Free Charcoal Infused Floss-Tip Bristles", "percentage": 6, "isRecycled": False}],
    "pack": "100% plastic-free recycled cardboard box with zero blister plastic windows",
    "plastic_free": True,
    "certs": [{"id": "fsc", "name": "FSC Certified Moso Bamboo", "issuer": "Forest Stewardship Council", "verified": True, "description": "Harvested from sustainably managed bamboo plantations that do not displace giant pandas"}, {"id": "plastic-free", "name": "100% Plastic-Free Packaging", "issuer": "Colgate-Palmolive", "verified": True, "description": "Zero blister plastic packaging"}],
    "strengths": ["Handle is 100% backyard compostable and returns to organic soil within 6 months", "Eliminates hundreds of non-recyclable polypropylene plastic toothbrushes from landfills", "Beeswax finish prevents water swelling"],
    "improvements": ["Bristles are nylon and must be snapped off with pliers before composting the bamboo handle"]
  },
  {
    "id": "bare-necessities-copper-tongue-cleaner",
    "name": "Bare Necessities Pure Copper Tongue Cleaner (Handcrafted Ergonomic)",
    "brand": "Bare Necessities",
    "cat": "Personal Care",
    "subcat": "Oral Care",
    "price": 225,
    "score": 97.0,
    "carbon": 0.2,
    "conv_carb": 2.2,
    "water": 4,
    "lifespan": 20.0,
    "sub": [98, 98, 100, 98, 98, 100, 95],
    "explanation": "Handcrafted from 100% pure Ayurvedic copper in Karnataka; antimicrobial properties kill oral bacteria on contact and lasts for decades.",
    "mats": [{"name": "100% Pure Antimicrobial Copper", "percentage": 100, "isRecycled": True}],
    "pack": "100% compostable unbleached butter paper envelope with cotton string",
    "plastic_free": True,
    "certs": [{"id": "ayurvedic-heritage", "name": "Ayurvedic Heritage Oral Care", "issuer": "Ayush Board", "verified": True, "description": "Traditional non-toxic metal"}, {"id": "zero-waste", "name": "Zero Waste Packaging Certified", "issuer": "Bare Necessities Zero Waste", "verified": True, "description": "100% plastic-free compostable"}],
    "strengths": ["Copper is naturally oligodynamic and antibacterial, sterilizing itself between daily uses", "Lasts 20+ years, replacing dozens of flimsy disposable plastic tongue scrapers", "Zero plastic packaging"],
    "improvements": ["Develops natural copper patina over time (easily cleaned with lemon and salt)"]
  },

  # --- GROOMING & DEODORANTS (4 items) ---
  {
    "id": "nivea-men-fresh-active-roll-on",
    "name": "Nivea Men Fresh Active 48H Ocean Extracts Roll-On Deodorant 50ml",
    "brand": "Nivea",
    "cat": "Personal Care",
    "subcat": "Grooming",
    "price": 215,
    "score": 84.5,
    "carbon": 0.6,
    "conv_carb": 2.2,
    "water": 16,
    "lifespan": 0.3,
    "sub": [86, 86, 88, 86, 88, 80, 84],
    "explanation": "Glass roll-on bottle with zero aluminum chlorohydrate alcohol aerosol propellants, preventing VOC air emissions.",
    "mats": [{"name": "Recyclable Glass Bottle", "percentage": 70, "isRecycled": True}, {"name": "Ocean Extracts & Fragrance Formula", "percentage": 22, "isRecycled": False}, {"name": "Polypropylene Roller Ball & Cap", "percentage": 8, "isRecycled": False}],
    "pack": "Glass bottle without external paper box",
    "plastic_free": False,
    "certs": [{"id": "cfc-free", "name": "Zero Aerosol Propellants", "issuer": "Beiersdorf AG", "verified": True, "description": "Zero aerosol greenhouse gas propellants"}],
    "strengths": ["Roll-on format produces zero volatile greenhouse gas aerosol propellants compared to spray deodorants", "Heavy glass bottle is 100% recyclable in municipal glass bins"],
    "improvements": ["Roller ball must be popped out before glass bottle recycling"]
  },
  {
    "id": "bombay-shaving-company-metal-safety-razor",
    "name": "Bombay Shaving Company Precision Single-Blade Metal Safety Razor (Matte Black)",
    "brand": "Bombay Shaving Company",
    "cat": "Personal Care",
    "subcat": "Grooming",
    "price": 999,
    "score": 96.0,
    "carbon": 2.4,
    "conv_carb": 18.0,
    "water": 45,
    "lifespan": 30.0,
    "sub": [97, 98, 100, 98, 96, 100, 94],
    "explanation": "Engineered from brass and zinc alloy with chrome plating to last a lifetime; uses recyclable steel razor blades costing ₹5 each, eliminating plastic cartridge waste.",
    "mats": [{"name": "Heavy Solid Brass & Zinc Alloy Handle and Head", "percentage": 92, "isRecycled": True}, {"name": "Feather Stainless Steel Double Edge Blade", "percentage": 8, "isRecycled": True}],
    "pack": "100% recyclable rigid paperboard box with magnetic closure",
    "plastic_free": True,
    "certs": [{"id": "zero-plastic", "name": "Zero Plastic Shaving Certified", "issuer": "BSC Sustainable Initiative", "verified": True, "description": "Eliminates multi-blade plastic disposable heads"}],
    "strengths": ["Single metal razor handle lasts 30+ years, saving over 300 disposable plastic razor cartridges from landfills per user", "Double-edge steel blades cost only ₹5-10 each compared to ₹250 for multi-blade plastic cartridges", "Single sharp blade cuts hair cleanly at skin level, eliminating ingrown hairs and razor bumps"],
    "improvements": ["Requires careful technique at a 30-degree angle compared to pivoting plastic razors"]
  },
  {
    "id": "beardo-godfather-beard-oil",
    "name": "Beardo Godfather Natural Aloe & Almond Nourishing Beard Oil 30ml",
    "brand": "Beardo",
    "cat": "Personal Care",
    "subcat": "Grooming",
    "price": 350,
    "score": 88.0,
    "carbon": 0.5,
    "conv_carb": 2.0,
    "water": 12,
    "lifespan": 0.4,
    "sub": [89, 91, 88, 88, 92, 82, 88],
    "explanation": "Cold-pressed sweet almond, olive, and argan oils in an amber glass bottle with precision dropper.",
    "mats": [{"name": "Sweet Almond & Olive Cold-Pressed Oils", "percentage": 40, "isRecycled": False, "isRenewable": True}, {"name": "Argan Oil & Vitamin E", "percentage": 20, "isRecycled": False, "isRenewable": True}, {"name": "Dark Amber Glass Bottle", "percentage": 37, "isRecycled": True}, {"name": "Pipette", "percentage": 3, "isRecycled": False}],
    "pack": "Recyclable amber glass dropper bottle in paper box",
    "plastic_free": False,
    "certs": [{"id": "paraben-free", "name": "100% Paraben & Mineral Oil Free", "issuer": "Beardo Labs", "verified": True, "description": "Pure plant oils"}],
    "strengths": ["Zero petroleum mineral oil, parabens, or synthetic silicones", "Amber glass bottle completely recyclable"],
    "improvements": ["Rubber dropper bulb contains small synthetic elastomer"]
  },
  {
    "id": "bombay-shaving-company-pre-shave-scrub",
    "name": "Bombay Shaving Company Exfoliating Pre-Shave Scrub with Black Sand 100g",
    "brand": "Bombay Shaving Company",
    "cat": "Personal Care",
    "subcat": "Grooming",
    "price": 325,
    "score": 86.5,
    "carbon": 0.8,
    "conv_carb": 2.6,
    "water": 20,
    "lifespan": 0.4,
    "sub": [87, 88, 86, 86, 90, 80, 88],
    "explanation": "Uses real black volcanic sand and walnut shell powder to lift ingrown hairs before shaving without synthetic plastic microbeads.",
    "mats": [{"name": "Natural Volcanic Black Sand & Walnut Shell", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Shea Butter & Papaya Extract", "percentage": 25, "isRecycled": False, "isRenewable": True}, {"name": "Cream Base & Tube", "percentage": 50, "isRecycled": True}],
    "pack": "Recyclable plastic tube",
    "plastic_free": False,
    "certs": [{"id": "microbead-free", "name": "Microbead-Free Certified", "issuer": "BSC", "verified": True, "description": "100% natural mineral exfoliation"}],
    "strengths": ["Natural volcanic sand exfoliator completely biodegrades harmlessly", "Shea butter prevents razor burn"],
    "improvements": ["Tube packaging"]
  }
]
